### ISSUE TITLE
ValueError when running SpatialNeuron with method='exponential_euler'

### ISSUE THREAD

**Issue by psipeter** [brian-team/brian2#1010]
Here's a minimal example:

```
from brian2 import *

eqns = ''' 
Im = amp/meter**2: amp/meter**2
dk/dt = Hz : 1   # breaks exponential_euler
'''

soma = Soma(diameter=15*um)
neuron = SpatialNeuron(morphology=soma, model=eqns, method='exponential_euler')
briannet = Network(neuron)
briannet.run(1*ms)
```

produces

> The expression "Hz", defining the variable k, could not be separated into linear components
> UnsupportedEquationsException: Can only solve conditionally linear systems with this state updater.

Other numerical integration methods work fine. I am running brian2.1.3.1, and can run other examples involving SpatialNeurons and exponential_euler without problems (e.g. [Hodgkin_Huxley](https://brian2.readthedocs.io/en/stable/examples/compartmental.hh_with_spikes.html)).

**Comment by mstimberg** [comment]
Oops, good catch! It's not tied to `SpatialNeuron` but seems to be a general failure of the `exact` and the `exponential_euler` state updaters to deal with trivial equations where the RHS is just a constant. E.g. the following fails:
```pycon
>>> exact(Equations('dv/dt = 10*Hz : 1'))
...
UnsupportedEquationsException: Cannot solve the given equations with this stateupdater.
```
