### ISSUE TITLE
Issues about changes of Brian1

### ISSUE THREAD

**Issue by ljxgit** [brian-team/brian2#1016]
In brian1 simulator, there is a function "raster_plot" that can refresh the curve with the parameters "refrsh=" and "showlast=", but in brian2tools, there are no such parameters in the function "plot_raster" , how can I implement the curve refresh? Thanks!

**Comment by mstimberg** [comment]
Answered on the mailing list: https://groups.google.com/d/msg/briansupport/d6ePt80pDQE/B8qpc59gBQAJ
