### ISSUE TITLE
Ornstein–Uhlenbeck example in docs wrong

### ISSUE THREAD

**Issue by RinaldoB** [brian-team/brian2#1019]
https://brian2.readthedocs.io/en/stable/user/models.html?highlight=ornstein#noise

it reads:
`G = NeuronGroup(10, 'dv/dt = -v/tau + sigma*xi*tau**-0.5 : volt')`

should read:
`G = NeuronGroup(10, 'dv/dt = -v/tau + sigma*xi*tau**-0.5*2**0.5 : volt')`

or, nicer:
`G = NeuronGroup(10, 'dv/dt = -v/tau + sigma*sqrt(2/tau)*xi :  volt')`

**Comment by mstimberg** [comment]
Hi and thanks, you are right. Strictly speaking we *do* describe a OU process, but of course it is nicer if `sigma` has the expected meaning. I changed the documentation to match your last suggestion.
