### ISSUE TITLE
Cannot debug on Windows because of py-cpuinfo

### ISSUE THREAD

**Issue by Chris-Currin** [brian-team/brian2#1020]
py-cpuinfo has an error on Windows, [Broken when using Pyinstaller](https://github.com/workhorsy/py-cpuinfo/issues/80), which was fixed in a PR, but Brian2 uses py-cpuinfo 3.20 which does not have this fix.

Weirdly, this only occurs when debugging (in PyCharms/IntelliJ), running is fine.

This can be reproduced on a Windows machine by running
`> python -c "import cpuinfo; print(cpuinfo.actual_get_cpu_info_from_cpuid())"`
or
`> python -c "from brian2 import *"`
```
File "C:\Users\Chris\Anaconda3\lib\site-packages\cpuinfo\cpuinfo.py", line 560, in _asm_func
    if memmove(address, byte_code, size) < 0:
OSError: exception: access violation writing 0xFFFFFFFF95460000
```

If one then does 
`> pip uninstall py-cpuinfo -y` 
`> pip install py-cpuinfo -y`
```
brian2 2.2 has requirement py-cpuinfo!=4.0.0,>=0.1.6, but you'll have py-cpuinfo 4.0.0 which is incompatible.
```

Then py-cpuinfo v4 should be installed. Running 
`>python -c "import cpuinfo; print(cpuinfo.get_cpu_info())"` works. (command changed with the version)

It seems brian2 code can then be debugged fine, **except** the code runs twice.

The alternative is just to do *only* `> pip uninstall py-cpuinfo -y`  
(note that `> conda uninstall py-cpuinfo ` wants to remove brian2 too)
and then the exception that the module does not exist is caught.

Has this been investigated more?

**Comment by mstimberg** [comment]
Hi. We excluded py-cpuinfo 4.0 because it has this annoying "run scripts twice" problem on Windows (see #990). I'm not quite sure I understand your problem with 3.2 (note that there's also a version 3.3), you say you are seeing it only in debug mode, but why can you reproduce it then with the lines you mention? And what does this have to do with using pyinstaller? You see, I'm confused :) 

Note that as a workaround, you *can* use py-cpuinfo 4.0, but you have to wrap your script with:
```Python
if __name__ == '__main__':
    from brian2 import *
    ...
```

**Comment by Chris-Currin** [comment]
Thanks for the response!

It is understandably confusing as I do not know (for certain) why it only happens during debug mode either. Presumably, it is because the debug mode uses the `--multiproc` arg. This is what is run in IntelliJ when debugging:
`>python C:\Users\Chris\.IntelliJIdea2018.2\config\plugins\python\helpers\pydev\pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 55565 --file sim.py`

The py-cpuinfo fix for windows involves the multiprocessing library, so it was some sort of thread issue. 
In the docs for `actual_get_cpu_info_from_cpuid` it did say not to run it directly, but instead to use another method that spawns a thread for the command. I would guess during a normal run the multiprocessing of python is actually done in one thread, but during debug (with --muliproc) it does use another. That would be my educated guess.

I'll check out V3.3 and see if that has the fix (their github releases only has V4.0.0).

Thanks for the workaround for V4.0 too

**Comment by Chris-Currin** [comment]
V3.3 still has the issue. 

Adding this seems to work though isn't recommended (https://github.com/workhorsy/py-cpuinfo/issues/108#issuecomment-420506977):
```
import cpuinfo
cpuinfo.DataSource.can_cpuid = False
```

**Comment by mstimberg** [comment]
Ok, good to know. I'll have a look at this in a Windows VM as well (I'm on Linux). It might actually be a similar issue as the Cython debugging problem which I reported a while ago (without any reply unfortunately): https://youtrack.jetbrains.com/issue/PY-27833 The debug mode seems indeed to be messing with multiprocessing.

**Comment by mstimberg** [comment]
I just realized that you can switch off the `--multiproc` flag by unchecking "Attach to subprocess automatically while debugging" in "Build, Execution, Deployment > Python Debugger". This fixes/works around the Cython debugging issue and probably also your problem?

**Comment by Chris-Currin** [comment]
Thanks, can confirm it works.

I think I will stick to another workaround as the flag is useful for other
projects I am working on.

At least a number of options have been presented which can help others
encountering this issue!

**Comment by denisalevi** [comment]
Its not OS-dependent. I get the same error on Linux with py-cpuinfo 3.3, brian2 version 2.1 and 2.2, pycharm 2016.3 and pycharm 2018.2.

**Comment by mstimberg** [comment]
@psrmx and @denisalevi , thanks for that info, I can now reproduce the problem but only when using Python 3. I guess that's what you are using?

**Comment by psrmx** [comment]
Yes, Python 3.6 and Brian2 version 2.2.
