### ISSUE TITLE
can Brian2 support Max-pooling function?

### ISSUE THREAD

**Issue by hellolingling** [brian-team/brian2#1040]
Hi, Marcel, sorry to disturb you. Recently I am trying to use brian2 to convert the CNN model 'LeNet' into SNN. But when writing code on max-pooling layer, it seems I cannot obtain the spike_counts every dt. With my shallow understanding of Brian2, I can only obtain the spike_counts of NeuronGroup when the whole simulation of one trial(such as net.run (1000*ms)) ends. In this way, I cannot choose the neurons with maximum firing rate  at every time step and pass the spikes of the neurons to the next layer to form the max-pooling layer.
Could you tell me if my understanding is right? Or how can I  implement the function? Looking forward to your reply!

**Comment by mstimberg** [comment]
Closing this for now, please feel free to open it if the question is still relevant.
