### ISSUE TITLE
SpikeGeneratorGroup period checking error

### ISSUE THREAD

**Issue by kevincuallado** [brian-team/brian2#1041]
I needed to run a SpikeGeneratorGroup on a period, so I created one using the following command:
`ing = SpikeGeneratorGroup(1, [0, 0, 0, 0, 0], [0, 45, 75, 105, 135]*ms, period=150*ms, name='ing')`.
When running the network, I got this error :  
`NotImplementedError: The period of ing is <ing.period: 150. * msecond>, which is not an integer multiple of its dt of 0.0001.`

I decided to make a barebone example to check it wasn't working, as well print what the SpikeGeneratorGroup.before_run() is testing for:

```python
from brian2 import SpikeGeneratorGroup, ms, run
import numpy as np

period = 150*ms
ing = SpikeGeneratorGroup(1, [0], [0]*ms, period=150*ms, name='ing')
dt = ing.dt

print(str(abs(int(period/dt)*dt - period)) + ' > '
      + str(period * np.finfo(dt.dtype).eps))

run(300*ms)
```
I receive the same error when running this code; the print outputs this : 
`100. us > 33.30669074 as`
I tried again but with a period of 100*ms; the print outputs is the same but this time the network runs. 
It would seem there's a precision problem when checking the period of SpikeGeneratorGroup. 
I think the test should be relaxed to be only as precise as the `dt` itself, to avoid this kind of error.

**Comment by mstimberg** [comment]
Thanks, I did not have a chance to look at this before (holidays and all), but this looks indeed like a bug, the check should be less strict. I also wonder whether it should rather be a warning instead of an error? Apart from that, the error message has some formatting issues that should be addressed as well.

**Comment by kevincuallado** [comment]
Thanks! Also, regarding the warning; it's an interesting idea; I wonder though: is there any case where one would not want to have their spike times being multiples of `dt`?

**Comment by mstimberg** [comment]
> I wonder though: is there any case where one would not want to have their spike times being multiples of `dt`?

I had situations in mind where you'd not care about the exact value of the period, say something with `period='np.random.rand()*100*ms`. But then, not sure whether this is really relevant, and the way to fix it should be clear from the error message.

**Comment by kevincuallado** [comment]
Well, if the period is not a multiple of `dt`, some of the spike times might not be valid anymore if I recall correctly; I'm not sure if would be a good idea to notch it down to a warning. Besides, in your example, as long as `100*ms` is a multiple of your `dt` you'll be fine.

**Comment by mstimberg** [comment]
> Well, if the period is not a multiple of `dt`, some of the spike times might not be valid anymore if I recall correctly; I'm not sure if would be a good idea to notch it down to a warning.

Um, you are actually right, our current algorithm would silently drop spikes in this case. It should definitely continue to be an error and not a warning.

> Besides, in your example, as long as `100*ms` is a multiple of your `dt` you'll be fine.

My example creates a random number between 0 and 100ms, i.e. it will be something like `42.96592444*ms` and therefore in general not a multiple of `dt`.
