### ISSUE TITLE
Can't import brian2 in google colab

### ISSUE THREAD

**Issue by daphn3cor** [brian-team/brian2#1048]
first I ran this command in colab

`!pip install brian2`

then this `import brian2`

and get this error `AttributeError: module 'brian2' has no attribute 'numpy_'`

Are there different commands I can run so I could use brian2 in colab?

**Comment by mstimberg** [comment]
Hi. I just tried this in a fresh Colab (with Python 2 and Python 3), and for me it works without error message. Do you maybe have something else installed in the same runtime that interferes with the Brian installation? Do you get any other error message before the `AttributeError`?

**Comment by daphn3cor** [comment]
You're right, I just ran it again and no error...
However there doesn't seem to be a `brain2tools` but it may be from the old version still.
`ModuleNotFoundError: No module named 'brian2tools'`

**Comment by mstimberg** [comment]
`brian2tools` is a separate package (https://brian2tools.readthedocs.io/en/stable/), you should be able to install it via `!pip install brian2tools` as well.

**Comment by daphn3cor** [comment]
Thank you Marcel, my bad :)
