### ISSUE TITLE
Brian2 integration with Tensorflow

### ISSUE THREAD

**Issue by eghbalhosseini** [brian-team/brian2#1052]
Hi, 
I am curious if currently there are any means to integrate brian2 networks into Tensor Flow. Specifically, importing a spiking network in brian2 as a new RNN cells, and defining relevant gradients for graph computation. 

Thanks, 
Eghbal Hosseini

**Comment by mstimberg** [comment]
Sorry for the late reply, I thought I already answered... 

In principle, everything is possible, you can write a function that takes in inputs and calculates outputs by running a Brian network, and calculate the gradient in some way. In practice, I think this would run into quite a few complications, and I don't think it would be a good fit. Brian is really about biological networks, there are other frameworks that are more adapted to machine learning questions.

**Comment by eghbalhosseini** [comment]
thanks for the information, could you point me towards the other frameworks that you mentioned that are are suited for machine learning questions.

**Comment by mstimberg** [comment]
I'm really not an expert on this topic, but there are examples that directly describe spiking networks in tensorflow (http://www.kaizou.org/2018/07/simulating-spiking-neurons-with-tensorflow/) and there's e.g. https://github.com/Hananel-Hazan/bindsnet -- I'm sure there are quite a few others.
