### ISSUE TITLE
unable to install brian2 using rtd-environment.yml

### ISSUE THREAD

**Issue by RahulMaram** [brian-team/brian2#1060]
Cloned the repository and trying to create a new environment and install brian2 but I am getting the following error message although most of the packages are installed successfully.
anaconda  version = 4.4.0
I Execute the following command : conda env create -f rtd_environment.yml
___________________________________________________________________________________________________
Error:

Executing transaction: |
Please note that Brian2's conda package does not automatically install a
C++ compiler. Such a compiler is necessary to benefit from C++ code
generation and the resulting improved performance.
See the 'Requirements for C++ code generation' section at
     http://brian2.readthedocs.io/en/2.2.1/introduction/install.html
for details.

failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'conda-forge::brian2-2.2.1-py36he980bc4_1000'.
LinkError: post-link script failed for package conda-forge::brian2-2.2.1-py36he980bc4_1000
running your command again with `-v` will provide additional information
location of failed script: C:\\Anaconda3\envs\brienv\Scripts\.brian2-post-link.bat
==> script messages <==

Please note that Brian2's conda package does not automatically install a
C++ compiler. Such a compiler is necessary to benefit from C++ code
generation and the resulting improved performance.
See the 'Requirements for C++ code generation' section at
     http://brian2.readthedocs.io/en/2.2.1/introduction/install.html
for details.

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::brian2-2.2.1-py36he980bc4_1000
running your command again with `-v` will provide additional information
location of failed script: C:\\Anaconda3\envs\brienv\Scripts\.brian2-post-link.bat
==> script messages <==

Please note that Brian2's conda package does not automatically install a
C++ compiler. Such a compiler is necessary to benefit from C++ code
generation and the resulting improved performance.
See the 'Requirements for C++ code generation' section at
     http://brian2.readthedocs.io/en/2.2.1/introduction/install.html
for details.

**Comment by mstimberg** [comment]
This seems to be the same issue as reported on the mailing list: https://groups.google.com/d/topic/briansupport/mi_ClsTf2sM/discussion As far as I can tell, this is not a Brian issue, but rather a problem with recent versions of conda (maybe try a `conda update conda` ?). Also note that the `rtd_environment.yml` file is not intended to be used for installation, it's what we use to install Brian on readthedocs, i.e. the documentation hosting site. Right now, it does more or less a full installation but that might again change in the future.

As I mentioned on the mailing list, a workaround for now seems to be to only use conda to install the dependencies:
```
conda install -c conda-forge --only-deps brian2
```
and then install Brian 2 via pip, either the latest release:
```
pip install brian2
```
or the version you cloned from github:
```
pip install .
```

**Comment by RahulMaram** [comment]
Thanks ! it was a conda problem.
