### ISSUE TITLE
sympy issue with inf symbol

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#1061]
Here's a problem, running this:

```Python
from brian2 import *

eqs = '''
dv/dt = (x-v)/(10*ms) : 1
x = clip(sin(2*pi*100*Hz*t), -inf, 0) : 1
'''

G = NeuronGroup(1, eqs)
M = StateMonitor(G, 'v', record=True)
run(100*ms)
plot(M.t/ms, M.v.T)
```

gives

```
KeyError: 'The identifier "oo" could not be resolved.'
```

Turns out somewhere along the line, ``inf`` is getting turned into ``oo``, presumably by sympy?

I'm running sympy 1.2 here.

**Comment by mstimberg** [comment]
Good catch! We deal with `inf` correctly, but it turns out that `-inf` is not represented as `-1*inf` by `sympy`, but instead as a proper constant `NegativeInfinity`.

The fix should be very straightforward, expect a PR soon.
