### ISSUE TITLE
slicing on Neurogroup

### ISSUE THREAD

**Issue by baixiaotian63648995** [brian-team/brian2#1070]
Hello,

When I want to do slicing operation on NeuroGroup such as:
`P = NeuronGroup(4000, eqs, threshold='v>-50*mV', reset='v=-60*mV')`
`Pi = P[:3200:2]`
It appeared` IndexError('Subgroups have to be contiguous')`.
So I want to ask if there is a way to make this operation come true.
Especially,is it possible that let  the neurons arrange like:''ex,ex,inh,ex,ex,inh,ex,ex,inh,....."

Thanks for your attention.

**Comment by mstimberg** [comment]
Hi,

> So I want to ask if there is a way to make this operation come true.
> Especially,is it possible that let the neurons arrange like:''ex,ex,inh,ex,ex,inh,ex,ex,inh,....."

no, as the error message states, subgroups have to be continuous. This is mostly for efficiency reasons: many operations have to check whether a given neuron is part of a subgroup which is easy/fast to do if we only have to check whether its index lies in a certain range, but would be much more difficult if we would have to check it against an arbitrary list of indices.

However, the indices itself do not have any meaning; if you want two thirds of your network to be excitatory, then just use the first/last two thirds of your neurons. I do not see what you would gain by interspersing excitatory and inhibitory indices.

**Comment by baixiaotian63648995** [comment]
> Hi,
> 
> > So I want to ask if there is a way to make this operation come true.
> > Especially,is it possible that let the neurons arrange like:''ex,ex,inh,ex,ex,inh,ex,ex,inh,....."
> 
> no, as the error message states, subgroups have to be continuous. This is mostly for efficiency reasons: many operations have to check whether a given neuron is part of a subgroup which is easy/fast to do if we only have to check whether its index lies in a certain range, but would be much more difficult if we would have to check it against an arbitrary list of indices.
> 
> However, the indices itself do not have any meaning; if you want two thirds of your network to be excitatory, then just use the first/last two thirds of your neurons. I do

**Comment by baixiaotian63648995** [comment]
> Hi,
> 
> > So I want to ask if there is a way to make this operation come true.
> > Especially,is it possible that let the neurons arrange like:''ex,ex,inh,ex,ex,inh,ex,ex,inh,....."
> 
> no, as the error message states, subgroups have to be continuous. This is mostly for efficiency reasons: many operations have to check whether a given neuron is part of a subgroup which is easy/fast to do if we only have to check whether its index lies in a certain range, but would be much more difficult if we would have to check it against an arbitrary list of indices.
> 
> However, the indices itself do not have any meaning; if you want two thirds of your network to be excitatory, then just use the first/last two thirds of your neurons. I do not see what you would gain by interspersing excitatory and inhibitory indices.

Thanks for your reply,

About interspersing excitatory and inhibitory indices, I think it is more realistic for simulating a network in which neurons are connected more possibly to neurons close to and arranged in a certain rule.
