### ISSUE TITLE
reducing the memory comsumption

### ISSUE THREAD

**Issue by XiaoquinNUDT** [brian-team/brian2#1072]
Hello,
Can anyone provide some tips for reducing the memory consumption in Brian2 ?  Only the final state of simulation is needed.
I can't connecting to 'http://groups.google.com/group/briansupport/' for some reasons, so I submit the request as an issue here.
Thanks.

**Comment by mstimberg** [comment]
If you are only interest in the final state of the simulation, you should remove/deactivate all monitors. Did you do this already and your simulation is still taking too much memory? Can you give more details about your stimulation?

**Comment by XiaoquinNUDT** [comment]
Thanks for your reply. I have removed the monitors as you suggested, and run the simulation to test the memory consumption again. The test showed that it is the monitor that increase the memory consumption. In addition, it is the StateMonitor that consume the most memory during running. So, I will not add the StateMonitor in a long run but in short run to record the states for analysis.
While, it may be better if a record 'dt' can be defined in the StateMonitor assuming it is easy to realize.
Thanks again!
Best wishes!

**Comment by mstimberg** [comment]
Well, the `StateMonitor` records the values of the state variables you ask it to record, for every neuron you ask it to record, for every time step, to memory. For long simulations/large networks/many variables, this will inevitably take up a lot of memory. 

> While, it may be better if a record 'dt' can be defined in the StateMonitor assuming it is easy to realize.

You can already set the `dt` for a  `StateMonitor`: https://brian2.readthedocs.io/en/stable/reference/brian2.monitors.statemonitor.StateMonitor.html
