### ISSUE TITLE
wonder how model equations work in Brian2

### ISSUE THREAD

**Issue by sestring** [brian-team/brian2#1077]
According to model equations in the Brian2 documentation, I did not see the description of how equations operate when the network runs. So I wonder how differential equation `dv/dt=((v_rest_e - v) + (I_synE+I_synI) / gleak) / taum_e  : volt` calculates variable v.   The variable I_synE has no innitial value, and its definition follows this equation as `I_synE = ge * (-v)                           : amp`. 
If you know why, please help me. Thank you~

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

I have to say that I do not quite understand the question. The variable `v` gets integrated using a numerical integration method either chosen by you or automatically (see [the documentation](https://brian2.readthedocs.io/en/stable/user/numerical_integration.html)). If you define `I_synE` via an equation, then it is not a variable but what we call a "subexpression", i.e. it is simply replaced by its definition in the differential equation defining `v`.

**Comment by mstimberg** [comment]
Closing this due to lack of response, feel free to reopen the issue if there is still something unclear.
