### ISSUE TITLE
Array of SpikeMonitor

### ISSUE THREAD

**Issue by vslobody** [brian-team/brian2#1079]
Hello,
I want to have few SpikeMonitors arrange as array, so that i can access them by index.
for example, is it possible to have something like this:
```
G_orientation = NeuronGroup(number_of_layers * number_neurons_per_layer, eqs);
spike_mon[0]=SpikeMonitor(G_orientation[:number_neurons_per_layer]);
spike_mon[1]=SpikeMonitor(G_orientation[number_neurons_per_layer: 2 * number_neurons_per_layer]);

```
Thanks much in advance.
Volodimir

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

Yes, you can do this, but you need to use proper Python syntax:
```Python
spike_mon = [SpikeMonitor(G_orientation[:number_neurons_per_layer]),
             SpikeMonitor(G_orientation[number_neurons_per_layer: 2 * number_neurons_per_layer])]
```
You can then access them via `spike_mon[0]` and `spike_mon[1]`. Note that Brian will not automatically "see" monitors defined in this way, i.e. you cannot use a simple `run` statement but you need to explicitly create a `Network` object. See: https://brian2.readthedocs.io/en/stable/user/running.html#networks
