### ISSUE TITLE
 Hodgkin Huxley equations with your Synapse and NeuronGroup classes.

### ISSUE THREAD

**Issue by cuong450** [brian-team/brian2#1089]
Hi I am trying to use the Hodgkin Huxley equations with your Synapse and NeuronGroup classes. Unfortunately it is not simply copying and pasting the (https://hub.gke.mybinder.org/user/brian-team-brian2-binder-2fezm5yh/notebooks/examples/compartmental/hh_with_spikes.ipynb) Diff Equations into the 
https://hub.gke.mybinder.org/user/brian-team-brian2-binder-hb3tnmuf/notebooks/tutorials/2-intro-to-brian-synapses.ipynb

Please give me suggestions to achieve this task of getting a synaptic network of Hodgkin Huxley modeled neurons. Thank you.

Code and Error below:

start_scope()
​
eqs = '''
# The same equations for the whole neuron, but possibly different parameter values
# distributed transmembrane current
Im = gl * (El-v) + gNa * m**3 * h * (ENa-v) + gK * n**4 * (EK-v) : amp/meter**2
I : amp (point current) # applied current
dm/dt = alpham * (1-m) - betam * m : 1
dn/dt = alphan * (1-n) - betan * n : 1
dh/dt = alphah * (1-h) - betah * h : 1
alpham = (0.1/mV) * (-v+25*mV) / (exp((-v+25*mV) / (10*mV)) - 1)/ms : Hz
betam = 4 * exp(-v/(18*mV))/ms : Hz
alphah = 0.07 * exp(-v/(20*mV))/ms : Hz
betah = 1/(exp((-v+30*mV) / (10*mV)) + 1)/ms : Hz
alphan = (0.01/mV) * (-v+10*mV) / (exp((-v+10*mV) / (10*mV)) - 1)/ms : Hz
betan = 0.125*exp(-v/(80*mV))/ms : Hz
gNa : siemens/meter**2
'''
​
G = NeuronGroup(2, eqs, threshold='v>1', reset='v = 0', method='exact')
G.I = [2, 0]
G.tau = [10, 100]*ms
​
# Comment these two lines out to see what happens without Synapses
S = Synapses(G, G, on_pre='v_post += 0.2')
S.connect(i=0, j=1)
​
M = StateMonitor(G, 'v', record=True)
​
run(100*ms)
​
plot(M.t/ms, M.v[0], label='Neuron 0')
plot(M.t/ms, M.v[1], label='Neuron 1')
xlabel('Time (ms)')
ylabel('v')
legend();
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-62810341fcda> in <module>
     18 '''
     19 
---> 20 G = NeuronGroup(2, eqs, threshold='v>1', reset='v = 0', method='exact')
     21 G.I = [2, 0]
     22 G.tau = [10, 100]*ms

/srv/conda/envs/notebook/lib/python3.6/site-packages/brian2/groups/neurongroup.py in __init__(self, N, model, method, method_options, threshold, reset, refractory, events, namespace, dtype, dt, clock, order, name, codeobj_class)
    431                            PARAMETER: ('constant', 'shared', 'linked'),
    432                            SUBEXPRESSION: ('shared',
--> 433                                            'constant over dt')})
    434 
    435         # add refractoriness

/srv/conda/envs/notebook/lib/python3.6/site-packages/brian2/equations/equations.py in check_flags(self, allowed_flags, incompatible_flags)
   1009                                       'flag "%s", only the following flags '
   1010                                       'are allowed: %s') % (eq.type,
-> 1011                                                             flag, allowed_flags[eq.type]))
   1012                 # Check for incompatibilities
   1013                 for flag_combinations in incompatible_flags:

ValueError: Equations of type "parameter" cannot have a flag "point current", only the following flags are allowed: ('constant', 'shared', 'linked')

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

You are mixing two things here: 1) multicompartmental models (defined in `SpatialNeuron` that is used in the `hh_with_spikes.py` example) where you define the membrane current and Brian takes care of updating the membrane potential `v` using this current and the axial current across compartments; 2) single-compartment ("point-neuron") models, where you directly provide a differential equation for the membrane potential `v` (there is no axial current here to take care of). 

For an example of HH neurons in a network, see [the COBAHH example](https://brian2.readthedocs.io/en/stable/examples/COBAHH.html).
