### ISSUE TITLE
Converting to ODE form

### ISSUE THREAD

**Issue by MunozatABI** [brian-team/brian2#1092]
Hi, I am trying to implement a channel conductance equation and I'm wanting to convert it to ODEs like in your examples given at https://brian2.readthedocs.io/en/stable/user/converting_from_integrated_form.html

I have worked through your example of the spike response model, exponential and alpha synapses, but cannot seem to understand how you converted the biexponential synapse. I looked at using a Z-transform but it still doesn't give me the equations you have. Since my example is quite similar to the biexponential I'd really appreciate it if you could expand on this further, or let me know how best I can implement my equation I attached below.

Thank you!

![Eqn](https://user-images.githubusercontent.com/51766200/59392631-6e024c80-8dcc-11e9-9f76-243004a6de56.PNG)

**Comment by thesamovar** [comment]
It looks like your $g(t)$ is just a scaled version of the bi-exponential synapse? The differential equations are linear, so just multiply by a constant, the basic form of the equations should be the same.
