### ISSUE TITLE
RunTimeError in cpp standalone mode

### ISSUE THREAD

**Issue by ulyssek** [brian-team/brian2#1106]
Hi there,

I'm sorry, I'm sure it's a very dumb issue here, but I can't find why it's not working.

I'm trying to launch two different simulations in one python script using cpp_standalone mode.

My script is very simple

`brian.set_device('cpp_standalone', build_on_run=False)`
`n = Network(seed=0,default_kwargs=default_kwargs,**kwargs)`
`n1 = Network(seed=0,default_kwargs=default_kwargs,**kwargs1)`
`n.run_network()`
`n1.run_network()`
`brian.device.build(directory='output', compile=True, run=True, debug=False)`

Where Network is a custom object having a brian network as a variable. run_network() will run this network.

Unfortunately, for absurd confidentiality reasons, I can't show you the full code.

When launching, I have this error 

`
g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make: *** [objects.o] Error 4
make: *** Waiting for unfinished jobs....
makefile:31: recipe for target 'objects.o' failed
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /var/tmp/pbs.292850.pbsserver/brian_debug_w5xqgwmp.log  Additionally, you can also include a copy of the script that was run, available at: /var/tmp/pbs.292850.pbsserver/brian_script_l3lpefdb.py You can also include a copy of the redirected std stream outputs, available at /var/tmp/pbs.292850.pbsserver/brian_stdout_6msgj4v2.log and /var/tmp/pbs.292850.pbsserver/brian_stderr_zilh50b8.log Thanks! [brian2]
Traceback (most recent call last):
  File "/home/uk259060/neuron_paper/ptah/crun.py", line 49, in <module>
    brian.device.build(directory='output', compile=True, run=True, debug=False)
  File "/home/uk259060/.local/lib/python3.5/site-packages/brian2/devices/cpp_standalone/device.py", line 1192, in build
    self.compile_source(directory, compiler, debug, clean)
  File "/home/uk259060/.local/lib/python3.5/site-packages/brian2/devices/cpp_standalone/device.py", line 972, in compile_source
    raise RuntimeError(error_message)
RuntimeError: Project compilation failed (error code: 512). Consider running with "clean=True" to force a complete rebuild.
`

Something I'm doing wrong ?

Thanks a lot,

**Comment by mstimberg** [comment]
From what I can see, this is not a problem with Brian but rather a potential bug in the g++ compiler itself. You seem to be using gcc 5, could you try using a newer version and see whether the problem still occurs?

**Comment by mstimberg** [comment]
Closing this for now, feel free to reopen it if you have new information.
