### ISSUE TITLE
Using loops for multiple summed variables

### ISSUE THREAD

**Issue by MunozatABI** [brian-team/brian2#1109]
Hi Brian2 Team, 

To get around the multiple summed variables error for multiple synapses, I have used for loops to generate the code in dictionaries. But I have found that I need to also redefine the synapses outside of a dictionary (as shown in the short example code below where I just connect one spike generator to 2 neurons). Is this the best way to do this for multiple synapses? Or is there a better way to get the synapses definitions read out from a dictionary?

Thanks for your help!
![CodeSnippet](https://user-images.githubusercontent.com/51766200/61597378-26d96800-ac64-11e9-915f-dd562f5fd668.PNG)

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

Objects that are in dictionaries or other containers are indeed not recognized when you use a simple `run`, but I would strongly advice against your `exec` based approach and instead create a `Network` object. See the documentation here: https://brian2.readthedocs.io/en/stable/user/running.html#networks
