### ISSUE TITLE
Adding Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by tapaswenipathak** [brian-team/brian2#1113]
Hey maintainers: Can the project has Contributor Covenant Code of Conduct added https://en.wikipedia.org/wiki/Contributor_Covenant?

**Comment by thesamovar** [comment]
I would have no objection to this. @mstimberg any thoughts?

**Comment by mstimberg** [comment]
Fine from my side as well!
@tapaswenipathak Do you want to open a PR adding the CoC? I guess the contact email address should be ``team@briansimulator.org``

**Comment by thesamovar** [comment]
Does anyone read that email address?

**Comment by mstimberg** [comment]
> Does anyone read that email address?

Mails are simply forwarded to Romain, you, and me :)

**Comment by thesamovar** [comment]
Ah OK that works then. :)

**Comment by mstimberg** [comment]
Oh, I just saw that github has a feature to add the CoC (a bit hidden: https://github.com/brian-team/brian2/community) – I'll just go ahead and add it, then.

**Comment by tapaswenipathak** [comment]
Thanks for keeping me out of the discussion and attaching the CoC instead.
