### ISSUE TITLE
Add more functions (e.g. expm1)

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#1117]
We might want to add more predefined functions, in particularly those that are part of the C++ standard (and therefore need basically no work to add). I'm mostly thinking about `expm1` (which is `exp(x) -1`, but more accurate for x close to 0), and potentially `log1p` (`log(1 + x)`) for completeness. Then, we should probably also add something like `exprel` (`expm1(x) / x`, but returning 1 for x=0), which is easily implemented if we have `expm1` (see e.g. [scipy's implementation in Cython](https://github.com/scipy/scipy/blob/0a5bb3ba367d34a93bbd6b6afe886fb842911a3a/scipy/special/_exprel.pxd#L7-L13)).

One thing I am wondering though is: in rate equations, what you often use is:
`x/(exp(x/y) - 1)`. Now, with `exprel`, you can express this in a safe way by writing `y/exprel(x/y)`, but I am not sure this is obvious to most users. Many NEURON models instead define a `vtrap` function, i.e. `vtrap(x, y) = x/(exp(x/y) - 1)`, but this name seems very NEURON-specific to me. Maybe there is some other standard name for this, though?@thesamovar, @romainbrette any thoughts?

Just to show that having such a function could have practical relevance: For a typical rate equation from the HH model like this
```
beta_m = 0.28*(mV**-1)*(V+23*mV)/
        (exp((V+23*mV)/(5*mV))-1)/ms : Hz
```
we will have the obvious problem that for V=-23mV, this will give NaN – but of course with floating point values getting *exactly* to -23mV is rather unlikely. However. if we are very close to this number, we already get inaccurate results due to catastrophic cancellation. This plot shows the values from the above equation in blue and the corrected solution with `exprel` in orange:

![accuracy](https://user-images.githubusercontent.com/1381982/64446475-2e9c8100-d0d9-11e9-9bfc-83237955bcd6.png)

Of course you need to be really close (the axis shows the difference to -23mV in **nano**volt) and the absolute differences are rather small, but still...

**Comment by thesamovar** [comment]
I don't know of a standard name. I'm wondering how difficult it would be to automatically pattern match for this and replace instances of ``x/(exp(x/y) - 1)`` with ``exprel``?

**Comment by mstimberg** [comment]
Hmm, yes, maybe `sympy` could deal with this. Worth checking out, it would be great if we could avoid forcing users to think about these numerical details!

**Comment by mstimberg** [comment]
As a follow up on this issue: I tried pattern matching and automatic substitution with `sympy`, but did not get it robustly to work. The problem is that e.g. if you try to match `5*mV/(10*mv)` with `x/y` it might give you something like `x=5*mV/(10*mv), y=1`, there are ways around it but I'm not very confident that it will work in general. Maybe a better approach would be to parse the AST, e.g. as part of the `ArithmeticSimplifier`, but this is already quite messy at it is and I think we should do a refactoring first.

**Comment by mstimberg** [comment]
After merging #1141 we support `expm1`, `log1p`, and `exprel`. Closing this issue for now.
