### ISSUE TITLE
List dependencies in README

### ISSUE THREAD

**Issue by c-torre** [brian-team/brian2#1125]
Hi, is it possible that you list your dependencies in the README?

They are not immediately obvious under a new user perspective, especially the fact that you use Python 2.X.

See an example from https://github.com/mne-tools/mne-python/blob/master/README.rst:

    The minimum required dependencies to run MNE-Python are:

    Python >= 3.5
    NumPy >= 1.12.1
    SciPy >= 0.18.1

    For full functionality, some functions require:

    Matplotlib >= 2.0.2
    Mayavi >= 4.6
    PySurfer >= 0.8
    Scikit-learn >= 0.18.2
    Numba >= 0.40
    NiBabel >= 2.1.0
    Pandas >= 0.19.2
    Picard >= 0.3
    CuPy >= 4.0 (for NVIDIA CUDA acceleration)
    DIPY >= 0.10.1
    PyVista >= 0.20.1

**Comment by mstimberg** [comment]
Hi, thanks for the suggestion, we should indeed make the dependencies clearer (even though most users simply install via `pip` or `conda` and will get the dependencies installed automatically). For now, they are only listed in [setup.py](https://github.com/brian-team/brian2/blob/master/setup.py) itself.

Not sure what you mean by "especially the fact that you use Python 2.X." – Brian 2 runs with Python 2 (for now), but it of course also runs with Python 3.
