### ISSUE TITLE
OS X builds failing on Python 2.7

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#1128]
Our travis builds have been failing on OS X with Python 2.7 for a while, I'm not sure whether it is a general issue or only some configuration issue on the travis server. It warns that:
```
Compiling with an SDK that doesn't seem to exist: /opt/MacOSX10.9.sdk
Please check your Xcode installation
[....]
clang: warning: no such sysroot directory: '/opt/MacOSX10.9.sdk' [-Wmissing-sysroot]
```
And then fails to find header files:
```
In file included from /Users/travis/miniconda/envs/travis_conda/include/python2.7/Python.h:33:
/Applications/Xcode-9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
              ^~~~~~~~~
1 error generated.
```
Given that I cannot debug this on my own machine and that Python 2.7 reaches its end of life in less than two months, I'm not very motivated to debug this much further. For now, I'll simply mark the failing runs as "allowed to fail".

**Comment by mstimberg** [comment]
Example of a failing test: https://travis-ci.org/brian-team/brian2/jobs/607144454

**Comment by thesamovar** [comment]
Now that we're not supporting Python 2 any more should we close this?

**Comment by mstimberg** [comment]
> Now that we're not supporting Python 2 any more should we close this?

A bit late but: yes :)
