### ISSUE TITLE
Can we process Dynamic Vision Sensors (.aedat or .aedat4) data using Brian2?

### ISSUE THREAD

**Issue by shyam302** [brian-team/brian2#1139]
Hi, 
Is it possible to use DVS data with Brian2. If possible then how we can proceed with .aedat4 or .aedat data?

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

If you just want to "replay" the output from a DVS camera as spikes which you then use as input to a network, you can use a [`SpikeGeneratorGroup`](https://brian2.readthedocs.io/en/stable/user/input.html#spike-generation). Brian does not have a mechanism to specifically deal with any event data format like `.aedat`, but it should be straightforward to read in these files and convert them into a list of indices and times that are needed by the `SpikeGeneratorGroup`.
