### ISSUE TITLE
Error occurs when running example

### ISSUE THREAD

**Issue by wjx0914** [brian-team/brian2#1145]
Using "pip install brian2 --user" ,it show install successfully! But brian2.test() shows  that installation is not completely successful ！when i run example on Ubuntu and python3 environment，the error occurs as following picture，it is unable to draw（‘plot’ has error），how should i solve it?

**Comment by wjx0914** [comment]
![error](https://user-images.githubusercontent.com/43661240/71245403-9062bd00-234f-11ea-8f49-95829015a7f4.png)

**Comment by mstimberg** [comment]
The error you are showing is not from Brian but an error related to the general configuration of your graphics system. I guess if you run some trivial matplotlib code like:
```pycon
>>> import matplotlib.pyplot as plt
>>> plt.plot([1, 2], [3, 4])
>>> plt.show()
```
you will get the same error. Is this really the full error message? I guess it might have to do with e.g. trying to run code on a remote server, but I am afraid we cannot help you with this kind of problem.

**Comment by mstimberg** [comment]
Closing for lack of information.
