### ISSUE TITLE
Multiple call to `rand()` does not raise error in Synapses code

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#1146]
When running this code:
```python
from brian2 import *

set_device('cpp_standalone')
G = NeuronGroup(1, 'x: 1', threshold='True')
G.x = 'rand() * rand()'

run(1*defaultclock.dt)
```
I get 
```
NotImplementedError: The expression "rand() * rand()" contains more than one call of rand, this is currently not supported since rand is a stateful function and its multiple calls might be treated incorrectly (e.g."rand() - rand()" could be  simplified to "0.0").
```
But if I use multiple `rand()` calls in `Synapses` code, the error does not appear. E.g.:
```python
from brian2 import *

set_device('cpp_standalone')
G = NeuronGroup(1, 'x: 1', threshold='True')
syn = Synapses(G, G, 'dw/dt = rand() * rand()/ms: 1', on_pre='x += w')

run(1*defaultclock.dt)
```
In the generated cpp code, the `rand()` calls are still simplified to `_brian_pow(rand(), 2)`. I guess this should also throw an error?

EDIT: tested in brian2 version 2.2.1

**Comment by mstimberg** [comment]
Hi. I cannot reproduce this with the most recent version, maybe we fixed this issue somewhere along the way?

**Comment by mstimberg** [comment]
Oops, my mistake, I *can* reproduce the issue now. I'll try to have a closer look soon.
