### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by lemonade117** [brian-team/brian2#1148]
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\ADMINI~1\AppData\Local\Temp\brian_debug_8f31z7gi.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\ADMINI~1\AppData\Local\Temp\brian_script_zrkbn4bx.py Thanks! [brian2]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 58, in paintEvent
    memoryview(reg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\cbook\__init__.py", line 2116, in _unmultiplied_rgba8888_to_premultiplied_argb32
    if alpha8.min() != 0xff:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)

**Comment by lemonade117** [comment]
Anyone has the same problem?

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

It is hard to say without further details, but the typical reason for "zero-size array" errors is that you are trying to do something with an empty array, e.g. providing it as an argument for a plotting function.

**Comment by lemonade117** [comment]
Thanks for your response.
