### ISSUE TITLE
Help docs for Multicompartment Models - define stimulation

### ISSUE THREAD

**Issue by risecourse** [brian-team/brian2#1153]
In the example code for the Help section [brian2/docs_sphinx/user/multicompartmental.rst](https://brian2.readthedocs.io/en/stable/user/multicompartmental.html) there is a code line `S = Synapses(stimulation, neuron, on_pre='gs += w')` that errors out for me because I had not previously defined `stimulation`. Can you add a line of code to define the `stimulation` to this tutorial?

**Comment by mstimberg** [comment]
Hi. The idea is that `stimulation` can be anything you want, e.g. a `PoissonGroup`, a `NeuronGroup` or another `SpatialNeuron`. I'm not sure that adding a specific object here would be that helpful, a lot of other things necessary for running the simulation are missing here. This page is not a tutorial – but admittedly having a tutorial for multicompartmental models would be helpful.

**Comment by risecourse** [comment]
Gotcha
