### ISSUE TITLE
Investigate issues with parallel processes using Cython

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#1154]
According to a report on the [development mailing list](https://groups.google.com/d/topic/brian-development/FkeRd7BP9yM/discussion), running many simulations in parallel (with Cython) can sometimes lead to processes freezing. I'd say the most likely cause is a deadlock with the lock files we use to protect processes from trying to write to the same source files. In the [`filelock` branch](https://github.com/brian-team/brian2/tree/filelock), I replaced our own locking system by https://github.com/benediktschmitt/py-filelock , which seems to be a bit more mature and well-tested.
However, this does not seem to fix all issues.

**Comment by mstimberg** [comment]
I tried to reproduce the issue by simply launching many identical trivial Brian scripts in parallel, but all worked fine.

**Comment by mstimberg** [comment]
I tried a few more things like artificially slowing down the locking process, but still no luck.

@wilhelmbraun can you figure out at what stage your scripts are freezing? The filelocking module will not only log the acquire/release message but also "attempt to acquire/release" on the debug level. You'll find the debug message in the log file (path stored in `BrianLogger.tmp_log`), or on the console if you set `BrianLogger.log_level_debug()`.

**Comment by wilhelmbraun** [comment]
I used `BrianLogger.log_level_debug()` and got this output (one for each process, this repeats ad infinitum and the process status is 'S' or 'D' in tpo:

`
DEBUG      Attempting to acquire lock 140632110356408 on /home/wilhelm/.cython/brian_extensions/_cython_magic_ffbd4e816d2c35fa3fa6d87e8b22f05d.lock [brian2.utils.filelock]
...

DEBUG      Lock 140632110354840 not acquired on /home/wilhelm/.cython/brian_extensions/_cython_magic_ffbd4e816d2c35fa3fa6d87e8b22f05d.lock, waiting 0.05 seconds ... [brian2.utils.filelock]
...
`
Thanks!

**Comment by wilhelmbraun** [comment]
As an additional observation, using `clear_cache('cython')` takes a long time to execute (several minutes sometimes), which is unusual in my experience.

**Comment by mstimberg** [comment]
I still don't have a good handle at this issue. I artificially slowed down write operations on the Cython directory and go something like what you describe, i.e. a long sequence of failed attempts to acquire the lock, but in the end it all worked out, it simply took a long time. But your observation about the very slow `clear_cache` function points to disk access being very slow on your setup. The `clear_cache` function simply walks through the directory and deletes files individually – this should certainly not take minutes. There is no file locking involved here, though, so this is an independent issue.

While slow disk access could explain some of your observations, I don't quite see how it could depend on the number of processes. As a wild guess: if you increase the number of processes above a certain value, do some of the processes maybe land on a node that is otherwise not used and has very slow disk access for some reason? Maybe you could write some Python script (independent of Brian) to test this theory?

**Comment by wilhelmbraun** [comment]
> While slow disk access could explain some of your observations, I don't quite see how it could depend on the number of processes. As a wild guess: if you increase the number of processes above a certain value, do some of the processes maybe land on a node that is otherwise not used and has very slow disk access for some reason? Maybe you could write some Python script (independent of Brian) to test this theory?

I can exclude this possibility- the script gets exclusively executed on one node.

**Comment by mstimberg** [comment]
:man_shrugging: well, well. Just to get an idea: how many processes do you launch in parallel when you have the issue? And just to be sure: you are only executing `clear_cache('cython')` in one process only, right?

**Comment by wilhelmbraun** [comment]
I launch between 20 and 30 processes in parallel. I use `clear_cache('cython')` before the start of the simulation.

**Comment by wilhelmbraun** [comment]
I also just checked whether my brian2 script might be the source of the problem, so I replaced it with a very simple one (https://brian2.readthedocs.io/en/stable/examples/frompapers.Brunel_Hakim_1999.html), but the error persists.
@mstimberg, how do you call the different processes? I define a function inside which the network gets simulated (using magic syntax), this is then passed to `multiprocessing.Process()`, pushed to a queue and then the results are gathered.

**Comment by mstimberg** [comment]
I did two things: one was starting them from a bash script (i.e. several calls of `python ... &`) and the other one was from Python. I also used the `multiprocessing` package but slightly differently:
```Python
with multiprocessing.Pool(20) as p:
    results = p.map(my_func, arguments)
```

**Comment by wilhelmbraun** [comment]
Ok, can you maybe explain to me how brian2 is called in my_func, and what kind of shape results has? Maybe a longer snippet would be really helpful. Thanks!

**Comment by mstimberg** [comment]
I used a wildcard import and the simple magic system to write the Brian sim. The results are a list with whatever the function returned, in the same order as the arguments (`p.map` works like `map`, i.e. in the end `results = [myfunc(arg) for arg in arguments]`)`).

The code I used is this (not doing anything interesting obviously, and no need to actually plot stuff):
```Python
import os
import multiprocessing

from brian2 import *

def run_sim(tau):
    pid = os.getpid()
    print(f'RUNNING {pid}')
    G = NeuronGroup(1, 'dv/dt = -v/tau : 1', method='exact')
    G.v = 1
    mon = StateMonitor(G, 'v', record=0)
    run(100*ms)
    print(f'FINISHED {pid}')
    return (mon.t/ms, mon.v[0])

clear_cache('cython')

tau_values = np.arange(20)*ms + 5*ms
with multiprocessing.Pool(20) as p:
    results = p.map(run_sim, tau_values)

for tau_value, (t, v) in zip(tau_values, results):
    plt.plot(t, v, label=str(tau_value))
plt.legend()
plt.show()
```

**Comment by wilhelmbraun** [comment]
Thanks, this code actually worked in my setup too, but there still are many failed releases and locks. I think that my original code might also get executed at some point, if one waits a long time. However, the above code isn't suitable for what I want because my equivalent of `run_sim` takes in more than 1 argument and also returns an array of fixed length, so I am not sure this can be done as above.

**Comment by mstimberg** [comment]
> but there still are many failed releases and locks.

Failed locks are normal, after all we wouldn't need any locks if they always succeeded. A failed lock simply means that the other process compiling the source needed by this process is not finished yet. I don't think the release can fail, though?


> However, the above code isn't suitable for what I want because my equivalent of `run_sim` takes in more than 1 argument and also returns an array of fixed length, so I am not sure this can be done as above.

You can hand over more than one argument, either by unpacking it in the function manually (i.e. the single argument is actually a tuple or dict of arguments), or by using [`Pool.starmap` ](https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.pool.Pool.starmap). Not sure what you mean by the return value, `Pool.map` does not care about what you return, it just puts it into a list.  You can always transform it into something else later.

**Comment by wilhelmbraun** [comment]
> Failed locks are normal, after all we wouldn't need any locks if they always succeeded. A failed lock simply means that the other process compiling the source needed by this process is not finished yet. I don't think the release can fail, though?
Sorry, yes, only the locks failed ('Lock 123 not aquired').
Thanks a lot for the other tips. I'll try them out and let you know whether it helped.

**Comment by wilhelmbraun** [comment]
Update: I changed your code so that it fits my purposes (multiple inputs/ lists as outpus), and let it run on my local machine (without the new brian2 version with the new filelock system), and it ran fine. However, on my cluster, it still produced many instances of 'Lock 123 not aquired' and so the problem remains there. Can this be related to the version of cython?

**Comment by mstimberg** [comment]
The only way I could see how the version of Cython would change anything here is that they might simply cythonize/compile faster or slower.

> However, on my cluster, it still produced many instances of 'Lock 123 not aquired' and so the problem remains there.

Do you get stdout from all of the processes? I wonder if the simple fact of printing a lot of stuff to stdout and the log files slows things down. Assuming everything goes smoothly: if all of your 20 processes run the same code and the code compilation takes 2s, we'd expect to see ~800 messages about not being able to acquire locks (each process will try every 0.05s). Maybe you could manually reduce `filelock`'s polling interval to see clearer? There's unfortunately no way to configure it currently, but you could manually change it in this line:
https://github.com/brian-team/brian2/blob/8c47a31c3c34ff8246fcf654b21776a77ecc008c/brian2/utils/filelock.py#L219

**Comment by wilhelmbraun** [comment]
As suggested, I changed `poll_intervall` in `filelock.py` to 0.01 and the problem does not reappear, this time robustly so. Thanks so much. I just wonder why this issue never appeared on my local machine, even if I had everything printed out (debug mode in the logger), but this is probably not related as stdout can't be turned off I assume.

**Comment by mstimberg** [comment]
Um, it disappeared with `poll_intervall=0.01`? Actually what I wanted to suggest was to reduce the number of attempts, i.e. to *increase* the polling interval :man_shrugging: Now I am even more confused...

**Comment by wilhelmbraun** [comment]
Yes, that's right, I _decreased_ the polling interval. Maybe just the previous value was for some reason not good. As I said, it seems to be platform-dependent.

**Comment by mstimberg** [comment]
I'm not sure what to do about this from Brian's side then. I'd still like to reproduce your original problem, since for me it does not make sense that it goes away with a smaller polling interval and we cannot be sure that other users will not have the same problem at some point. To me, the worst thing that should happen with longer polling is that things take a bit longer, in this case on the order of 1s for 20 processes, not a complete deadlock (or extreme slowdown) as you were seeing.

Would you be able to run a minimal example with the polling interval where it blocks and upload the full debug output somewhere? And ideally also the same but with the smaller polling interval?

Another thought: do you know what file system is used on the cluster?

**Comment by wilhelmbraun** [comment]
> Would you be able to run a minimal example with the polling interval where it blocks and upload the full debug output somewhere? And ideally also the same but with the smaller polling interval?

Sure, I'll let you know once it's done.

> Another thought: do you know what file system is used on the cluster?

We use nfs4.

**Comment by mstimberg** [comment]
I think the NFS filesystem is the problem. Here's a quote from an [IBM Knowledge center page](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/performance/misuses_nfs_perf.html):
> Another type of application that should not be run across NFS file systems is an application that does hundreds of lockf() or flock() calls per second. On an NFS file system, all the lockf() or flock() calls (and other file locking calls) must go through the rpc.lockd daemon. This can severely degrade system performance because the lock daemon may not be able to handle thousands of lock requests per second.
> Regardless of the client and server performance capacity, all operations involving NFS file locking will probably seem unreasonably slow. There are several technical reasons for this, but they are all driven by the fact that if a file is being locked, special considerations must be taken to ensure that the file is synchronously handled on both the read and write sides. This means there can be no caching of any file data at the client, including file attributes. All file operations go to a fully synchronous mode with no caching.

So, I'm tending towards simply marking this as a "known issue". My recommendation would be to use a separate cache directory for each process and then disable the file locking. E.g. by using something like this inside each process:
```Python
import os
cache_dir = os.path.expanduser(f'~/.cython/brian-pid-{os.getpid()}')
prefs.codegen.runtime.cython.cache_dir = cache_dir
prefs.codegen.runtime.cython.multiprocess_safe = False
```

**Comment by wilhelmbraun** [comment]
Thanks! This is really good to know, particularly in light of the problem persisting when changing `poll_interval`. It was impossible to predict when processes would start and run and when they would just go to sleep. It also explains why on my local machine, which uses ext4 filesystem, this issue never appeared.

> Would you be able to run a minimal example with the polling interval where it blocks and upload the full debug output somewhere? And ideally also the same but with the smaller polling interval?

I guess this is not necessary anymore then? What I observed when processes went to sleep is many instances of 'Lock 123 not acquired', and this happens ad infinitum.

**Comment by mstimberg** [comment]
> I guess this is not necessary anymore then?

No, I think I'll simply explain it on our known issues page in the documentation. The above linked page is quite clear about `flock` not being a good idea on NFS (the page title is "NFS misuses"...), and I do not see any way to deal with this from within Brian.
