### ISSUE TITLE
Inaccurate Output

### ISSUE THREAD

**Issue by LovelyBuggies** [brian-team/brian2#1158]
My work doesn't get the expected result when I am using brian2 on jupyter notebooks.

> ```python
> 1000*namp
> ```
> 
> 1.0000000000000002 𝜇A
> 
> 
> 
> ```python
> 10*nA*5*Mohm
> ```
> 
> 49.99999999999999mV
> 

Is that a reasonable error or something else?

**Comment by LovelyBuggies** [comment]
I got it!  Maybe the dimensions are too small/large to calculate accurately.

**Comment by mstimberg** [comment]
> I got it! Maybe the dimensions are too small/large to calculate accurately.

This is not specific about the dimensions in Brian actually, but due to the internal use of floating point numbers (see the [Python documentation](https://docs.python.org/3.7/tutorial/floatingpoint.html)). You'll get the same behaviour with plain numbers:
```pycon
>>> 1000*1e-9
1.0000000000000002e-06
>>> 10*1e-9*5*1e6
0.049999999999999996
```
