### ISSUE TITLE
Improve report function in C++ standalone mode

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#1162]
[Note that this issue is "reserved" for prospective GSoC students and probably there will be multiple pull requests open at the same time. No pull request will be merged before the end of the application period.]

When you use `report='text'` with a run (see the [documentation on progress reports](https://brian2.readthedocs.io/en/stable/user/running.html#progress-reporting) and [custom reports](https://brian2.readthedocs.io/en/stable/advanced/scheduling.html#id1)), you get a standard progress report that tells you how much of the simulation has been already done, how much time was spent, and an estimate of the remaining time. In runtime mode, the simulated and estimated time are formatted in hours/minutes/seconds for readability:
```
18.2041 s (1%) simulated in 1m 0s, estimated 53m 56s remaining.
```
In standalone mode, the display simply shows the times in seconds:
```
37.4416 s (3%) simulated in 70 s, estimated 1800 s remaining.
```

**It would be nice to be consistent here and show the time nicely formatted in standalone mode as well.**

*Bonus* improvements:

* the [documentation](https://brian2.readthedocs.io/en/stable/advanced/scheduling.html#custom-progress-reporting) currently does not have any interesting example for a custom progress report function in C++ standalone. It would be nice to add one, e.g. one that writes the progress to a file or one that displays a simple text-based progress bar on the terminal.
* we might want to implement some simple(!) approach to improve the estimates of the remaining time (this would also apply to runtime mode). See e.g. https://stackoverflow.com/questions/933242/smart-progress-bar-eta-computation for some pointers.

**Comment by rahuliitg** [comment]
When I'm clicking on the "Edit on Github" link in the documentation page, I'm getting a 404 error. @mstimberg can you please guide me about how to edit the documentation in this case.

**Comment by rahuliitg** [comment]
Hi, @mstimberg I am getting initial checks failed because I'm using the std::string in my solution. Should I include corresponding libraries while generating coder in cpp or try out a solution using char*. The latter solution makes code cumbersome.

**Comment by mstimberg** [comment]
> When I'm clicking on the "Edit on Github" link in the documentation page, I'm getting a 404 error. @mstimberg can you please guide me about how to edit the documentation in this case.

The documentation is in the `docs_sphinx` folder (also see our [developer docs](https://brian2.readthedocs.io/en/stable/developer/guidelines/documentation.html) on this topic). The "Edit on Github" links are not always working unfortunately, they should work if you switch the documentation to the "latest" version (lower left corner), e.g. use https://brian2.readthedocs.io/en/latest/user/running.html#progress-reporting .

**Comment by mstimberg** [comment]
> Hi, @mstimberg I am getting initial checks failed because I'm using the std::string in my solution. Should I include corresponding libraries while generating code in cpp or try out a solution using char*.

It should work if you add an `#include` statement to the template where the report function is used (`network.cpp`).

**Comment by mstimberg** [comment]
> It should work if you add an `#include` statement to the template where the report function is used (`network.cpp`).

Apologies (you probably noticed already): the function is called in `network.cpp`, but it is defined in `main.cpp`, so that's where the include has to go.

**Comment by rahuliitg** [comment]
<img width="673" alt="Screenshot 2020-03-12 at 1 06 50 AM" src="https://user-images.githubusercontent.com/25398437/76456949-e6e71100-63fd-11ea-9193-17c94568c064.png">
@mstimberg  Is this kind of progress bar also accepted ??

**Comment by rahuliitg** [comment]
Hi @mstimberg I'm thinking of using linear regression to approximate the remaining time (http://code.activestate.com/recipes/578914-simple-linear-regression-with-pure-python/)
