### ISSUE TITLE
Event not defined

### ISSUE THREAD

**Issue by LovelyBuggies** [brian-team/brian2#1166]
> ```python
> from brian2 import *
> 
> G = NeuronGroup(10, 'dv/dt = -v/tau : volt')
> S = Synapses(G, G, model='w:1', on_pre='v+=w')
> S.connect('i!=j')
> mon = SpikeMonitor(G)
> 
> run(10*ms)  # will include G, S, mon
> ```

At [Running a Simulation / Networks](https://brian2.readthedocs.io/en/stable/user/running.html#networks), the even seems not defined, causing a "Value Error: Source group does not define an event 'spike'."

I added `threshold='v>1', reset='v = 0', method='exact'` to the source group, and it generates error: "KeyError: 'The identifier "tau" could not be resolved.'"

**Comment by mstimberg** [comment]
Thanks for the report. The code examples on that page are not necessarily meant to be standalone code that can be run as it is (more obvious in the later examples which contain "`...`"), but not having a threshold/reset here is really inconsistent. Not sure whether it is worth defining a `tau` variable, maybe in the interest of brevity it would be better to just replace it in the equations by something like `10*ms`.
