### ISSUE TITLE
Adaptive threshold

### ISSUE THREAD

**Issue by hhamin** [brian-team/brian2#1168]
Hello everybody,
I want help in writing the equation part in code using the Spike Response Model (SRM) and adaptive threshold.
The threshold level is inversely proportional to the interspike interval between the current and the previous spike time, i.e., 1/(t_i - t_(i-1)).
Thanks

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [support mailing list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com), we try to keep the github issues for bugs and feature requests.]

You can use `t` to refer to the current time, and `lastspike` for the time of the last spike, so `threshold='1/(t-lastspike)'` should do what you want I think.

**Comment by hhamin** [comment]
thanks, I will forward my question there. whilst, I know the eqs. but the problem is in how to pass the spike times to it.

**Comment by mstimberg** [comment]
I don't quite understand what you mean. What do you mean by "spike times"? If I understood your orginal question correctly,you only need the distance between the current time and the time of the last spike (i.e. `t` and `lastspike`) to define your adaptive threshold.

**Comment by mstimberg** [comment]
I saw that you moved the question to the mailing list. I'm closing this issue and continue the discussion there.
