### ISSUE TITLE
On the ubiquity of `import *` in brian2 code?

### ISSUE THREAD

**Issue by cortical-iv** [brian-team/brian2#1180]
This is a friendly "issue". I am new to brian2, and reading over the papers, tutorials, etc.. As a Python developer, my instant reaction when I see `import *` is abject horror :) . I am curious why this is still so common in brian2 code/tutorials/even recent (2019) papers? It seems to be a pattern, while in Python it is explicitly an anti-pattern. 

When I searched the issues pile, I found this issue:
https://github.com/brian-team/brian2/issues/167

Therein, not only is it mentioned as legit, but also noticed that **pylab** is discussesd matter-of-factly.  I double gasped (look at the first few lines of pylab it is a horror show, and its use is actively discouraged in its own documentation, partly because it includes things like `from numpy import *` -- it is a relic of the days when Python suffered from Matlab-envy). 

Again, this is a friendly poke/question I know the code _works_ and it is seems like a great package. It just doesn't feel much like modern Python the way it is being used/taught, so I'm just curious if this is something people are OK with or is it something folks are moving away from?

**Comment by thesamovar** [comment]
You can import ``from brian2.only import ...`` to avoid ``*`` imports. We don't do this for the tutorials because there are a lot of non-expert programmers using Brian who come from Matlab and we don't want to put them off. Read more in the docs here: https://brian2.readthedocs.io/en/stable/user/import.html

**Comment by cortical-iv** [comment]
Thanks for that I hadn't found that bit of the docs.
