### ISSUE TITLE
repeated standalone runs crash

### ISSUE THREAD

**Issue by fpbattaglia** [brian-team/brian2#1189]
I found a potential issue with repeated standalone runs. This has been tested on macOS Catalina and with Brian 2.2.1 (conda package, python 3.6) and 2.3.0.2 (from pip, python 3.8). 

A minimal version of the code reproducing the bug (the actual code is way more complex) is attached here. 

In essence, when the simulation is run a second time in the same script, it fails with error 
```
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /var/folders/_n/ml20bf7n0_g3sz165pd3nrjm0000gn/T/brian_debug_1uynejn5.log  Additionally, you can also include a copy of the script that was run, available at: /var/folders/_n/ml20bf7n0_g3sz165pd3nrjm0000gn/T/brian_script_m_84dmg4.py You can also include a copy of the redirected std stream outputs, available at /var/folders/_n/ml20bf7n0_g3sz165pd3nrjm0000gn/T/brian_stdout_d2yd1ugv.log and /var/folders/_n/ml20bf7n0_g3sz165pd3nrjm0000gn/T/brian_stderr_xkxqltw0.log Thanks! [brian2]
Traceback (most recent call last):
  File "/Users/fpbatta/src/assembly_sequences/scripts/run_simulation_simple.py", line 69, in <module>
    nn1 = network_sim()
  File "/Users/fpbatta/src/assembly_sequences/scripts/run_simulation_simple.py", line 59, in network_sim
    bb.get_device().build(directory='PETH_standalone', compile=True, run=True, debug=False)
  File "/Users/fpbatta/.conda/envs/brian23/lib/python3.8/site-packages/brian2/devices/cpp_standalone/device.py", line 1265, in build
    self.generate_objects_source(self.writer, self.arange_arrays,
  File "/Users/fpbatta/.conda/envs/brian23/lib/python3.8/site-packages/brian2/devices/cpp_standalone/device.py", line 633, in generate_objects_source
    arr_tmp = self.code_object_class().templater.objects(
  File "/Users/fpbatta/.conda/envs/brian23/lib/python3.8/site-packages/brian2/codegen/templates.py", line 210, in __call__
    return MultiTemplate(module)
  File "/Users/fpbatta/.conda/envs/brian23/lib/python3.8/site-packages/brian2/codegen/templates.py", line 226, in __init__
    s = autoindent_postfilter(str(f()))
  File "/Users/fpbatta/.conda/envs/brian23/lib/python3.8/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/fpbatta/.conda/envs/brian23/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/Users/fpbatta/.conda/envs/brian23/lib/python3.8/site-packages/brian2/devices/cpp_standalone/templates/objects.cpp", line 122, in macro
    if(f{{name}}.is_open())
  File "/Users/fpbatta/.conda/envs/brian23/lib/python3.8/site-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: dict object has no element <DynamicArrayVariable(dimensions=Dimension(),  dtype=int32, scalar=False, constant=True, read_only=True)>
 ```
Note that I do all the 
device.reinit()
and activate() as explained in the documentation. Also note that the network is completely rebuilt after device reinitialization 

After some debugging, it seems that the problem has to do that device.reinit() (or seemingly none of the other initialization functions) does not reinitialize Brian's object tracker system. Therefore, when the simulation is run a second time, and after device reinitialization, a "ghost" of the previous simulation is reintroduced in bb.device.networks by CPPStandaloneDevice.find_synapses(). Then, device.build() crashes while parsing that ghost. 
I could solve the issue by resetting the object tracker like this 
bb.core.tracking.InstanceFollower.instance_sets = defaultdict(bb.core.tracking.InstanceTrackerSet)
before rebuilding the network a second time. But of course this is a dirty hack and maybe something like this should be included eg in bb.restore_initial_state() ? 
The issue is also present when running simulations in parallel under Jupyter and ipyparallel and it required restarting the ipyparallel cluster before being able to run the simulation again. 
[run_simulation_simple.zip](https://github.com/brian-team/brian2/files/4688232/run_simulation_simple.zip)

**Comment by mstimberg** [comment]
I looked into this a bit and I agree that the object tracker system is part of the problem here. By the way, this also means that in your example, a `del nn` before the second network run should get rid of the problem.

Your proposed solution would fix it, but I am somewhat hesitant to manually clear the collected objects. I think there's a somewhat larger issue here, the fact that it tries to collect *all* networks and synapses, regardless of whether they are actually used in the simulation. I don't think there's a good reason for it, and it might also introduce problems in situations where you do not run multiple simulations. I'll see whether this is easy to fix.

All that said, there is major room for improvement here in general... When we originally designed standalone mode, we did not have multiple runs (in the sense of your script) in mind and it clearly shows...

**Comment by fpbattaglia** [comment]
Indeed, deleting the network object also works. I previously tried to delete a bigger “container” object (as said, the original code was more complicated), of which the network object was a member, and that somehow didn’t work…


It would be nice to document that, indeed, the standalone device seems almost ready to work with repeated simulations and this helps with a number of workflows (eg parameter space exploration in a multi-core machine, etc.) and the performance gain is too nice to ignore.

Thanks a lot

Francesco
