### ISSUE TITLE
event-driven should be automatic for linear synaptic equations?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#119]
We could have a ``timestep-driven`` flag if users want to insist on not having event-driven updates, but the default is to use the most sensible one?

**Comment by thesamovar** [comment]
New option: we force users to specify event-driven or timestep-driven (maybe clock-driven). Like this we don't have to guess, and it seems that both event-driven and timestep-driven are options that users would expect to be true, but they can't both be true. @romainbrette - any thoughts?

**Comment by mstimberg** [comment]
Some feedback on this: raising an error was judged to be too drastic, instead raise a warning if an equation does not have a flag, stating that it will be simulated as clock-driven which is slow and possible not what the user wanted/needed. The user can easily get rid of the warning by explicitly specifying `(clock-driven)`. I'd be happy with this solution, it also has the advantage of being fully backwards-compatible.

**Comment by thesamovar** [comment]
OK!
