### ISSUE TITLE
Failed import of module

### ISSUE THREAD

**Issue by mdepitta** [brian-team/brian2#1191]
As of May 31, 2020; 14:40pm (GMT+1) import `brian2modelfitting` as installed by `pip` fails:

    import brain2modelfitting
    ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please 
    report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, 
    or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file 
    with debug information in your report: /tmp/brian_debug_v3tpmde8.log  Thanks! [brian2]
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'brain2modelfitting'
    >>> import brian2modelfitting
    ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please 
    report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, 
    or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file 
    with debug information in your report: /tmp/brian_debug_v3tpmde8.log  Thanks! [brian2]
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python3.6/dist-packages/brian2modelfitting/__init__.py", line 8, in <module>
    from .fitter import *
    File "/usr/local/lib/python3.6/dist-packages/brian2modelfitting/fitter.py", line 12, in <module>
    from .optimizer import Optimizer
    File "/usr/local/lib/python3.6/dist-packages/brian2modelfitting/optimizer.py", line 8, in <module>
    from nevergrad import instrumentation as inst
    ImportError: cannot import name 'instrumentation'

**Comment by mstimberg** [comment]
Hi @mdepitta . Please report issues with `brian2modelfitting` in [its repository](https://github.com/brian-team/brian2modelfitting/issues). In this case, this is a known issue (see brian-team/brian2modelfitting#35) – recent `nevergrad` versions break backwards compatibilty, so you'll have to use `nevergrad` 0.3.0 for now.
