### ISSUE TITLE
can't import brian2 in anaconda3

### ISSUE THREAD

**Issue by cnjackhu** [brian-team/brian2#1204]
I create a new environment for Brian 2 in anaconda. And then open spyder in the new environment from the anaconda-Navigator to run the python file. But when I run `from brian2 import *`. It report ModuleNotFoundError: No module named 'brian2'. How to solve? My installation for brian 2 is : `conda install -c conda-forge brian2`

**Comment by Vigneswaran-Chandrasekaran** [comment]
Hi, did you check whether you're using the correct environment where `brian2` is installed?

**Comment by cnjackhu** [comment]
Yes, I installed, I check this in the environment I use

**Comment by mstimberg** [comment]
I agree with @Vigneswaran-Chandrasekaran that this is most likely an environment configuration problem. I'd first double check whether `brian2` is installed in the correct environment (e.g. in the Anaconda Navigator). Then, make sure that spyder is actually using that environment. E.g. you can add
```python
import sys
print(sys.prefix)
```
in the same place where your import failed, and check whether the path corresponds to your environment.

**Comment by cnjackhu** [comment]
@mstimberg @Vigneswaran-Chandrasekaran  Thank you so much! It is exactly this problem. 
@mstimberg Happy French National Days!
