### ISSUE TITLE
Unable to set object parameters in network instance

### ISSUE THREAD

**Issue by neurologic** [brian-team/brian2#1208]
I have searched and scoured the tutorials and documentation as much as I could on this question before asking for help here, so apologies if I missed something obvious. I just can't figure out what I am doing wrong to not be able to accomplish the behavior that I want and hope to get some help.

I am using the Network class to collect 1) a neuron group instance 2) several spike generator group instances and 3) several synapses instances. 
I need to change the spike times in one of the spike generator group objects. Ideally I would like to pass the Network object into a function and then use that function to change the spike times based on the np.array of spike times that I provide to the function.
However, I cannot get the spike times of a spike generator group object to change within a function nor within a loop at the same level as the network object creation.
The workflow is:
    0. Initiate N,G,and S and connect the synapses (in G, both the spike times and the number of active inputs needs to change in subsequent calls to simulate the network... initializing G with the maximum potnetial number of indices it will encounter in future runs seems to enable that to work)  
    1.``` net = Network(N,G,S)```
    2. ```G.set_spikes(new spike times and indices)```
    3. ```net.run()```
I check ```G._spike_time``` after ```.set_spikes``` and see that the spike times have been successfully altered as I specified, however the result of ```net.run()``` uses the old set of spike times rather than the updated spike times. I also tried to use the following syntax to set the spike times of the object in the network directly: ```net.objects[[s.name for s in net.objects].index(Gname)]._set_spikes(new times and indices)``` where 'Gname is the name given to the spike generator group object upon creation.

 I can only get the spike times of the spike generator group object to change AND be used in the simulator run when everything is within the same level (no function calls to modularize the process) and when magic is implemented by ```store()``` ```restore()``` and  ```run()``` , etc. I would like to be able to do the same thing using the Network object version of simulation implementation (and be able to pass the Network object to different functions that do different kinds of simulations on my network). 

Let me know what I am missing/misunderstanding.
Thanks for your help!

-Krista

**Comment by neurologic** [comment]
I accidentally tried one more thing and I think it worked.
It seems like I can manipulate the object within the network by using the following syntax:
```net[Gname].set_spikes(new indices and times)```
which is what I was trying to do with:
```net.objects[[s.name for s in net.objects].index(Gname)]._set_spikes(new times and indices)```

**Comment by mstimberg** [comment]
`net[name]` is indeed the recommended way to access an object in a `Network` object. Can we close this issue or is there anything that is still not working for you?

**Comment by neurologic** [comment]
Thank you. Yes, this can be closed. It is working for me.
