### ISSUE TITLE
Trying to understand the order of the parameters gmax in STDP simulation

### ISSUE THREAD

**Issue by hockman1** [brian-team/brian2#1209]
I am trying to replicate the example in https://brian2.readthedocs.io/en/stable/examples/synapses.STDP.html

I have conducted experiments and fitted a STDP function to the data points based on tpre-tpost. Here comes the problem:

For instance I have A+ = 107.84 % and A- = -45.36 % (It is in percentage). So in the following code, from the example on Brian,

------------------------------------------------------------------------------------------------------------------------------------------
from brian2 import *
start_scope()

N = 100  # Original N is 1000
taum = 64*ms
taupre = 127*ms
taupost = taupre
Ee = 0*mV
vt = -0.5*mV
vr = -0.5*mV
El = -0*mV
taue = 32*ms
F = 15*Hz   # Original F is 15
gmax = 140e-6 # Maximum conductance
dApre = 1.0784
dApost = -0.4536
dApost *= gmax
dApre *= gmax

eqs_neurons = '''
dv/dt = (ge * (Ee-vr) + El - v) / taum : volt
dge/dt = -ge / taue : 1
'''

input = PoissonGroup(N, rates=F)
neurons = NeuronGroup(1, eqs_neurons, threshold='v>vt', reset='v = vr',
                      method='exact')
S = Synapses(input, neurons,
             '''w : 1
                dApre/dt = -Apre / taupre : 1 (event-driven)
                dApost/dt = -Apost / taupost : 1 (event-driven)''',
             on_pre='''ge += w
                    Apre += dApre
                    w = clip(w + Apost, 0, gmax)''',
             on_post='''Apost += dApost
                     w = clip(w + Apre, 0, gmax)''',
             )
S.connect()
S.w = 'rand() * gmax'
#print(S.w)
mon = StateMonitor(S, 'w', record=[0, 1])
###############################
M = StateMonitor(neurons,'v',record=True) # Monitor the potential of the neuron
###############################
s_mon = SpikeMonitor(input)

run(100*second, report='text') # Original 100 second

subplot(311)
plot(S.w / gmax, '.k')
ylabel('Weight / gmax')
xlabel('Synapse index')
subplot(312)
hist(S.w / gmax, 20)
xlabel('Weight / gmax')
subplot(313)
plot(mon.t/second, mon.w.T/gmax)
xlabel('Time (s)')
ylabel('Weight / gmax')
tight_layout()
show()

#print(S.w)

----------------------------------------------------------------------------------------------------------------------------------------

1. Is my way of setting dApre and dApost correct? Should they be  (107.84 , -45.36 % ) or (1.0784, -0.4536)? Secondly, what should the value of gmax be in this case?
2. If I were to use 0.01, then it might not make sense since my dApre and dApost are very big values and the simulation will drive all the conductances or weights to the max value?
3. How should I initialise the 'S.w' parts if I want the conductances to be of original values (20 microS to 140 microS)? It seems like randomly initialising them between 0 to 1 wont make sense in this case??
4. How about if my STDP  taupre and taupost is of the order microsecond , different from the conventional millisecond change?
How big should I set the membrane time constant in this case?

 I am quite confused by the parameters used in the example? I hope that someone can help me. Many Many Thanks!

**Comment by mstimberg** [comment]
We try to only use github issues for bugs/feature requests, not for general questions. In general the mailing list is a better place for such questions, but as I said in [my response there](https://groups.google.com/g/briansupport/c/-SStP5nnPC4/m/dB1edixXBQAJ), you will likely only get answers to questions about the implementation ("how can I do X with Brian?").
