### ISSUE TITLE
TimedArray with wrong argument number in Synapses connect condition fails ungraciously

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#1218]
I was just testing if `TimedArray` can also be used in a Synapse `connect` condition (which runs on the host for brian2CUDA). And it seems that is possible. But while a `TimedArray` in a `NeuronGroup` fails with a useful error message when the function is called with two few or two many arguments, this does not happen in the Synapse connect condition. Just took some example from the tests and adapted it below by a Synapse. This runs without error.
 
```python
from brian2 import *
set_device('cpp_standalone')

ta2d = TimedArray(np.arange(12).reshape(4, 3), dt=0.1*ms)
G = NeuronGroup(3, '''x : 1
                      value = ta2d(t, i) + 1: 1''',
                      dt=0.1*ms, threshold='True')
S = Synapses(G, G, on_pre='x += 1')
S.connect('ta2d(t, 2) > 3')
mon = StateMonitor(G, 'value', record=True, dt=0.1*ms)
run(0.5*ms)
```

If I now change the `NeuronGroup` equation to `value = ta2d(t) + 1: 1` (only one argument for 2d function), I get this nice error:
```python
SyntaxError: Function ta2d was called with 1 parameters, needs 2.
```

But if I change the Synapse connect condition to `ta2d(t) > 3`, I don't. Instead it fails ungraciously during the compilation with:
```cpp
|| code_objects/synapses_synapses_create_generator_codeobject.cpp: In function ‘void _run_synapses_synapses_create_generator_codeobject()’:
|| code_objects/synapses_synapses_create_generator_codeobject.cpp:136:50: error: too few arguments to function ‘double {anonymous}::_timedarray(double, int)’
||   136 |     const char _lio_create_cond_1 = _timedarray(t) > 3;
||       |                                                  ^
|| code_objects/synapses_synapses_create_generator_codeobject.cpp:20:23: note: declared here
||    20 |  static inline double _timedarray(const double t, const int i)
||       |                       ^~~~~~~~~~~
|| make: *** [makefile:31: code_objects/synapses_synapses_create_generator_codeobject.o] Error 1
|| make: *** Waiting for unfinished jobs....
```

Not sure if it makes sense to have `TimedArray` in a codeobject that does not run on a clock? But if it's possible, I guess the error should be shown there as well :) Or not allow it at all?

**Comment by mstimberg** [comment]
Good catch! It is true that using `TimedArray` there is unusual, but I could imagine a situation where you refer to the starting value of a `TimedArray` in the `connect` call. It turns out that there is actually a bigger issue here, the `connect` condition was not checked for correctness at all. For example, you can write `S.connect('2*i')` or `S.connect('i > 3*mV')`, and the same goes for `p` (e.g. currently `S.connect(p='3*mV')` does not raise an error). I've fixed this in a branch and will open a PR soon.
