### ISSUE TITLE
Remove 32bit support

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#1232]
I wonder whether it isn't time that we officially remove the 32bit OS support? In the past, this has often been tricky to get right on Windows and > 1h40 of our test suite (which takes way too long even without it) is concerned with testing the 32bit behaviour. I had a look on our download statistics, and there hasn't been a download from a 32bit OS in the last month on pypi (for conda, we are only providing 64bit packages in the first place).

Just to be clear, I'm not talking about removing support for setting the standard `dtype` to 32bit (which can still be useful for `brian2genn`). This is just about the cross-compiling support for Linux and running the tests on 32bit Windows VMs.

PS: Looking at the download statistics I also noted that Linux become our dominant platform: ~50% of our conda downloads and almost 90%(!) of our pip downloads are now on Linux :penguin: Wouldn't have thought!

**Comment by thesamovar** [comment]
I'm in favour. We'd still allow it to run on 32 bit, just not provide precompiled versions and not test it, right?

**Comment by mstimberg** [comment]
We haven't been providing compiled 32bit versions for a while, so yes it would be basically about testing it. I'd also remove the support for cross-compilation to 32bit on a 64bit Linux system, since I don't think anyone ever used this outside of us building binaries for 32bit back in the days.

**Comment by thesamovar** [comment]
I guess there's a chance we're missing some sort of relevant use case, but I can't think what it could be. Even raspberry pi is 64 bit.

**Comment by mstimberg** [comment]
If Brian was about controlling some hardware in a lab computer for example, I could still see a use for 32bit support because such machines are never updated. But I don't see much of a danger here. If I extend the query to the last 3 months (I can't look much further back without exceeding my free quota), I find that 2 out of 4327 downloads were from a 32bit system. For reference, that is less than the downloads for ipad8/11 (3 downloads) and the ARM 64bit architecture (4 downloads) – no idea whether those actually work!

**Comment by thesamovar** [comment]
Go for it!
