### ISSUE TITLE
Cache certain computations using joblib

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#124]
Some of the code generation stuff can end up actually taking a while. Solution: cache it!

**Comment by thesamovar** [comment]
Could also use memoize (in Python 3 there is ``functools.lru_cache``). See also the way sympy uses it: https://github.com/sympy/sympy/blob/master/sympy/core/cache.py

**Comment by mstimberg** [comment]
I think with all the improvements to the preparation time merged recently, maybe we should postpone this to post-2.0? A quick and dirty solution might do more harm then good...

**Comment by thesamovar** [comment]
Yep!
