### ISSUE TITLE
Example for homeostatic plasticity with firing rate

### ISSUE THREAD

**Issue by schmitts** [brian-team/brian2#1241]
Hi!

I'm looking for an example for homeostatic plasticity to stabilize firing rates. Is there a notion for firing rates available that can be used to formulate a weight update rule?

Thanks,

Sebastian

**Comment by mstimberg** [comment]
Hi. Just as a general remark: our forum on https://brian.discourse.group would be a better place to ask this kind of question.

In spiking networks, there is no direct firing rate variable that is available. What you'd typically do is to use a variable that increases with each spike (via the `reset` statement) and decays over time. Another option is to low-pass filter the membrane potential and to use this as a proxy for the firing rate (see e.g. the [Clopath et al. (2010) example](https://brian2.readthedocs.io/en/stable/examples/frompapers.Clopath_et_al_2010_homeostasis.html)).

**Comment by schmitts** [comment]
Thanks. Will continue on discourse.
