### ISSUE TITLE
how to acess log file from Brian2 simulator which is installed anaconda environment?

### ISSUE THREAD

**Issue by ramapati166** [brian-team/brian2#1243]
when usually we do simulation of spiking neural network using Brian 2 simulator  and spikes are generated then if I want to access the log file to get the tracing information of neurons,means which neuron generated how many spikes or spike times?I have accessed this "/tmp/brian_debug_qcnvs7wb.log" ,but not getting any information related to neuron of number of spike..If anyone can help I will highly obliged to you.Thanks in advance.

**Comment by mstimberg** [comment]
Hi @ramapati166. The information about spikes is not stored to a log file, but they can be accessed from the `SpikeMonitor` object (that you have to create to record them). Please have a look at the documentation: https://brian2.readthedocs.io/en/stable/user/recording.html#recording-spikes

**Comment by ramapati166** [comment]
Respected sir
I am a PhD student from National Institute of Technology ,Durgapur
,India.Sir I have gone through a journal paper published in Elsevier with
the title
" *Liquid State Machine Applications Mapping for NoC-Based Neuromorphic
Platform*s",the authors  have used the *Brian2 Simulator *and also given
your Research paper *"Brian 2, an intuitive and efficient neural simulator'*'
as a reference and in this paper the authors claimed that the "*The
behavior of spike can be analyzed from the log file of Brian2 *" and *after
generating the tracing file from log file of Brian2 simulator they applying
*it to Booksim 2 simulator.Hence I have raises the question as I could not
able to find it.Sir I have one doubt ,say if I want to generate a
feedforward multilayer spiking neural network(*say, 20: 40 : 2*) by using*
Brian2 simulator* is it possible? If yes then If you can give some
reference paper or supporting link or documents ,I will be highly obliged
to you sir.
Thank you,
With regards
Ramapati Patra
NIT Durgapur,
India

**Comment by mstimberg** [comment]
Hi again [just in case you are not aware: you replied on GitHub, not via personal mail].
I don't know what the authors did in their paper, they probably stored the files returned by Brian to disk before continuing to use them with another software. If you need more details about their approach, you might have to ask them. In general, please ask general questions about Brian at https://brian.discourse.group – we try to keep GitHub issues for bug reports and feature requests.

You can definitely create a feedforward multilayer spiking network, but please be aware that Brian is in itself not a "machine learning tool". Its strength lies in the flexibility to define arbitrary neural/synaptic models with equations. If you don't need that flexibility and just want to create/train/test a network with minimal coding, it might not be the right tool for you. *If* you are interested in using it, I suggest you go through our [tutorials](https://brian2.readthedocs.io/en/stable/resources/tutorials/index.html).

**Comment by ramapati166** [comment]
Ok sir.Thank you very much.
