### ISSUE TITLE
Circle (Ring shaped) neuronal layer in Brian2 [STDP synapse].

### ISSUE THREAD

**Issue by IrisHydi** [brian-team/brian2#1247]
Hello,

Is it possible to create a ring shaped neuron layer in Brian2? I would like to create a Stdp synapse connection between two ring shaped layers.

Thank you in advance!

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

You can certainly have ring-based connectivity in Brian 2. How to do this concretely depends on the details of your desired connectivity scheme. The simplest is to connect neurons based on their index, e.g. each cell to its neighbours and then take care of "wrapping" around for the ring structure with the modulo operator (we have an example like this in our [2014 paper](https://www.frontiersin.org/articles/10.3389/fninf.2014.00006)). Another option is to use Brian's [generator syntax](https://brian2.readthedocs.io/en/stable/user/synapses.html#creating-synapses-with-the-generator-syntax), e.g.
```Python
synapses.connect(j='(i + k) % N_post for k in range(-1, 1, 2)')
```
I'd recommend having a look at the [2nd Brian tutorial](https://brian2.readthedocs.io/en/stable/resources/tutorials/2-intro-to-brian-synapses.html) for a general introduction to synaptic connection patterns.

There are other ways to do things (e.g. each neuron could have a variable denoting its angular position on the ring, and you can express your connectivity as a function of that position), but we'd need some more details to help you with that.
