### ISSUE TITLE
Improvement in PoissonInput documentation

### ISSUE THREAD

**Issue by johnpi** [brian-team/brian2#1255]
It might be useful to add in the documentation of the PoissonInput class something like "Each of the N inputs is connected to all neurons of the target Group but each neuron receives independent realizations of Poisson spike trains." Currently, the text in the documentation of this class does not clarify if it uses an all-to-all connectivity or not and how the value of N inputs affects the target neurons. The suggested change might help users.

**Comment by mstimberg** [comment]
Sorry for the late reply! Yes, I agree that it would be useful to make this clearer. Feel free to propose a pull request with a change to the documentation :smile:

For changes to the documentation, you don't have to jump through all the git hoops to do this. You can simply go to https://github.com/brian-team/brian2/edit/master/docs_sphinx/user/input.rst, click :pencil2: ("Edit this file"), make the changes and then use the option to create a pull request based on the changes.

**Comment by mstimberg** [comment]
Closed via #1272.
