### ISSUE TITLE
Constant replacements in C++ standalone can go wrong

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#1276]
As discovered by @wxie2013, the following rather trivial example leads to a compilation error:
```Python
set_device('cpp_standalone')
x = 42
G = NeuronGroup(1, 'y : 1')
G.y = 'x'
run(0*ms)
```
The reason is that we quite naively replace `x` in the code with 42 in our "this is a bit of a hack" [`freeze`](https://github.com/brian-team/brian2/blob/20e120921ab237c5a0f6ea04db766c9ca052e811/brian2/devices/cpp_standalone/device.py#L232) function. Unfortunately we use the name `x` quite often, e.g. in macro definitions like `#define _brian_pow(x, y) (pow((x), (y)))` or as the argument of functions. I think the fix is rather straightforward (short of dealing with this as part of a bigger refactoring): the constant replacement should only affect the user code, not all the support code around it.

**Comment by thesamovar** [comment]
Can't believe we never ran into this before!

**Comment by mstimberg** [comment]
That was my first reaction as well! The bug has been around since version 2.0.2.1 at least (the oldest I tested), so it's not a regression we introduced with any changes recently :grimacing:
