### ISSUE TITLE
Support for apple m1

### ISSUE THREAD

**Issue by DingkunLiu** [brian-team/brian2#1278]
When I ran brian2 on the new m1 Mac, I got the following clang error:
`clang-11: error: the clang compiler does not support '-march=native'
WARNING    Cannot use Cython, a test compilation failed: command '/Users/.../miniforge3/bin/arm64-apple-darwin20.0.0-clang' failed with exit code 1 (CompileError) [brian2.codegen.runtime.cython_rt.cython_rt.failed_compile_test]
INFO       Cannot use compiled code, falling back to the numpy code generation target. Note that this will likely be slower than using compiled code. Set the code generation to numpy manually to avoid this message:
prefs.codegen.target = "numpy" [brian2.devices.device.codegen_fallback]`

It seems that clang for the arm architecture does not have the `-march` parameter. Is it possible to fix this?

**Comment by mstimberg** [comment]
Hi. We should have recently fixed this issue in the development version of Brian, but since we don't have any M1 hardware ourselves, it is a bit tricky to test. We'd therefore be very happy if you could give us feedback whether the new version works for you. Did you install Brian via `conda-forge` or via `pip`? If it was with `conda`, please first uninstall your current version. You can then install the current development version with pip:
```
 pip install -i https://test.pypi.org/simple/ Brian2==2.4.2.post0.dev120
```

**Comment by DingkunLiu** [comment]
Thank you for the reply.   

I just installed this wheel [Brian2-2.4.2.post0.dev120-cp39-cp39-macosx_10_9_universal2.whl](https://test-files.pythonhosted.org/packages/bd/1d/acb204f83c3a7ff4de27c549d43e4d6021d40779b6957dac0fc61b57e929/Brian2-2.4.2.post0.dev120-cp39-cp39-macosx_10_9_universal2.whl#sha256=555e98fd154f9b063cc92c16752d571d4dc177e073a1f64e266b643d84bb6854), but the issue persisted. 

My system info:

```
{'platform': 'Darwin', 
'platform-release': '20.3.0', 
'architecture': 'arm64', 
'processor': 'arm', 
'ram': '16 GB'}
```

Test script:  
```from brian2 import *

n = 1000
duration = 1*second
tau = 10*ms
eqs = '''
dv/dt = (v0 - v) / tau : volt (unless refractory)
v0 : volt
'''
group = NeuronGroup(n, eqs, threshold='v > 10*mV', reset='v = 0*mV',
                    refractory=5*ms, method='exact')
group.v = 0*mV
group.v0 = '20*mV * i / (n-1)'

monitor = SpikeMonitor(group)

run(duration)
plot(group.v0/mV, monitor.count / duration)
xlabel('v0 (mV)')
ylabel('Firing rate (sp/s)')
show()
```

Output:
```
clang-11: error: the clang compiler does not support '-march=native'
WARNING    Removing unsupported flag '-march=native' from compiler flags. [brian2.codegen.cpp_prefs]
WARNING    Cannot use Cython, a test compilation failed: command 'arm64-apple-darwin20.0.0-clang++' failed: No such file or directory (LinkError) [brian2.codegen.runtime.cython_rt.cython_rt.failed_compile_test]
INFO       Cannot use compiled code, falling back to the numpy code generation target. Note that this will likely be slower than using compiled code. Set the code generation to numpy manually to avoid this message:
prefs.codegen.target = "numpy" [brian2.devices.device.codegen_fallback]
```

**Comment by mstimberg** [comment]
It did actually partially work, it removed the `-march=native` flag from the compiler flags (even though it should have swallowed the `clang-11: error...` part instead of displaying it...). It's a different error now, it fails with "No such file or directory (LinkError)". Unfortunately it is hard to see what is going wrong with only this information. Could you add the following to the beginning of your test script (after the Brian import), it should give you more output when the compilation fails:
```Python
prefs.logging.std_redirection = False
```

**Comment by DingkunLiu** [comment]
Thanks a lot, but the added line seems to make no difference.

**Comment by DingkunLiu** [comment]
Maybe I could try building it locally or running the tests to give you more feedback?

**Comment by mstimberg** [comment]
Yes, that would be the next step. Maybe before we do this one last attempt to do an ugly hack to get Cython to display some more info.
Please put the following in the beginning of your script **before the Brian import**:
```Python
import Cython.Build
_real_cythonize = Cython.Build.cythonize
def cythonize_wrapper(*args, **kwds):
    if 'quiet' in kwds:
        kwds['quiet'] = False
    _real_cythonize(*args, **kwds)
Cython.Build.cythonize = cythonize_wrapper
```
And also keep the `prefs.logging...` line.

**Comment by mstimberg** [comment]
(Actually having it after the Brian import should work as well...)

**Comment by DingkunLiu** [comment]
This time there is something 😂 : 

```
clang-11: error: the clang compiler does not support '-march=native'
WARNING    Removing unsupported flag '-march=native' from compiler flags. [brian2.codegen.cpp_prefs]
[1/1] Cythonizing /Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.pyx
WARNING    Cannot use Cython, a test compilation failed: dlopen(/Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.cpython-39-darwin.so, 2): image not found (ImportError) [brian2.codegen.runtime.cython_rt.cython_rt.failed_compile_test]
INFO       Cannot use compiled code, falling back to the numpy code generation target. Note that this will likely be slower than using compiled code. Set the code generation to numpy manually to avoid this message:
prefs.codegen.target = "numpy" [brian2.devices.device.codegen_fallback]
```

There should be a compiled `.so` file after cythonizing, and maybe this is the problem?

**Comment by mstimberg** [comment]
I think you do have a compiled `.so` file, but it fails to load due to some linking/library path issue. You are using `clang` installed via conda, right? I'm not really an expert on these things, but could you try adding the following to see whether it changes anything?
```Python
import os, sys
os.environ['DYLD_LIBRARY_PATH'] = os.path.join(sys.prefix, 'lib')
```

**Comment by DingkunLiu** [comment]
Still not working... And the error message is the same. 

I checked the cython cache dir, and I found there was only a `_cython_magic_5e4fca9e6a96b8d6722421525ceea994.lock` file but not the `.so` one.

And the clang info:

```
clang version 11.0.1
Target: arm64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Users/dingkunliu/miniforge3/bin
```

**Comment by mstimberg** [comment]
Ouch, no this is actually just a stupid mistake in my wrapper above :facepalm: The last line should be
```Python
    return _real_cythonize(*args, **kwds)
```
(instead of just `_real_cythonize(*args, **kwds)`).

Please try first without the `DYLD_LIBRARY_PATH` thing.

**Comment by DingkunLiu** [comment]
It is wired that without the `return`, it works just the same.

```
clang-11: error: the clang compiler does not support '-march=native'
WARNING    Removing unsupported flag '-march=native' from compiler flags. [brian2.codegen.cpp_prefs]
[1/1] Cythonizing /Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.pyx
WARNING    Cannot use Cython, a test compilation failed: command 'arm64-apple-darwin20.0.0-clang++' failed: No such file or directory (LinkError) [brian2.codegen.runtime.cython_rt.cython_rt.failed_compile_test]
INFO       Cannot use compiled code, falling back to the numpy code generation target. Note that this will likely be slower than using compiled code. Set the code generation to numpy manually to avoid this message:
prefs.codegen.target = "numpy" [brian2.devices.device.codegen_fallback]
```

**Comment by mstimberg** [comment]
Hmm, this is all the output you get? I hoped for a bit more... Did you try setting `DYLD_LIBRARY_PATH`?

**Comment by DingkunLiu** [comment]
Yes, that was all the output.. And yeah, I tried, but it didn't work (the error message was the same).

**Comment by mstimberg** [comment]
Ok, let's try another thing. I wonder whether standalone mode works. It compiles/executes things in a different way, so if it worked it would give us some hints. If it does not work either, it will at least be a bit more verbose in its output. Could you run e.g. this example: https://brian2.readthedocs.io/en/latest/examples/standalone.simple_case.html
But replace the `set_device('cpp_standalone')` line by:
```Python
set_device('cpp_standalone', debug=True)
```

**Comment by DingkunLiu** [comment]
The standalone mode works very well. The output is:

```
INFO       Overwriting environment variable "DYLD_LIBRARY_PATH" [brian2.devices.cpp_standalone.device.overwritten_env_var]
```

**Comment by mstimberg** [comment]
Great, progress! But this seems to indicate that it should work in principle and when setting the `DYLD_LIBRARY_PATH` which we do by default in standalone mode but which hasn't been necessary when using Cython so far.

Here's another thing to try for Cython, but please run `clear_cache('cython')` first or manually delete the cython cache directory to make sure it recompiles everything. In your script, declare:
```Python
lib_dir = os.path.join(sys.prefix, 'lib')
prefs.codegen.cpp.extra_compile_args_gcc += [f'-rpath={lib_dir}']
```

**Comment by DingkunLiu** [comment]
I found that the overwriting information was caused by my freesurfer installation. By default, the DYLD path led to `/Applications/freesurfer/7.1.1/lib/gcc/lib`

**Comment by mstimberg** [comment]
Oh, maybe could you simply try removing the `DYLD_LIBRARY_PATH` definition by freesurfer then? It might work without any other changes if it does not get redirected to the wrong library directory.

**Comment by DingkunLiu** [comment]
Very wired. I removed freesurfer related thing manually and set the `DYLD_LIBRARY_PATH` to miniforge lib. But still the same error persisted.

```
% echo $DYLD_LIBRARY_PATH
/Users/dingkunliu/miniforge3/lib/
```

```
clang-11: error: the clang compiler does not support '-march=native'
WARNING    Removing unsupported flag '-march=native' from compiler flags. [brian2.codegen.cpp_prefs]
[1/1] Cythonizing /Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.pyx
WARNING    Cannot use Cython, a test compilation failed: command 'arm64-apple-darwin20.0.0-clang++' failed: No such file or directory (LinkError) [brian2.codegen.runtime.cython_rt.cython_rt.failed_compile_test]
INFO       Cannot use compiled code, falling back to the numpy code generation target. Note that this will likely be slower than using compiled code. Set the code generation to numpy manually to avoid this message:
prefs.codegen.target = "numpy" [brian2.devices.device.codegen_fallback]
```

**Comment by mstimberg** [comment]
Just to make sure: you do have a `/Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.so` file now, right?

**Comment by DingkunLiu** [comment]
No, there weren't...

```
% ls /Users/dingkunliu/Library/Caches/cython/brian_extensions 
Users
_cython_magic_5e4fca9e6a96b8d6722421525ceea994.cpp
_cython_magic_5e4fca9e6a96b8d6722421525ceea994.lock
_cython_magic_5e4fca9e6a96b8d6722421525ceea994.pyx
```

There is still one more wired thing. There is a `Users` folder inside the cache, which had a repetitive path leading to a `.o` file:
```
% ls /Users/dingkunliu/Library/Caches/cython/brian_extensions/Users/dingkunliu/Library/Caches/cython/brian_extensions/                                                                       
_cython_magic_5e4fca9e6a96b8d6722421525ceea994.o
```

**Comment by mstimberg** [comment]
The weird path thing is normal (even though I never exactly understood why it does things this way). Here's one more thing to add to your script which will hopefully give us some useful hint:
```Python
import distutils.log
distutils.log.set_verbosity(2)
```

**Comment by DingkunLiu** [comment]
The `-rpath=` line you mentioned above triggered another error:

```
clang-11: error: unknown argument: '-rpath=/Users/dingkunliu/miniforge3/lib'
WARNING    Removing unsupported flag '-rpath=/Users/dingkunliu/miniforge3/lib' from compiler flags. [brian2.codegen.cpp_prefs]
```

Do you know how to fix this?

**Comment by DingkunLiu** [comment]
Here is the output:

```
arm64-apple-darwin20.0.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -D_FORTIFY_SOURCE=2 -isystem /Users/dingkunliu/miniforge3/include -c /var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmp85ztyg9d.cpp -o var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmp85ztyg9d.o -w
arm64-apple-darwin20.0.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -D_FORTIFY_SOURCE=2 -isystem /Users/dingkunliu/miniforge3/include -c /var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmpgtzia45h.cpp -o var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmpgtzia45h.o -O3
arm64-apple-darwin20.0.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -D_FORTIFY_SOURCE=2 -isystem /Users/dingkunliu/miniforge3/include -c /var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmpbjawv9o2.cpp -o var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmpbjawv9o2.o -ffast-math
arm64-apple-darwin20.0.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -D_FORTIFY_SOURCE=2 -isystem /Users/dingkunliu/miniforge3/include -c /var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmp7f8juolr.cpp -o var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmp7f8juolr.o -fno-finite-math-only
arm64-apple-darwin20.0.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -D_FORTIFY_SOURCE=2 -isystem /Users/dingkunliu/miniforge3/include -c /var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmpmw_n0lov.cpp -o var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmpmw_n0lov.o -march=native
clang-11: error: the clang compiler does not support '-march=native'
WARNING    Removing unsupported flag '-march=native' from compiler flags. [brian2.codegen.cpp_prefs]
arm64-apple-darwin20.0.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -D_FORTIFY_SOURCE=2 -isystem /Users/dingkunliu/miniforge3/include -c /var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmpdq_yfyb9.cpp -o var/folders/ws/30911crd7w79c19868350xfm0000gn/T/tmpdq_yfyb9.o -std=c++11
[1/1] Cythonizing /Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.pyx
building '_cython_magic_5e4fca9e6a96b8d6722421525ceea994' extension
arm64-apple-darwin20.0.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -D_FORTIFY_SOURCE=2 -isystem /Users/dingkunliu/miniforge3/include -I/Users/dingkunliu/miniforge3/lib/python3.9/site-packages/brian2/synapses -I/Users/dingkunliu/miniforge3/include/python3.9 -c /Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.cpp -o /Users/dingkunliu/Library/Caches/cython/brian_extensions/Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.o -w -O3 -ffast-math -fno-finite-math-only -std=c++11
arm64-apple-darwin20.0.0-clang++ -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/dingkunliu/miniforge3/lib -L/Users/dingkunliu/miniforge3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/dingkunliu/miniforge3/lib -L/Users/dingkunliu/miniforge3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/dingkunliu/miniforge3/lib -L/Users/dingkunliu/miniforge3/lib -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/dingkunliu/miniforge3/include -D_FORTIFY_SOURCE=2 -isystem /Users/dingkunliu/miniforge3/include -arch arm64 /Users/dingkunliu/Library/Caches/cython/brian_extensions/Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.o -o /Users/dingkunliu/Library/Caches/cython/brian_extensions/_cython_magic_5e4fca9e6a96b8d6722421525ceea994.cpython-39-darwin.so
WARNING    Cannot use Cython, a test compilation failed: command 'arm64-apple-darwin20.0.0-clang++' failed: No such file or directory (LinkError) [brian2.codegen.runtime.cython_rt.cython_rt.failed_compile_test]
INFO       Cannot use compiled code, falling back to the numpy code generation target. Note that this will likely be slower than using compiled code. Set the code generation to numpy manually to avoid this message:
prefs.codegen.target = "numpy" [brian2.devices.device.codegen_fallback]
```

**Comment by mstimberg** [comment]
Just wondering, do you have a `arm64-apple-darwin20.0.0-clang++` binary in your `.../miniforge3/bin` or only a `...clang` one?

**Comment by mstimberg** [comment]
> Seems like the missing `.so` caused the clang error.

I rather think the failure to compile leads to the missing `.so` file.


> The `-rpath=` line you mentioned above triggered another error:

Never mind that suggestion, from your debug output we can see that it already sets `rpath` in the correct way.

**Comment by DingkunLiu** [comment]
> Just wondering, do you have a `arm64-apple-darwin20.0.0-clang++` binary in your `.../miniforge3/bin` or only a `...clang` one?

Yes, there is only a `...clang` one.

**Comment by mstimberg** [comment]
Ah, then that seems to be the issue. Could you paste the output of
```bash
$ export | grep clang
$ conda list | grep clang
```

**Comment by DingkunLiu** [comment]
```
% export |grep clang
CC=arm64-apple-darwin20.0.0-clang
CC_FOR_BUILD=/Users/dingkunliu/miniforge3/bin/arm64-apple-darwin20.0.0-clang
CLANG=arm64-apple-darwin20.0.0-clang
OBJC=arm64-apple-darwin20.0.0-clang
OBJC_FOR_BUILD=/Users/dingkunliu/miniforge3/bin/arm64-apple-darwin20.0.0-clang
% conda list | grep clang
clang                     11.0.1               hce30654_1    conda-forge
clang-11                  11.0.1          default_h87665d4_1    conda-forge
clang_osx-arm64           11.0.1               h54d7cd3_1    conda-forge
clangxx                   11.0.1          default_hbe4449c_1    conda-forge
libclang-cpp11            11.0.1          default_h87665d4_1    conda-forge
```

**Comment by mstimberg** [comment]
Could you try to install the `clangxx_osx-arm64` with conda and see whether this changes anything? Please deactivate/activate the environment after installation or restart the terminal.

**Comment by DingkunLiu** [comment]
There is a `clang++` in the binary folder. I made a symbolic link for the `arm64-apple-darwin20.0.0-clang++` and now it works!

**Comment by DingkunLiu** [comment]
> Could you try to install the `clangxx_osx-arm64` with conda and see whether this changes anything? Please deactivate/activate the environment after installation or restart the terminal.

This way also works! Thank you very much!

**Comment by mstimberg** [comment]
I think installing the package just makes the symlink :) Happy to hear that it works, let us know if you run into other issues. 

Just one last question: when you initially installed Brian 2, i.e. the released version not the development version, did you install it via `pip` or via `conda`? I am asking because installing it via conda should have installed the `clangxx` package automatically, but maybe there's an issue with that.

**Comment by DingkunLiu** [comment]
From pip. it seems there hasn't been any arm version provided on conda-forge.

**Comment by mstimberg** [comment]
Right, of course, that makes sense. The next release will probably have one though given that conda-forge's infrastructure seems to be up to the task. I'll close this issue for now, thanks again for bearing with my clumsy attempts at debugging the issue ;)

**Comment by dokato** [comment]
hey @mstimberg any news on getting brian2 on conda forge for arm64?

**Comment by mstimberg** [comment]
Hi @dokato . No, we still don't have arm64 builds on conda-forge. Apparently we'd have to open a PR to trigger a bot making the necessary changes: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock If you could verify that all of Brian's dependencies have arm64 packages, please go ahead proposing that it gets added to the list!
Also note that on pypi we now have [`universal2`](https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2) binary wheels for OSX, i.e. wheels that package both arm64 and x86_64 versions: https://pypi.org/project/Brian2/

**Comment by dokato** [comment]
Thanks @mstimberg , what worked for me in the end was:
```
pip install --upgrade --pre -i https://test.pypi.org/simple/ brian2
```
following your response on some other forum. Happy to test Brian's dependencies. But you mean just to see if my pip installation work, or you want me to go through the `requirements.txt` and see if they're all on conda for arm64?

**Comment by mstimberg** [comment]
> appy to test Brian's dependencies. But you mean just to see if my pip installation work, or you want me to go through the `requirements.txt` and see if they're all on conda for arm64?

Sorry for the late reply... I meant the latter (check whether all dependencies already have arm64 builds), but I just verified this myself. All dependencies are good, I opened a PR to trigger the arm64 builds on conda-forge.
