### ISSUE TITLE
Support for Ultra-Low Power FPGAs such as the Lattice iCE40UP5K

### ISSUE THREAD

**Issue by contrebande-labs** [brian-team/brian2#1293]
Hello! [I opened a feature request for that with Nengo.](https://github.com/nengo/nengo-fpga/issues/76) and then, the [designer and manufacturer of the Upduino 3.0](https://tinyvision.ai/) board gave me a link to your project. I don't know if it's applicable to Brian, but would it be possible to have a iCE40UP5K backend to run Brian simulations on? I don't know if it makes sense even to ask that, but I saw [this which seems to implicate Brian2 with FPGAs somehow](http://beweb.ucsd.edu/courses/senior-design/projects/2016-2017/project_5/), and well, I would love to know. Thanks!

**Comment by thesamovar** [comment]
We have looked into FPGA backend but it's quite a lot of work and we have limited bandwidth, so it's not imminent I'm afraid.
