### ISSUE TITLE
Three questions in Brain2 

### ISSUE THREAD

**Issue by banffff** [brian-team/brian2#1305]
I have this Brain2 script:
stimulus = TimedArray(np.random.randn(int(run_time/defaultclock.dt)), dt=defaultclock.dt) #common noise stimulus
NeuronGroup(100, 'dv/dt = -v / 10 * ms + stimulus * amp * meter**-2: volt', threshold='v >-35*mV', reset='v=-50*mV', method='euler')
state = StateMonitor(neurons,['v'], record=True)
fire = SpikeMonitor(neurons)

(1) How to plot the timedarray "stimulus"?
(2) How to export state.v of 100 neurons into a csv or excel file?
(3) how to export fire.spike_train of 100 neurons into a  csv or excel file?

Thank you!

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

The `TimedArray` is a function of time, so you can use it to plot its values like this:
```Python
t_array = np.arange(len(stimulus.values))*defaultclock.dt
plt.plot(t_array/ms, stimulus(t_array))
```
Alternatively, you can directly access the stored values:
```Python
plt.plot(t_array/ms, stimulus.values)
```
The variables stored in `StateMonitor` and `SpikeMonitor` are numpy arrays, you can therefore use standard numpy functions to store them to disk, e.g.
```Python
np.savetxt('values.txt', state.v/mV)
```
to store the recorded voltage values in mV.
See https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html for details. If you need more fancy csv/xls support, you can create a Pandas data frame with the values and then use its [`t_csv`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html) or [`to_excel`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html) methods.
