### ISSUE TITLE
Monitoring: Divide Neurons into Winning and Losing Neurons to get subNeuronGroup Firing Rates

### ISSUE THREAD

**Issue by ojas13** [brian-team/brian2#1313]
Is it possible to divide neurons of the same NeuronGroup based on sensitivity to an input stream and then get firing rates of these subgroups when they are activated?

Example: 
Neurons 0-49 from Layer 1 are sensitive to 'X' input
Neurons 50-99 from Layer 1 are sensitive to 'O' input. 
On 'X' input, we get firing rate of neurons 0-49(winning neurons) and neurons 50-99(losing neurons) separately.

**Comment by mstimberg** [comment]
Sorry about the very late reply, but questions like this are better suited for the discussion forum at: https://brian.discourse.group

That said, please add some more details about what you want to do. Are you asking how to get the firing rate of two groups of neurons separately? For this, you can for example use [subgroups](https://brian2.readthedocs.io/en/stable/user/models.html#subgroups) and record each of them separately with a [PopulationRateMonitor](https://brian2.readthedocs.io/en/stable/user/recording.html#recording-population-rates).
