### ISSUE TITLE
Brian usage in google colab

### ISSUE THREAD

**Issue by 18sarru** [brian-team/brian2#1325]
I have been trying to use brian in google colab, Hoever i am not able to download brian , so i ytried writting the code in brian 2. However I need the hears module but brian2 hears is connected to brian's hears and i am not able to use it. How to dowload brian in python3?

**Comment by Vigneswaran-Chandrasekaran** [comment]
You can install Brian in colab using `pip`,
```
!pip install brian2
```

**Comment by 18sarru** [comment]
I want to use Brian 2 hears module which in turn uses Brian hears module
and I am not able to use it

**Comment by 18sarru** [comment]
ImportError: brian2.hears is deprecated and will be removed in a future release, please use the brian2hears package available at https://brian2hears.readthedocs.io/. If you really want to keep using it, note: brian2.hears is a bridge between Brian 2 and the version of Brian Hears from Brian 1, you need to have Brian 1 installed to use it.

this is the error i am facing

**Comment by mstimberg** [comment]
Hi. As the error message says, `brian2.hears` is deprecated, please install the `brian2hears` package instead. (`pip install brian2hears`). If you have issues using it, please report on its bug tracker: https://github.com/brian-team/brian2hears/issues
