### ISSUE TITLE
ipython notebook: figure out why the debug output appears

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#133]
On some machines, I get all of Brian's debug output when running things in the ipython notebook.

**Comment by damiendr** [comment]
I seem to have this problem again on my install:
brian2-2.0b3
ipython-3.1.0
cython-0.22

Hundreds of lines of compilation logs appear in the notebook. A workaround is to run:

```python
import logging
logger = logging.getLogger('brian2')
logger.propagate = False
```

**Comment by mstimberg** [comment]
Hmm, I cannot reproduce this problem. Are you sure that you are using brian2-2.0b3 (well, it should mention it at the start of the debug log output you are getting :) )? But I remember that at the time where I had the problem, it was somewhat difficult to reproduce, I did not get it on all of my machines.

I wonder if there's any downside to doing the equivalent of your workaround, i.e. to switch of `propagate` for the `brian2` logger when we create it.
