### ISSUE TITLE
Change in merged PR #1069 is lost in master? Or am I just not gitting it?

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#1330]
I was just updating brian2cuda with changes made in brian2 PR #1069 (in May 2019). I'm looking at [this change](https://github.com/brian-team/brian2/pull/1069/files#diff-e7238a1e7fde86d1e113a4215e35ae2a930c9805cf67c82a71c98ca109e1ff27L1216-R1216), which should have been introduced [here in commit 125e591](https://github.com/brian-team/brian2/commit/125e591c1067c2d8d1e6cc624f06c528c0d6d2a0#diff-e7238a1e7fde86d1e113a4215e35ae2a930c9805cf67c82a71c98ca109e1ff27L1216-R1216). The PR and with that the commit should be merged into brian2 master.

But [the corresponding line in current brian2 master](https://github.com/brian-team/brian2/blame/master/brian2/devices/cpp_standalone/device.py#L1225) does not include that change and GitHub's `git blame` shows that it was last modified in 2015...

And the commit 125e591 which should have modified that line [shows in `git blame`](https://github.com/brian-team/brian2/blame/master/brian2/devices/cpp_standalone/device.py#L1365), so it is not lost.

I guess this is more a git issue than a brian issue but I've been banging my head against the wall for an hour now an thought maybe someone here sees something I'm missing?

**Comment by denisalevi** [comment]
Well and the underlying brian2 question is whether it should be 

```cpp
names = [obj.name for net in self.networks for obj in net.objects]
```
as it currently is in brian2 master or should it be

```cpp
names = [obj.name for net in self.networks for obj in net.sorted_objects]
```
as the PR #1069 introduced it? I didn't follow the rather long discussion in the PR in detail.

**Comment by mstimberg** [comment]
Hmm, I think this line got indeed lost, probably when I manually had to solve merge conflicts.

In principle, I think the line should be 
```Python
names = [obj.name for net in self.networks for obj in net.sorted_objects]
```
to check *all* objects for name conflicts, not just the main objects. On the other hand, I don't see a situation where this would make a difference. It would mean that a "contained object" has a name conflict, while the main one doesn't. E.g. that there would be two `neurongroup_2_state_updater` objects, but only one `neurongroup_2` object. So I'd say nothing to worry about, but should be fixed for consistency with earlier versions.
