### ISSUE TITLE
Are Units checked in synapses ?

### ISSUE THREAD

**Issue by ttxtea** [brian-team/brian2#1346]
Here is a strange example with a purposefully wrong unit for the synaptic weight. However this runs on several machines without any error message.

~~~
from brian2 import *
n = 10
v0 = 1.05
tau = 10*ms

eqs = '''
dv/dt = (v0 - v + Igap) / tau : 1
Igap : 1 # unitless current 
'''
neurons = NeuronGroup(n, eqs, threshold='v > 1', reset='v = 0',
                      method='exact')
neurons.v = 'i * 1.0 / (n-1)'
trace = StateMonitor(neurons, 'v', record=[0, 5])

S = Synapses(neurons, neurons, '''
             w : kilogram # gap junction wight with wrong unit
             Igap_post = w * (v_pre - v_post) : 1 (summed)
             ''')
S.connect()
S.w = .02 * kilogram
run(500*ms)
plot(trace.t/ms, trace[0].v)
plot(trace.t/ms, trace[5].v)
xlabel('Time (ms)')
ylabel('v')
show()
~~~

**Comment by mstimberg** [comment]
Thanks for the report! It does indeed seem that summed variables do not check the unit of the RHS expression.

Note that AFAICT this bug only affects summed variables – e.g. differential equations in `Synapses` are checked correctly. Also, it only affects the overall outcome of the RHS; unit errors *within* the RHS are still detected (e.g. if it used `w + v_pre - v_post`).
