### ISSUE TITLE
Network load from file 

### ISSUE THREAD

**Issue by Alexis-Melot** [brian-team/brian2#1370]
Hello,

I am training a large network for classification and I stored the network to a file like this `net.store('training', filename='net_trained')` to avoid re-training each time and directly skip to the test part. But I have trouble to restore my network from this file on another run. I made sure to recreate the objects add them to the network and I call this  instead of running the training simulation : 
 `net = Network(input_group, excitatory_group, inhibitory_group, input_synapse, e_i_synapse, i_e_synapse, e_monitor)` 
 `net = Network.restore(net, name='training', filename = 'net_trained')` 
 `print(net.objects)`

but I get this AttributeError:  'NoneType' object has no attribute 'objects'

**Comment by mstimberg** [comment]
Hi @Alexis-Melot. The `Network.restore` method does not return anything (therefore `net` will be `None` in the last line), instead it restores things inside the object. This means instead of `net = Network.restore(...)` use:
```
net.restore(name='training', filename='net_trained')
```
Let us know whether this works for you!

**Comment by Alexis-Melot** [comment]
thanks for your quick reply, it works perfectly !

**Comment by Alexis-Melot** [comment]
I have another question, my training is very slow, is there a way to accelerate the process ?

**Comment by mstimberg** [comment]
Happy it works. The execution speed depends a lot on the specifics of your model. Can you open a thread on https://brian.discourse.group with some more details and example code? This is a better place for this kind of discussion.
