### ISSUE TITLE
[question] Winnter-Take-all

### ISSUE THREAD

**Issue by davideschiavone** [brian-team/brian2#1379]
Dear all, 

is there a way to connect a neuron to another neuron in the same layer? (even itself)

Thanks a lot

Davide

**Comment by unstablecursor** [comment]
```
G = NeuronGroup(N, eqs, threshold='v>1.0', reset='v = 0.0', method='exact')
# Here just specify G,G to connect to group to itself
S = Synapses(G, G, 'w : 1', on_pre='v_post += w')
S.connect(condition="i=j") 

```
this will connect each neuron to itself. If condition string is empty, then it will connect every neuron to every neuron.

**Comment by davideschiavone** [comment]
thanks a lot
