### ISSUE TITLE
how to add brian2 objects together and run

### ISSUE THREAD

**Issue by ivapl** [brian-team/brian2#1414]
I created a class that contains the parameters, group of neurons, synapses stored in a dictionary.

For example the parameter for input resistance for excitatory neuron is created like self.Rin["E"] and self.Rin["Isom"] for inhibitory somatostatin neurons. 

The group of neurons is created via function in the class using the brian2 objects:

self.createNeuron()

The excitatory neurons will be stored in self.groupNeuron["E"] and self.groupNeuron["Isom] for somatostatin.
I will create the synapses and connect them in a similar way.

When I run the simulation, the spike monitor and the population rate are empty. From what I understand based on what I have read so far, the brian2 was not able to recognize what I am doing because the brian2 objects are stored in a different way.

I also saw that there is a function called _add_. I tried to add the group of neurons, synapses, and the monitors but I still got empty result. Should I add more objects? If yes, what are those objects?

Can I inherit brian2 that will allow brian2 to recognize that I have created brian2 objects? If yes, which class should I inherit? Thank you so much in advance for your time on this!

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

In general, your approach should work but hard to say without seeing some code. Did you call `run` on the `Network` object where you added the objects? If you use `Network.add` but then later call a simple `run`, it would ignore the `Network`. It should look like this:
```python
# define objects
net = Network()
net.add(...)  # add objects, alternatively you can also call Network(...) with the objects
net.run(...)
```
https://brian2.readthedocs.io/en/stable/user/running.html#networks

**Comment by ivapl** [comment]
Thanks @mstimberg for your quick response! I will keep this in mind next time. Thanks for letting me know!

I modified the code as you have described. I am getting an error about the NeuronGroup. I might have missed something here. Here is the error:

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/core/network.py:892, in Network.before_run(self, run_namespace)
    891 try:
--> 892     obj.before_run(run_namespace)
    893 except Exception as ex:

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/groups/neurongroup.py:878, in NeuronGroup.before_run(self, run_namespace)
    876 def before_run(self, run_namespace=None):
    877     # Check units
--> 878     self.equations.check_units(self, run_namespace=run_namespace)
    879     # Check that subexpressions that refer to stateful functions are labeled
    880     # as "constant over dt"

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/equations/equations.py:1018, in Equations.check_units(self, group, run_namespace)
   1016 external -= set(all_variables.keys())
-> 1018 resolved_namespace = group.resolve_all(external, run_namespace,
   1019                                        user_identifiers=external)  # all variables are user defined
   1021 all_variables.update(resolved_namespace)

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/groups/group.py:731, in Group.resolve_all(self, identifiers, run_namespace, user_identifiers, additional_variables)
    730 for identifier in identifiers:
--> 731     resolved[identifier] = self._resolve(identifier,
    732                                          user_identifier=identifier in user_identifiers,
    733                                          additional_variables=additional_variables,
    734                                          run_namespace=run_namespace)
    735 return resolved

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/groups/group.py:691, in Group._resolve(self, identifier, run_namespace, user_identifier, additional_variables)
    689 # We did not find the name internally, try to resolve it in the external
    690 # namespace
--> 691 return self._resolve_external(identifier, run_namespace=run_namespace)

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/groups/group.py:814, in Group._resolve_external(self, identifier, run_namespace, user_identifier, internal_variable)
    813             error_msg = f'The identifier "{identifier}" could not be resolved.'
--> 814         raise KeyError(error_msg)
    816 elif len(matches) > 1:
    817     # Possibly, all matches refer to the same object

KeyError: 'The identifier "taum_E" could not be resolved.'

The above exception was the direct cause of the following exception:

BrianObjectException                      Traceback (most recent call last)
Input In [2], in <cell line: 16>()
     14 model.modelMonitor(right_neurons)
     15 model.iniStateVar(right_neurons)
---> 16 model.runNetwork(right_neurons, right_syn)

Input In [1], in ml.runNetwork(self, groupNeurons, synapses)
    406 self.addObject(groupNeurons, synapses)
    407 self.net.store()
--> 408 self.net.run(self.duration, report = 'text', report_period = 30*second)
    409 self.runresults = dict(input_times=self.times, input_ids=self.indices,
    410                   M_E_t=self.sMonitor["E"].t/ms,M_E_i=self.sMonitor["E"].i[:],
    411                   M_I5ht_t=self.sMonitor["Ivip"].t/ms, M_I5ht_i=self.sMonitor["Ivip"].i[:],
    412                   M_Ipv_t=self.sMonitor["Ipv"].t/ms,M_Ipv_i=self.sMonitor["Ipv"].i[:],
    413                   M_Isom_t=self.sMonitor["Isom"].t/ms,M_Isom_i=self.sMonitor["Isom"].i[:])
    414 scipy.io.savemat('layer23_example_spikes.mat', self.runresults)

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/core/base.py:293, in device_override.<locals>.device_override_decorator.<locals>.device_override_decorated_function(*args, **kwds)
    291     return getattr(curdev, name)(*args, **kwds)
    292 else:
--> 293     return func(*args, **kwds)

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/units/fundamentalunits.py:2428, in check_units.<locals>.do_check_units.<locals>.new_f(*args, **kwds)
   2421             error_message = (f"Function '{f.__name__}' "
   2422                              f"expected a quantitity with unit "
   2423                              f"{unit} for argument '{k}' but got "
   2424                              f"'{value}'")
   2425             raise DimensionMismatchError(error_message,
   2426                                          get_dimensions(newkeyset[k]))
-> 2428 result = f(*args, **kwds)
   2429 if 'result' in au:
   2430     if isinstance(au['result'], Callable) and au['result'] != bool:

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/core/network.py:1006, in Network.run(self, duration, report, report_period, namespace, profile, level)
   1003 if namespace is None:
   1004     namespace = get_local_namespace(level=level+3)
-> 1006 self.before_run(namespace)
   1008 if len(all_objects) == 0:
   1009     return  # TODO: raise an error? warning?

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/core/base.py:293, in device_override.<locals>.device_override_decorator.<locals>.device_override_decorated_function(*args, **kwds)
    291     return getattr(curdev, name)(*args, **kwds)
    292 else:
--> 293     return func(*args, **kwds)

File ~/opt/anaconda3/envs/ml/lib/python3.9/site-packages/brian2/core/network.py:894, in Network.before_run(self, run_namespace)
    892             obj.before_run(run_namespace)
    893         except Exception as ex:
--> 894             raise BrianObjectException("An error occurred when preparing an object.", obj) from ex
    896 # Check that no object has been run as part of another network before
    897 for obj in all_objects:

BrianObjectException: Error encountered with object named 'neurongroup'.
Object was created here (most recent call only, full details in debug log):
  File '/var/folders/tw/l49xbw2n6pd8lbywmd7hhgt80000gn/T/ipykernel_45410/541028591.py', line 292, in createNeurons
    return NeuronGroup(n, model=eqs, threshold='V > vth', reset='V = vrest', refractory=ref, method = 'euler')

An error occurred when preparing an object. (See above for original error message and traceback`

Here is the part of the class that I am using:

`    def createNeurons(self, n=None, eqs=None, ref=None): # create neurons
        return NeuronGroup(n, model=eqs, threshold='V > vth', reset='V = vrest', refractory=ref, method = 'euler')

    def createNeurons_batch(self): # create group of neurons by batch
        groupNeuron = {}
        for neuron in self.cellType:
            groupNeuron[neuron] = self.createNeurons(self.N[neuron],self.eqs[neuron], self.ref[neuron])
        return groupNeuron

    def createSynapses_E(self, groupA=None, groupB=None, neuronA=None, neuronB=None):
        return Synapses(groupA[neuronA],groupB[neuronB],'ge_syn : siemens',on_pre='ge_post += ge_syn*(floor(rand() + prel_' + neuronA + neuronB +'))')

    def createSynapses_I(self, groupA=None, groupB=None, neuronA=None, neuronB=None):
        return Synapses(groupA[neuronA],groupB[neuronB],'gi_syn : siemens',on_pre='gi_post += gi_syn*(floor(rand() + prel_' + neuronA + neuronB +'))')

    def createSynapses_batch(self, key=None, groupA=None, groupB=None):
        synapses = {}
        for neuronA in self.cellType:
            for neuronB in self.cellType:
                if neuronA == "E":
                    synapses[key + "_" + neuronA + neuronB] = self.createSynapses_E(groupA, groupB, neuronA, neuronB)
                else:
                    synapses[key + "_" + neuronA + neuronB] = self.createSynapses_I(groupA, groupB, neuronA, neuronB)

        return synapses
    
    def connectNeurons(self, synapse=None, conn=None, p=None):
        return synapse.connect(conn, p=p)
        
    def connectNeurons_batch(self, synapses):
        for syn in synapses.keys():
            if self.findPattern(syn.split("_")[1]): # if the connection is itself EE (find repeating pattern on a string)
                self.connectNeurons(synapse=synapses[syn], conn="i!=j", p=self.pcon[syn.split("_")[1]])
            else:
                self.connectNeurons(synapse=synapses[syn], conn=True, p=self.pcon[syn.split("_")[1]])
    
    def findPattern(self, s):
        i = (s+s).find(s, 1, -1)
        return None if i == -1 else s[:i]
    
    def setWeights(self, synapses):
        for syn in synapses.keys():
            key = syn.split("_")[1]
            if key[0] == "E": #check if excitatory
                synapses[syn].ge_syn = clip( exp(log(self.gsyn_median[key]/nS) + sqrt(2*log(self.gsyn_mean[key]/self.gsyn_median[key]))*randn(size(synapses[syn].ge_syn)) ) , 0, self.gmax ) * nS
            else:
                synapses[syn].gi_syn = clip( exp(log(self.gsyn_median[key]/nS) + sqrt(2*log(self.gsyn_mean[key]/self.gsyn_median[key]))*randn(size(synapses[syn].gi_syn)) ) , 0, self.gmax ) * nS                
    
    def set_voltages(self, groupNeuron):
        for g in groupNeuron:
            # voltage thresholds
            groupNeuron[g].vth = self.Vth[g] + self.Vth["sd"]*randn(size(groupNeuron[g].vth))
            # resting potentials
            groupNeuron[g].vrest = self.Vrest[g] + self.Vrest["sd"]*randn(size(groupNeuron[g].vrest))
    
    def createInput(self):
        cellvec = numpy.linspace(0,self.N["EL4"]-1,self.N["EL4"])
        cellvec = cellvec.astype(int)
        idx = numpy.arange(cellvec.size)
        numpy.random.shuffle(idx)
        self.indices = sort(idx[:self.NL4_ON])
        self.times = array(10*ones(size(indices)) + randn(self.NL4_ON))*ms
        self.G_INPUT = SpikeGeneratorGroup(self.N["EL4"], self.indices, self.times,name = 'Inputgroup')
        
    def connectInput(self, postSyn):
        self.inputSynapses = {}
#         import pdb; pdb.set_trace()
        for i in postSyn.keys():
            self.inputSynapses[i] = Synapses(self.G_INPUT,postSyn[i],'ge_syn : siemens',on_pre='ge_post += ge_syn*(floor(rand()+prel_EL4' + i + '))')
            self.inputSynapses[i].connect(True, p=self.pcon["EL4" + i])
            self.inputSynapses[i].ge_syn = exp(log(self.gsyn_median["EL4" + i]/nS) + sqrt(2*log(self.gsyn_mean["EL4" + i]/self.gsyn_median["EL4" + i]))*randn(size(self.inputSynapses[i].ge_syn)) ) * nS

    def modelMonitor(self, groupNeurons):
        self.sMonitor = {}
        self.vMonitor = {}
        self.geMonitor = {}
        self.giMonitor = {}
        self.popRate = {}

        for g in groupNeurons.keys():
            if g[0] == "E":
                self.sMonitor[g] = SpikeMonitor(groupNeurons[g])
                self.vMonitor[g] = StateMonitor(groupNeurons[g], 'V', record=[0,1])
                self.geMonitor[g] = StateMonitor(groupNeurons[g], 'ge', record=0)
                self.giMonitor[g] = StateMonitor(groupNeurons[g], 'gi', record=0)
                self.popRate[g] = PopulationRateMonitor(groupNeurons[g])
#                 self.net.add([groupNeurons[g],self.SpikeMonitor[g],self.vMonitor[g],
#                               self.geMonitor[g], self.giMonitor[g], self.popRate[g]])
            else:
                self.sMonitor[g] = SpikeMonitor(groupNeurons[g])
                self.vMonitor[g] = StateMonitor(groupNeurons[g], 'V', record=0)
                self.geMonitor[g] = StateMonitor(groupNeurons[g], 'ge', record=0)
                self.giMonitor[g] = StateMonitor(groupNeurons[g], 'gi', record=0)
                self.popRate[g] = PopulationRateMonitor(groupNeurons[g])
#                 self.net.add([groupNeurons[g], self.SpikeMonitor[g],self.vMonitor[g],
#                               self.geMonitor[g], self.giMonitor[g], self.popRate[g]])

    def iniStateVar(self, groupNeurons):
        for g in groupNeurons.keys():
            groupNeurons[g].V = self.Vrest[g]
    
    def addObject(self,groupNeurons, synapses):
        for g in groupNeurons.keys():
            self.net.add(groupNeurons[g])
        for s in synapses.keys():
            self.net.add(synapses[s])
        for m in self.sMonitor.keys():
            self.net.add(self.sMonitor[m])
        for p in self.popRate.keys():
            self.net.add(self.sMonitor[p])
#         for e in self.eqs.keys():
#             self.net.add(self.eqs[e])
            
    def runNetwork(self, groupNeurons, synapses):
        self.net = Network()
        self.addObject(groupNeurons, synapses)
        self.net.store()
        self.net.run(self.duration, report = 'text', report_period = 30*second)
        self.runresults = dict(input_times=self.times, input_ids=self.indices,
                          M_E_t=self.sMonitor["E"].t/ms,M_E_i=self.sMonitor["E"].i[:],
                          M_I5ht_t=self.sMonitor["Ivip"].t/ms, M_I5ht_i=self.sMonitor["Ivip"].i[:],
                          M_Ipv_t=self.sMonitor["Ipv"].t/ms,M_Ipv_i=self.sMonitor["Ipv"].i[:],
                          M_Isom_t=self.sMonitor["Isom"].t/ms,M_Isom_i=self.sMonitor["Isom"].i[:])
        scipy.io.savemat('layer23_example_spikes.mat', self.runresults)
        return`

And here is the code that I run:

`right_neurons = model.createNeurons_batch()
right_syn = model.createSynapses_batch("right", right_neurons, right_neurons)
model.connectNeurons_batch(right_syn)
model.setWeights(right_syn)
model.createInput()
model.connectInput(right_neurons)
model.modelMonitor(right_neurons)
model.iniStateVar(right_neurons)
model.runNetwork(right_neurons, right_syn)`

Thank you for your time on this!

**Comment by ivapl** [comment]
After going through the error, it was because of how the equations were written. Which is like this:

```python
        self.eqs["E"] = Equations('''
                            dV/dt = ( Rin_E*( ge*(Erev_e - V) + gi*(Erev_iE - V) ) - (V-vrest) )/taum_E : volt (unless refractory)
                            dge/dt = -ge/tau_Ee : siemens
                            dgi/dt = -gi/tau_Ei : siemens
                            vth : volt
                            vrest : volt
                            ''')
```

I did not change the taum_E into a proper way of calling from the class. It is initialized in the class as self.taum["E"]. Could you let me know how should I call them in the equations please?

**Comment by ivapl** [comment]
Alright, I used namespace to call them and  it's working. I will use it for other functions and will update it here again.

**Comment by ivapl** [comment]
It's working now. Thank you so much @mstimberg!

**Comment by mstimberg** [comment]
> Alright, I used namespace to call them and it's working. I will use it for other functions and will update it here again.

I was about to use suggest to use namespace (https://brian2.readthedocs.io/en/stable/advanced/namespaces.html) :) Happy to hear it is working for you now.
