### ISSUE TITLE
Implementation of alpha synapses for a conductance based point LIF neuron model in Brian2

### ISSUE THREAD

**Issue by sras202** [brian-team/brian2#1432]
Hi everyone !

I am new to Brian2 and I am trying to connect two conductance based point LIF neuron model through alpha synapses. Neuron n1 receives sinusoidal input and Neuron n2 receives input from neuron n1 through alpha synapse. Here is my code : 

import pandas as pd

import numpy as np

from scipy import signal

start_scope()

seed(11922)

# Parameters

n_n1=5

n_n2=5

# Neuron Parameters

# Neuron n1

E_l_n1=-70*mV                   # Leak Reversal Potential

E_e_n1=0*mV                     # Excitatory synaptic reversal potential

E_i_n1=-80*mV                   # Inhibitory synaptic reversal potential

C_m_n1=198*pF                   # Membrane Capacitance

tau_n1=20*ms                    # Membrane time constant

g_L_n1=C_m_n1/tau_n1            # Leak conductance

tau_e_n1=5*ms                   # Excitatory synaptic time constant

tau_i_n1=10*ms                  # Inhibitory synaptic time constant

tau_r_n1=5*ms                   # Refractory period

V_th_n1=-55*mV                  # Firing threshold

V_r_n1=E_l_n1                   # Reset potential

# Synapse parameters

w_e_n1=0.05*nS                     # Excitatory synaptic conductance

w_i_n1=1.0*nS                     # Inhibitory synaptic conductance

# Neuron n2

E_l_n2=-70*mV                   # Leak Reversal Potential

E_e_n2=0*mV                     # Excitatory synaptic reversal potential

E_i_n2=-80*mV                   # Inhibitory synaptic reversal potential

C_m_n2=198*pF                   # Membrane Capacitance

tau_n2=20*ms                    # Membrane time constant

g_L_n2=C_m_n2/tau_n2            # Leak conductance

tau_e_n2=5*ms                   # Excitatory synaptic time constant

tau_i_n2=10*ms                  # Inhibitory synaptic time constant

tau_r_n2=5*ms                   # Refractory period

V_th_n2=-53*mV                  # Firing threshold

V_r_n2=E_l_n2                   # Reset potential

# Synapse parameters

w_e_n2=0.05*nS                     # Excitatory synaptic conductance

w_i_n2=1.0*nS                     # Inhibitory synaptic conductance

t_recorded=np.arange(int(20000*ms/defaultclock.dt))*defaultclock.dt

I_rec_1_sin=TimedArray(I1_1_sin*amp,dt=defaultclock.dt)                # Sinusoidal input signal (fed to neuron n1)

eqs_n1='''
dv/dt=(I_syn_e/C_m_n1)+(I/(g_L_n1*tau_n1))+(g_L_n1*(v-E_l_n1)+g_e*(v-E_e_n1)+g_i*(v-E_i_n1))/C_m_n1:volt
I_syn_e=g_e*(E_e_n1-v):amp
I=I_rec_1_sin(t):amp
dg_e/dt=(s_e-g_e)/tau_e_n1:siemens
dg_i/dt=(s_i-g_i)/tau_i_n1:siemens
ds_e/dt=-s_e/tau_e_n1:siemens
ds_i/dt=-s_i/tau_i_n1:siemens
'''

eqs_n2='''
dv/dt=(I_syn_e/C_m_n2)+(g_L_n2*(v-E_l_n2)+g_e*(v-E_e_n2)+g_i*(v-E_i_n2))/C_m_n2:volt
I_syn_e=g_e*(E_e_n2-v):amp
dg_e/dt=(s_e-g_e)/tau_e_n2:siemens
dg_i/dt=(s_i-g_i)/tau_i_n2:siemens
ds_e/dt=-s_e/tau_e_n2:siemens
ds_i/dt=-s_i/tau_i_n2:siemens
'''

G_n1=NeuronGroup(n_n1,eqs_n1,threshold='v>V_th_n1',reset='v=V_r_n1',refractory='tau_r_n1',method='rk2')

G_n2=NeuronGroup(n_n2,eqs_n2,threshold='v>V_th_n2',reset='v=V_r_n2',refractory='tau_r_n2',method='rk2')

# Random initial membrane potential values and conductances

G_n1.v='E_l_n1+rand()*(V_th_n1-E_l_n1)'

G_n1.g_e='rand()*w_e_n1'

G_n1.g_i='rand()*w_i_n1'

G_n2.v='E_l_n2+rand()*(V_th_n2-E_l_n2)'

G_n2.g_e='rand()*w_e_n2'

G_n2.g_i='rand()*w_i_n2'

S_n1_n2=Synapses(G_n1,G_n2,on_pre='s_e+=w_e_n1',method='rk2')

S_n1_n2.connect(p=0.1)

# Record the spikes

M_n1=SpikeMonitor(G_n1)

M_n2=SpikeMonitor(G_n2)

# Record the membrane voltage

V_n1=StateMonitor(G_n1,'v',record=True)

V_n2=StateMonitor(G_n2,'v',record=True)

run(20*second)

I found that neuron n2 is not spiking at all inspite of increasing Excitatory synaptic conductance of neuron n1 (which I am using to increment variable s_e while making synaptic connection from n1 to n2. Is my implementation of conductance based neuron with alpha synapses correct ?

Hoping for an early response.

Thanks and Regards
Shavika Rastogi
PhD Scholar

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

Discussion is here: https://brian.discourse.group/t/implementation-of-alpha-synapses-for-a-conductance-based-point-lif-neuron-model-in-brian2/770/2
