### ISSUE TITLE
[Question] Is it possible to run multiple threads/processes to run multipe simulations simultaneously?

### ISSUE THREAD

**Issue by steathy-spikes** [brian-team/brian2#1441]
To whom it may concern

I was wondering if I can leverage multithreading/processing to perform multiple simulations at once.

For example, is it possilbe to run 20 simulations in paralle, if the neuron model that I want to use is the same for all the simulations?

Thank you

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

You can definitely run simulations in parallel, e.g. with Python's built-in `multiprocessing` module. See the examples here: https://brian2.readthedocs.io/en/stable/examples/index.html#multiprocessing
There's also a new feature under development, that makes such tasks more convenient/efficient for Brian's "high performance" C++ standalone mode. See https://brian.discourse.group/t/running-multiple-standalone-simulations-request-for-feedback/802
