### ISSUE TITLE
SpatialNeuron (spatialstateupdate) fails with numpy without scipy

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#1459]
As reported in the [discussion forum](https://brian.discourse.group/t/about-the-problems-of-brian2-test-in-the-test-process-failures-test-spatialneuron-timearray/931), the no-scipy-fallback for `SpatialNeuron` fails with current `master`. This should either be fixed or alternatively we simply declare scipy as a hard dependency? If we fix it, we should also make sure that the CI tests cover this situation.

**Comment by thesamovar** [comment]
I don't have strong feelings about this! I thought scipy was already a requirement. 😂

**Comment by mstimberg** [comment]
scipy's status is a bit odd: we don't require it (since the only place where we need it is to the `SpatialNeuron` state update with numpy), but it gets pulled in quickly if you install other packages (say, `scikit-learn` or `scikit-optimize`). The main reason why we don't install it is that back in the days, installing scipy via `pip` was painful, since it needed to compile it from source (which is no longer the case thanks to Python wheels). We always installed it as a dependency of the `conda` package.

**Comment by thesamovar** [comment]
Ah right, sounds like the reason not to include it has pretty much evaporated so we could just do that? Virtually everything else includes it as you say.

**Comment by mstimberg** [comment]
Yep. The only reason why I am still hesitant is that it is a fairly big package (30-40MB; about twice the size of `numpy` and bigger than all existing dependencies combined), and most of the time we don't need it. But I am very much in favor of simplifying the code and testing procedure – a simple compromise solution would be to simply remove the fallback solution from the code and fail with an error if `scipy` is not installed, but only in the specific case (simulating multi-compartmental model with `numpy` as codegen target) where we need it.

**Comment by thesamovar** [comment]
I feel like the days of worrying about 30-40mb packages are probably mostly over now, right? But I'm happy with whatever solution you think is best.

**Comment by thesamovar** [comment]
I forgot pyodide - good point! That's heavy enough as it is. OK, as you say then!
