### ISSUE TITLE
[Question] Regarding the spatial neuron equation

### ISSUE THREAD

**Issue by hunjunlee** [brian-team/brian2#1466]
Hi guys, I have a question related to the code for the spatial neuron.

I assume that you discretize the cable equation as follows when implementing spatialstateupdate.py.

Cm * (V_{n, t+1} - V_{n, t}) / dt + (g_tot * V_{n, **t+1**} - I_0) = g_{n-1, n} * (V_{n-1, **t+1**} - V_{n, **t+1**}) + g_{n, n+1} * (V_{n, **t+1**} - V_{n+1, **t+1**}) [Equation 1]

where: g_{n-1, n} indicates the conductance between compartment n-1 and n.

But I think that this complicates the equations as you need to solve a complex linear algebra.

I assume that the equation would be much simpler if you discretize the cable equation as follows.

Cm * (V_{n, t+1} - V_{n, t}) / dt + (g_tot * V_{n, **t**} - I_0) = g_{n-1, n} * (V_{n-1, **t**} - V_{n, **t**}) + g_{n, n+1} * (V_{n, **t**} - V_{n+1, **t**}) [Equation 2]

Are there any reason for adopting Equation 1 instead of Equation 2?

Does it make a critical difference in the simulation result?

Thanks.

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

Hi @hunjunlee . Equation 2 would mean an integration with the forward Euler method, which is inaccurate and unstable. How much this matters in practice depends of course on the model, e.g. in a highly simplified model with just a few compartments it might be fine. I find the clearest way to see why this method (or any other explicit) method is not a good choice for complex morphologies is to look at a long cable with many compartments, and current injection or any kind of suddenly increased voltage at one end (all other compartments are at rest). With an explicit method, the current can only propagate one compartment per time step – in the first time step, the second compartment receives a current from the first compartment, in the second time step, the third compartment receives a current from the second compartment, and so on. This means, the time it takes for the current to propagate along the cable depends both on the simulation time step and the number of compartments; both very undesirable properties.

**Comment by hunjunlee** [comment]
Thanks for the immediate reply.

I get the point... Thanks for the reply!

By the way, I'll use the forum from now on.
