### ISSUE TITLE
the Izhikevich_2007 example neuron model bug

### ISSUE THREAD

**Issue by max-talanov** [brian-team/brian2#1476]
Dear all.
Thank you for the great impact involved in creation of the brian2 and documentation and examples.
But I have found the bug in the example [Izhikevich_2007](https://github.com/brian-team/brian2/blob/master/examples/frompapers/Izhikevich_2007.py#L55):
The line 55 contains the formula of the Neuron:
dv/dt = (ge * (Ee-v**r**) + El - v) / taum : volt
While original example [STDP](https://github.com/brian-team/brian2/blob/master/examples/synapses/STDP.py#L26C1-L26C45) contains the following formula:
dv/dt = (ge * (Ee-v) + El - v) / taum : volt
And the original article of Song, Miller and Abbott (2000) page 25:
![image](https://github.com/brian-team/brian2/assets/548287/6128cd49-13e6-40aa-85de-d93c67ba3c7e)
That makes much more sense as ge influence is multiplied to Ee - current voltage rather than reset voltage constant.
In the scope of the Izhikevich_2007 example the bug possibly does not make much difference, but if one tries to reuse the code in the network with combination of STDP and  static synapses STDP synaptic influence could be much lower than static.
Could you please fix this minor issue in the example.
Thank you so much in advance.
Dr. Max Talanov.

**Comment by DHRUVJ2003** [comment]
Hello,
I am interested in solving this issue. Can you please state how can I reproduce the issue? Will changing the formula in [Izhikevich_2007](https://github.com/brian-team/brian2/blob/master/examples/frompapers/Izhikevich_2007.py#L55) solve the issue??
I am new to open source and to brian as well.

Thanks

**Comment by max-talanov** [comment]
Hello.
Yes please update the formula.

**Comment by DHRUVJ2003** [comment]
Thank you 🙏 ..... It is an honour to contribute to brian
