### ISSUE TITLE
[readthedocs] Tutorials disappeared

### ISSUE THREAD

**Issue by kernfel** [brian-team/brian2#1477]
Assuming they haven't been removed on purpose, the tutorials seem to be newly absent from the RTD site. They're still referenced in text (e.g. in index.html), and they turn up in search results (e.g. https://brian2.readthedocs.io/en/stable/search.html?q=introduction+part), but their links end in a 404. I'm pretty sure I've seen them around recently (a couple months back, at most), if that helps to find where they got lost.

**Comment by mstimberg** [comment]
Arf, thanks for letting us know – definitely not on purpose! I'll look into what went wrong. You can still find them at the previous version of the docs: https://brian2.readthedocs.io/en/2.5.1/

**Comment by mstimberg** [comment]
Tutorials (and example plots) are back: https://brian2.readthedocs.io/en/latest/
I'll make a new release so that it appears correctly in the `stable` version as well.
