### ISSUE TITLE
Setting Neuron weights?

### ISSUE THREAD

**Issue by IanQS** [brian-team/brian2#1494]
Good day! 

I'm trying to set neuron weights directly. I can't seem to find anything on the [models](https://brian2.readthedocs.io/en/stable/user/models.html) documentation page, but I do see something about [synapses/synaptic-connection-weight-matrices](https://brian2.readthedocs.io/en/stable/user/synapses.html#synaptic-connection-weight-matrices). Unfortunately, in my scenario, I do not know the "identity" of the synapses. My data is of the form

```python
[ 
    [0, 5, 0],
    [0, 0, -2],
    [0, 0, 0],
]
```

where the rows are the `pre-` and the cols describe the `post-` neurons. In the case of the matrix above, the first neuron is excitatory and connected to second neuron by 5 synapses. The second neuron is connected to the third neuron in an inhibitory manner, and there are two synapses between them.

Can you point me in the right direction? I've tried searching through the documentation, but I don't know enough to know if what I'm finding is particularly relevant. I've also tried searching through the open and closed issues, but I don't think that they apply in my scenario.

**Comment by mstimberg** [comment]
[In the future, please direct questions or error reports where you are not sure whether it is "Brian's fault" to Brian's [discussion forum](https://brian.discourse.group), we try to keep the github issues for bugs and feature requests.]

Hi, sorry for the late reply, holidays got into the way (and also note the above comment about the discussion forum being a better place for such questions). 

I am assuming that when you say e.g. "connected by 5 synapses", you want to connect with a weight of 5, not actually model 5 independent synapses? We indeed do not mention this use case (sparse connectivity with given weights) in the documentation – but I think it would be a useful addition! The basic approach is the same as the one mentioned in the documentation. The key is to use numpy's `nonzero` function to get the indices of the non-zero elements (`C` would be your example matrix from above):
```python
sources, targets = C.nonzero()
synapses = Synapses(..., "w : 1", ...)
synapses.connect(i=sources, j=targets)
```
in your case, you then want to also set the weights, and you can get them using the indices as indices into the weight matrix:
```python
synapses.w[:] = C[(sources, targets)]
```

Hope that works for you!

**Comment by mstimberg** [comment]
Closing this issue, discussion has continued on the forum.
