### ISSUE TITLE
Value error in stdp code

### ISSUE THREAD

**Issue by hanbuck30** [brian-team/brian2#1538]
I run a file called stdp, and I got a file called ValueError: The pyNN.brian2 backend does not currently support dendritic days: for the purpose of the STDP calibration all delays are accumulated to be axonal. Can you tell me what the problem is?

**Comment by mstimberg** [comment]
Hi. This is not an error from Brian itself, but from the `brian2` backend in PyNN. Could you please open an issue in their repository (https://github.com/NeuralEnsemble/PyNN) or on their mailing list (https://groups.google.com/g/neuralensemble)? In either case, please provide more details about the "file called stdp".
