### ISSUE TITLE
Small error in the Maass_Natschlaeger_Markram_2002 example

### ISSUE THREAD

**Issue by bjourne** [brian-team/brian2#1539]
Maass 2002  says:

> In the case of a synaptic connection from a to b, we modeled the synaptic dynamics according to the model proposed in Markram, Wang, and Tsodyks (1998), with the synaptic parameters U (use), D (time constant for depression), and F (time constant for facilitation) randomly chosen from gaussian distributions that were based on empirically found data for such connections. Depending on whether a, b were excitatory (E) or inhibitory (I), the mean values of these three parameters (with D, F expressed in second, s) were chosen to be .5, 1.1, .05 (EE), .05, .125, 1.2 (EI), .25, .7, .02 (IE), .32, .144, and .06 (II). **The SD of each parameter was chosen to be 50% of its mean** (with negative values replaced by values chosen from an appropriate uniform distribution).

So the line

    synapses.U[:] = np.random.normal(U, 0.5, size=N_syn)

should be 

    synapses.U[:] = np.random.normal(U, 0.5 * U, size=N_syn)

The change doesn't affect the result afaict.

**Comment by mstimberg** [comment]
Many thanks (apologies for the late reply…), that sounds right – for `D` and `F`, this seemed to have been applied correctly.
