### ISSUE TITLE
I don't get a correct answer

### ISSUE THREAD

**Issue by mareba2030** [brian-team/brian2#1542]
Why, despite the synaptic connections between neurons, after applying an external stimulus to the network, only neurons in the same direction as the input have an acceptable response output, and zero response is observed for other neurons. In other words, why neurons connected to neurons of the same direction do not respond, even weakly, despite the presence of external input

**Comment by mareba2030** [comment]
here is my code
# -*- coding: utf-8 -*-
"""layer V1.ipynb

Automatically generated by Colab.

"""

!pip install brian2              #install library

from gettext import install
from brian2 import *

# populations in V1 layer

N = 1250            # Number of neurons
N_E = int(N * 0.8)  # Excitetory (pyramidal) neurons
N_I = int(N * 0.2)  # Inhibitory (interneurons) neurons

# voltage
V_L = -70. * mV
V_thr = -50. * mV
V_reset = -55. * mV
V_E = 0. * mV
V_I = -70. * mV
# membrane capacitance
C_m_E = 0.5 * nF
C_m_I = 0.2 * nF
# membrane leak
g_m_E = 25. * nS
g_m_I = 20. * nS
# refractory period
tau_rp_E = 2. * ms
tau_rp_I = 1. * ms
# AMPA (for excitatory neurons)
g_AMPA_ext_E = 2.08 * nS
g_AMPA_rec_E = 0.104 * nS * 1000. / N_E
g_AMPA_ext_I = 1.62 * nS
g_AMPA_rec_I = 0.081 * nS * 1000. / N_E
tau_AMPA = 2. * ms
# NMDA ( for excitatory neurons)
g_NMDA_E = 0.327 * nS * 1000. / N_E
g_NMDA_I = 0.258 * nS * 1000. / N_E
tau_NMDA_rise = 2. * ms
tau_NMDA_decay = 100. * ms
alpha = 0.5 / ms
Mg2 = 1.
# GABAergic (inhibitory)
g_GABA_E = 1.287 * nS * 200. / N_I
g_GABA_I = 1.002 * nS * 200. / N_I
tau_GABA = 10. * ms
# subpopulations
f = 0.5
p = 2                              # Number of selective pools
N_sub = int(N_E * f)               # slective pools neuron
w_plus = 1.5*1000                       #Synaptic weights
w_minus = (1. - f * (w_plus - 1.) / (1. - f))*1000
w_i = 1.0 *1000



# serotonin_increase = 1.2 
# serotonin_release_time = 1500 * ms 


# modeling
eqs_E = '''
dv / dt = (- g_m_E * (v - V_L) - I_syn) / C_m_E : volt (unless refractory)

I_syn = I_AMPA_ext + I_AMPA_rec + I_NMDA_rec + I_GABA_rec : amp

I_AMPA_ext = g_AMPA_ext_E * (v - V_E) * s_AMPA_ext : amp
I_AMPA_rec = g_AMPA_rec_E * (v - V_E) * w * s_AMPA : amp
ds_AMPA_ext / dt = - s_AMPA_ext / tau_AMPA : 1
ds_AMPA / dt = - s_AMPA / tau_AMPA : 1
w:1

I_NMDA_rec = g_NMDA_E * (v - V_E) / (1 + Mg2 * exp(-0.062 * v / mV) / 3.57) *w* s_NMDA : amp
ds_NMDA / dt = - s_NMDA / tau_NMDA_decay + alpha * x * (1 - s_NMDA) : 1
dx / dt = - x / tau_NMDA_rise : 1


I_GABA_rec = g_GABA_E * (v - V_I) * w*s_GABA : amp
ds_GABA / dt = - s_GABA / tau_GABA : 1
'''
eqs_I = '''
dv / dt = (- g_m_I * (v - V_L) - I_syn) / C_m_I : volt (unless refractory)

I_syn = I_AMPA_ext + I_AMPA_rec + I_NMDA_rec + I_GABA_rec : amp

I_AMPA_ext = g_AMPA_ext_I * (v - V_E) * s_AMPA_ext : amp
I_AMPA_rec = g_AMPA_rec_I * (v - V_E) * w * s_AMPA : amp
ds_AMPA_ext / dt = - s_AMPA_ext / tau_AMPA : 1
ds_AMPA / dt = - s_AMPA / tau_AMPA : 1
w:1

I_NMDA_rec = g_NMDA_I * (v - V_E) / (1 + Mg2 * exp(-0.062 * v / mV) / 3.57) * w*s_NMDA : amp
ds_NMDA / dt = - s_NMDA / tau_NMDA_decay + alpha * x * (1 - s_NMDA) : 1
dx / dt = - x / tau_NMDA_rise : 1

I_GABA_rec = g_GABA_I * (v - V_I) * w*s_GABA : amp
ds_GABA / dt = - s_GABA / tau_GABA : 1
'''

# prefered orientation for selective pool S1

angles_E_first_half = np.linspace(-90, 90, N_E//2).astype(int)

# prefered orientation for selective pool S2

angles_E_second_half = np.linspace(-90, 90, N_E//2).astype(int)

# prefered orientation for Excitetory Pools

angles_E = np.concatenate((angles_E_first_half, angles_E_second_half))

# prefered orientation for Inhibitory Pools

angles_I = np.linspace(-90, 90, N_I).astype(int)



P_E = NeuronGroup(N_E, eqs_E, threshold='v > V_thr', reset='v = V_reset', refractory=tau_rp_E, method='euler')
P_E.v = V_L
P_I = NeuronGroup(N_I, eqs_I, threshold='v > V_thr', reset='v = V_reset', refractory=tau_rp_I, method='euler')
P_I.v = V_L


#add atribute angle
P_E.add_attribute('angle')
P_I.add_attribute('angle')


P_E.angle = np.array(angles_E)
P_I.angle = np.array(angles_I)





# E to E Synapses
C_E_E = Synapses(P_E, P_E,  method='euler')
C_E_E.connect('i != j')
C_E_E.w[:] = 1
    #Synaptic weight between selective pools
C_E_E.w[C_E_E.indices[0:N_sub, N_sub:2*N_sub]] = w_minus
C_E_E.w[C_E_E.indices[N_sub:2*N_sub, 0:N_sub ]] = w_minus
    #Synaptic weight inside selective pools
for pi in range(0,  p * N_sub, N_sub):
    C_E_E.w[C_E_E.indices[pi:pi + N_sub, pi:pi + N_sub]] = w_plus

# E to I Synapses
C_E_I = Synapses(P_E, P_I,  method='euler')
C_E_I.connect()
C_E_I.w[:] = 1
# I to I Synapses
C_I_I = Synapses(P_I, P_I, method='euler')
C_I_I.connect('i != j')
C_I_I.w[:] = 1
# I to E Synapses
C_I_E = Synapses(P_I, P_E, method='euler')
C_I_E.connect()
C_I_E.w[:] = 1
    #Synaptic weight from Inhibitory Neurons To selective pools
C_I_E.w[C_I_E.indices[:, 0:2*N_sub]] = w_i




# External Inputs

    #V_ext
in3=PoissonInput(P_I, 's_AMPA_ext', 1000, 2.4*Hz, '1')
in4=PoissonInput(P_E, 's_AMPA_ext', 1000, 2.4*Hz, '1')

stimuli_angle = 0

stimuli1 = TimedArray(np.r_[np.zeros(100), np.ones(100), np.zeros(20)], dt=10 * ms)

stimuli1_1 = TimedArray(np.r_[np.zeros(100), np.ones(100), np.zeros(20)], dt=10 * ms)

stimuli2 = TimedArray(np.r_[np.zeros(100), np.ones(100), np.zeros(20)], dt=10 * ms)

for i in range(len(P_E)):
    if P_E.angle[i] == stimuli_angle and i < N_sub:
        # External Inputs
        # V_in
       in1 = PoissonInput(P_E[i], 's_AMPA_ext', 10000, 750*Hz, 'stimuli1(t)')
       in2 = PoissonInput(P_E[i], 's_AMPA_ext', 5000, 240*Hz, 'stimuli2(t)')
    else:
      for i in range(len(P_E)):
         if P_E.angle[i] == stimuli_angle and i >= N_sub:
        # External Inputs
        # V_in
          in11 = PoissonInput(P_E[i], 's_AMPA_ext', 1000, 75*Hz, 'stimuli1_1(t)')
         else:
           pass


# MONITOR for layer V1
S_S1 = StateMonitor(P_E[0:500], 'I_syn', record = True)
S_S2 = StateMonitor(P_E[500:1000], 'I_syn', record = True)

S_Inh = StateMonitor(P_I, 'I_syn', record = True)


M_S1 = SpikeMonitor(P_E[0:500])
M_S2 = SpikeMonitor(P_E[500:1000])

M_Inh = SpikeMonitor(P_I)


R_S1 = PopulationRateMonitor(P_E[0:500])
R_S2 = PopulationRateMonitor(P_E[500:1000])

R_Inh = PopulationRateMonitor(P_I)


run(2200*ms)

#Plots for layer V1

    #Selective pool S1 rate
figure()
rate_S1 = R_S1.smooth_rate(width = 10*ms)
plot(R_S1.t/ms, rate_S1/Hz)
xlabel('Time (ms)')
ylabel('Firing Rate of S1 (HZ) in V1')


    #Selective pool S2 rate
figure()
rate_S2 = R_S2.smooth_rate(width = 10*ms)
plot(R_S2.t/ms, rate_S2/Hz)
xlabel('Time (ms)')
ylabel('Firing Rate of S2  (HZ)in V1')





    #Inhibitory pool  rate
figure()
rate_Inh = R_Inh.smooth_rate(width = 10*ms)
plot(R_Inh.t/ms, rate_Inh/Hz)
xlabel('Time (ms)')
ylabel('Firing Rate of Inhibitory pool (HZ) in V1')


    #All Pool Rate
figure()
plot(R_S1.t/ms, rate_S1/Hz)
plot(R_S2.t/ms, rate_S2/Hz)

plot(R_Inh.t/ms, rate_Inh/Hz)
xlabel('Time (ms)')
ylabel('Firing Rate (HZ)')
plt.legend(['Selective pool S1', 'Selective pool S2','Inhibitory pool'])


    #Firing neuron for selective pools
figure()
title('Firing neuron for selective pool')
plot(M_S1.t/ms, M_S1.i, '.k',color="blue")
plot(M_S2.t/ms, M_S2.i+500, '.k',color="red")
xlabel('Time (ms)')
ylabel('Neuron Index in V1')


    #LFP for S1
figure()
title('Raw LFP')
ss=0
for i in range(0, 500):
    ss += S_S1.I_syn[i]
sss = ss/500
plot(S_S1.t[200:22000]/ms, sss[200:22000]/namp, '-k',color="green")
xlabel('Time (ms)')
ylabel('S1_LFP (namp)in V1')

    #LFP for S2
figure()
title('Raw LFP')
ss=0
for i in range(0, 500):
    ss += S_S2.I_syn[i]
sss = ss/500

plot(S_S2.t[200:22000]/ms, sss[200:22000]/namp, '-k',color="green")
xlabel('Time (ms)')
ylabel('S2_LFP (namp)in V1')

#Spike for Selective pool S1
figure()
title('Spike for selective pool S1')
plot(M_S1.t/ms, M_S1.i, '|', color="cyan")
ylim(0,500)
xlim(0,2200)
xlabel('Time (ms)')
ylabel('Spike ')

#Spike for Selective pool S2
figure()
title('Spike for selective pool S2')
plot(M_S2.t[0:45829]/ms, M_S2.i+500, '|', color="cyan")
ylim(500,1000)
xlabel('Time (ms)')
ylabel('Spike ')

#Spike for Inhibitory pool
figure()
title('Spike for Inhibitory pool')
plot(M_Inh.t[0:45829]/ms, M_Inh.i, '|', color="cyan")
ylim(0,250)
xlabel('Time (ms)')
ylabel('Spike ')

**Comment by mstimberg** [comment]
Hi @mareba2030. At least at first glance, this does not look like an issue with Brian itself, but rather a question of setting up your model and choosing parameters. Could you therefore please post your question at the Brian discussion forum (https://brian.discourse.group) instead? The "Science and projects" categories should be a good fit: https://brian.discourse.group/c/science/7 When posting, please enclose your code in triple backticks like this
````
```
from brian2 import *
# your code here
```
````
This way your code is easy to read and copy&paste. Thanks :pray: !
