### ISSUE TITLE
Error in test case 

### ISSUE THREAD

**Issue by abin102** [brian-team/brian2#1554]
Hi, when running the command
`import brian2
brian2.test()`
getting the assertion error.
<img width="1154" alt="assertion_error" src="https://github.com/user-attachments/assets/9931339e-a2e2-4eaf-8b79-cd4c1a2f8032">

**Comment by mstimberg** [comment]
Many thanks for your report. This has now been fixed (in the development version, i.e. not yet in the official release) via #1553.
