### ISSUE TITLE
Brian 2 compilation error on Windows (The "exprel" function needs C99 compiler support)

### ISSUE THREAD

**Issue by Treetalker** [brian-team/brian2#1565]
[brian_script_42vb4f0b.zip](https://github.com/user-attachments/files/17278456/brian_script_42vb4f0b.zip)
Log and py files are attached in the zip file.

**Comment by mstimberg** [comment]
Hi @Treetalker, thanks for your bug report. In the future, please make the information in the title/description more specific. From your log file, the reported error is:

> The "exprel" function needs C99 compiler support

Which seems to indicate that your C++ compiler is very old. You can either switch off C++/Cython code generation by setting
```
from brian2 import *
prefs.codegen.target = "numpy"
```
in the beginning of your script, or you can install a newer compiler, e.g. by following our instructions here: https://brian2.readthedocs.io/en/stable/introduction/install.html#requirements-for-c-code-generation

**Comment by Treetalker** [comment]
Thank you so much. Problems are solved.
