### ISSUE TITLE
Use ufunc.at for improved Synapses efficiency

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#161]
With the release of numpy 1.8 today, there is a new ufunc method ``at`` that allows us to do things like ``x[idx]+=1`` where ``idx`` contains repeated indices. This should allow for huge speed improvements in the pure Python case. The new syntax for the above would be ``add.at(x, idx, 1)``.

To make this work in the general case I guess we will need some sort of ufunc rewriter that takes an expression and rewrites it in terms of a sequence of ufunc ``at`` calls.

We could also backport this to Brian 1.x although I'm not sure if it's worth it.

**Comment by mstimberg** [comment]
We implemented this in #438 (in a more general way and not quite optimal yet, but working alright). I'm therefore closing this issue.
