### ISSUE TITLE
Loop invariant optimisations

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#174]
We should add the ability to perform loop-invariant optimisations since they can potentially make an enormous speed improvement for numpy. As long as we are smart about compiler flags it doesn't make much difference for the others. That means including ``-fno-math-errno``.

As an example, consider the expression that arises in the Jeffress example: ``a*sin(2.0*freq*pi*t) + b + v*exp(-dt/tau) + (-a*sin(2.0*freq*pi*t) - b)*exp(-dt/tau)``, where only ``a`` and ``v`` are arrays. Here's what the numpy-based state updaters are doing at the moment, essentially:

```Python
_v = a*sin(2.0*freq*pi*t) + b + v*exp(-dt/tau) + (-a*sin(2.0*freq*pi*t) - b)*exp(-dt/tau)
v[:] = _v
```

Compare that to this rearranged version to remove the loop invariants in the smartest way I could think of using only numpy:

```Python
_sin_term = sin(2.0*freq*pi*t)
_exp_term = exp(-dt/tau)
_a_term = (_sin_term-_sin_term*_exp_term)
_v = v
_v *= _exp_term
_v += a*_a_term
_v += -b*_exp_term + b
```

Comparing the timings for these against cython and weave (see https://github.com/brian-team/brian2/blob/cython_codegen/dev/ideas/cython_playing_around.py) I get:

```
cython_modified_inline: 0.13
numpy: 3.11
numpy_smart: 0.70
weave_slow: 3.89
weave_fast: 0.14
```

So the 'smart' version of numpy is 4.4x faster than the version we have, and numpy goes from being 24x slower than weave/cython to being only 5x slower. The remaining slowness is probably largely due to the memory bound operations, so trying numexpr seems like a good idea. Dumbly applying numexpr gives a slight speed improvement over numpy but not as much as the smart pure numpy version, but using numexpr on the smart version gives a further speed improvement. Here's the smart numexpr code:

```Python
_sin_term = sin(2.0*freq*pi*t)
_exp_term = exp(-dt/tau)
_a_term = (_sin_term-_sin_term*_exp_term)
_const_term = -b*_exp_term + b
v[:] = numexpr.evaluate('a*_a_term+v*_exp_term+_const_term')
# it would be nice to do this instead, but it gives wrong results, although faster
#numexpr.evaluate('a*_a_term+v*_exp_term+_const_term', out=v)
```

Here are the times:

```
cython_modified_inline: 0.13
numpy: 3.13
numpy_smart: 0.70
numexpr: 1.31
numexpr_smart: 0.45
weave_slow: 3.88
weave_fast: 0.13
```

So now the smart version of numexpr is only 3.4x slower than weave/cython. If you use the ``out=v`` version - which gives wrong results but maybe there is a way to make it work -  then you get it being only 1.5x slower than weave/cython.

So my thoughts on how to implement this:

We already know which variables are arrays and which are values, so we can pull out any subexpressions involving only values and create temporary variables to replace them. We can also group things like ``x*a+x*b`` into ``x*(a+b)`` where ``x`` is an array. We might be able to use sympy to help with this?

**Comment by mstimberg** [comment]
We didn't do all the term rewriting you suggested earlier, but the bulk of this was pulled in via #392, I'll therefore close this issue. See #394, #395, #396 for possible future optimizations, everything else should be a new issue.

**Comment by thesamovar** [comment]
I think everything here was covered in other issues (theano, numba, etc.) except for numexpr, so I made a new issue for that. Now that we have the LIOs numba could make numpy almost as fast as weave so it could be worth putting this optimisation in.
