### ISSUE TITLE
Reuse old names if object no longer exists

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#216]
Creating a new ``NeuronGroup`` (or other object) without specifying the name gives a series of names like ``neurongroup_1``, ``neurongroup_2``, etc. This happens even if the first object is deleted before the second one is created. This is problematic because it leads to unnecessary recompiles of weave code (the name of the group is embedded in the array name).

One thing we might also consider is making weave code not have the name of the group embedded in it, since it's not clear if this is necessary.

**Comment by mstimberg** [comment]
Basically same as before: I think this is important but we shouldn't rush it, moving its milestone again.

**Comment by thesamovar** [comment]
CNS meeting update: relax the unique names, instead insist that (1) names within a Network are unique, checked at run(), and (2) names are unique for a device.build(), checked within Device.
