### ISSUE TITLE
Improved continous integration and build tools

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#288]
I think it would be good to have wider CI support. It's great to have the linux support via Travis, but I think we also want Windows and (ideally) Mac as well, and it seems like there are quite often differences between them. We also want to support 32 and 64 bit builds on each of these platforms.

We should look into possible solutions for this, including paid options.

**Comment by mstimberg** [comment]
Just came across the (new?) https://ci.appveyor.com service which allows free testing on Windows VMs for open source projects. Vispy is using it and the setup seems to be quite straightforward and similar to configuration for travis: https://github.com/vispy/vispy/blob/master/appveyor.yml
@rossant what's your experience for vispy, does it work well?

**Comment by rossant** [comment]
ping @almarklein and @Eric89GXL who have more experience than me on appveyor!

**Comment by thesamovar** [comment]
This looks like a great idea!

**Comment by thesamovar** [comment]
If only there was an equivalent for Mac too.

**Comment by Eric89GXL** [comment]
I'm using AppVeyor on several repos (vispy, mne-python, expyfun) and it has been working well. At one point I tried to get Hosted-CI (OSX) working for vispy and mne-python, and it wasn't viable for either (too slow).

**Comment by mstimberg** [comment]
Many thanks @Eric89GXL, I think we'll go for it then -- the setup looks really similar to travis so it should be straightforward.

**Comment by thesamovar** [comment]
@rossant perhaps we should be using this for klustasuite too?

**Comment by mstimberg** [comment]
I'll have a go at this right now (for Brian, not for klustasuite :) ), it would be great to have this rather sooner than later.

**Comment by rossant** [comment]
@thesamovar yes good idea, let me add an issue

**Comment by mstimberg** [comment]
I just realized that this bug is still open... We now have 32bit and 64bit testing on Linux (travis) and Windows (appveyor), as well as 64bit testing on OS-X (travis) so there is nothing left to do here.

**Comment by thesamovar** [comment]
Satisfying!
