### ISSUE TITLE
Synapse indexes

### ISSUE THREAD

**Issue by guillaumeBellec** [brian-team/brian2#297]
Hi every one,
First issue on brian2's github for me. Big day.

Synapses some-times behave like a matrix, sometimes like a one dimensional vector and it's misleading I think. For instance, in the following S.w in length 20 but one can't access a particular set of synapses like [1,2,3].
Using S._post_synapse_idx, I expected to select the pre-synaptic neurons of let's say output neuron 0. However S.w[:,0] finally made the job fine.

Minimal example:
```
from brian2 import *

Ninputs = 3
Noutputs = 4

G_pre = NeuronGroup(Ninputs, '''v : volt''')
G_post = NeuronGroup(Noutputs, '''dv/dt = - v  / taum : volt''')
S = Synapses(G_pre, G_post, model= ''' w: 1''',pre = "v_post += w * w_pre",connect=True)

print len(S.w)
print S.w[[1,2,3]]
print len(S.w[[1]]),len(S.w[[1,2]]),len(S.w[[1,2,3]])
``` 

Returns:
12
[ 0.  0.  0.  0.  0.  0.  0.  0.]
4 8 8

**Comment by mstimberg** [comment]
Just realized this issue was still open, closing it now.
