### ISSUE TITLE
Images in automatically generated examples documentation

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#340]
See discussion near https://github.com/brian-team/brian2/pull/328#issuecomment-58352608.

The plan is to use git submodules to store the images.

We should also run and generate the tutorials, see #413.

**Comment by thesamovar** [comment]
I wrote some code to do this via scripts although it's not used by readthedocs.org and it uses a dropbox folder. We should probably use briansimulator.org or github to store the images instead, and move the downloading code into conf.py.

**Comment by thesamovar** [comment]
For tutorials (which are ipython notebooks) note that when you run the tutorial if a cell raises an exception it stops running the rest of the notebook. We need a way round that because part of the tutorial is showing what the exceptions look like.

**Comment by mstimberg** [comment]
If we use the `runipy` script I mentioned in #413, it has an option to continue running after an exception (`--skip-exceptions`)

**Comment by thesamovar** [comment]
I think this is all done now, so closing.
