### ISSUE TITLE
Tracebacks should point to where the problem is

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#376]
For example, if the problem is with some equations, it should point to the line where the string is written, if known, or at least where the ``NeuronGroup`` is defined. We can do this by inspecting source lines of the call stack when instantiating objects (but obviously fail gracefully).

Also, for weave we can put line number references in (search for #line): http://docs.scipy.org/doc/scipy-0.14.0/reference/tutorial/weave.html

**Comment by thesamovar** [comment]
Could store the information in ``BrianObject.__init__`` and then later request it from ``owner.something``.

**Comment by mstimberg** [comment]
I think we can consider this closed per #586 -- or do you want to keep it open for the weave line numbers?

**Comment by thesamovar** [comment]
Happy to close I think.
