### ISSUE TITLE
Automatically chose a codegen target (and tell the user about it)

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#379]
Currently, we default to the `numpy` codegen target. Some users might therefore not benefit from the acceleration of `weave`/`cython` even though they could.

Instead, we could try to chose (at import time) a code generation target for the user if they did not declare one explicitly. We'd emit an "info" (which should soon be the default log level) about it, telling the user which codegen target was chosen.

**Comment by thesamovar** [comment]
This seems like a good idea to me. One issue is whether or not there is a fast way to check if a codegen target is available. Seems like the only way to be sure (for Windows users) would be to try compiling something and see if it worked: but this might add a considerable amount of time to the initial import time?

**Comment by mstimberg** [comment]
Maybe we could do it like this:
* a possible value for `prefs.codegen.target` is `auto`
* Whenever code is generated for the first time (i.e. not at import, but at the first `before_run`) and the code generation target is set to `auto`, we determine the best target (`weave` > `cython` ?). This is stored somewhere in the codegen module, so it is only done once per process
* We log on the info level that we are automatically determining a codegen target and tell the user to set it explicitly if they don't want that (this kind of requires that we increase the default log level to info)

This way, if it adds a significant delay to the process the user will know why and can do something about it.

**Comment by thesamovar** [comment]
Actually how about we just write it to the user preference file the first time we determine it? We could have two prefs: ``prefs.codegen.target = 'auto'`` and ``prefs.codegen.auto_target = ...`` which gets filled in the first time it is run with target=auto? We still warn each time you run with auto but it doesn't take any longer to do so.

**Comment by mstimberg** [comment]
It depends a bit on how long this determination takes. If it is just 2 seconds or so, I'd say if it is fine if it is repeated with every new script you run. It has the advantage that you don't have to dig around and change something in a configuration file just because you installed cython after you first ran Brian or something like that. Actually, putting it in the user preferences at the first run would be equivalent to a determination at installation time (if the user installs Brian in the first place...), wouldn't it?

**Comment by thesamovar** [comment]
OK true: let's see how long it takes.
