### ISSUE TITLE
Try to import weave before scipy.weave

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#386]
Weave is now deprecated in the latest scipy 1.5 so we should do something like:

```
try:
   import weave
except ImportError:
  try:
    from scipy import weave
  except ImportError:
    weave = None
```

**Comment by thesamovar** [comment]
Oh, further explanation probably needed: weave is now being packaged separately from scipy.

**Comment by mstimberg** [comment]
The import part is easy, but how do we specify it as an dependency in `setup.py`? If we add it explicitly, then it will be installed even if someone already has weave. It would be nice if setuptools supported some more complex dependency definitions, something like in Linux packaging formats where we could define `scipy >= 0.7, scipy < 0.15 | weave`. 

Hmm, I guess installing a potentially unneeded weave package is the way to go? It's a quite small package so it should be ok.

**Comment by thesamovar** [comment]
Perhaps we should just ignore scipy.weave and always use the separate weave package?

**Comment by mstimberg** [comment]
> Perhaps we should just ignore scipy.weave and always use the separate weave package?

Ok, why not. For now, I'd still have something like this to prevent that Brian stops working after an update:
```Python
try:
   import weave
except ImportError:
  try:    
    from scipy import weave
    warnings.warn(DeprectationWarning('Using weave from scipy.weave, in the future only the '
                                      'separately installed weave package will be used.')
  except ImportError:
    weave = None
```

Oh and actually, I'll start working on moving the remaining pure python bits in `SpatialNeuron` to templates/C code soon. After this is done, we are not using scipy anywhere anymore so we can stop depending on it.
