### ISSUE TITLE
Raise a warning when a new attribute is stored in a group

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#393]
A common mistake is to set a non-existing (e.g. misspelled) state variable on a group. If this is done without any indexing, it will create a new attribute and set this. This can be very confusing for the user. Since there are situations where it is convenient to attach arbitrary attributes to a group, it's probably best to not raise an error but just a warning. For bonus points, we could present the user a best guess of the form "did you intend to set XXX instead?".

**Comment by thesamovar** [comment]
I have mixed feelings about this one. It feels like it might add quite a lot of noise that you will be required to filter out. But on the other hand, it is a very persistent source of errors.

A possible middle path: how about we only raise a warning if the new attribute is below a threshold of similarity to an existing one (using e.g. http://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance)?

**Comment by mstimberg** [comment]
> It feels like it might add quite a lot of noise that you will be required to filter out.

Do you use this feature in your simulations? The only use case I remember was to pull out objects of a `Network` in Brian 1, where it was useful to attach some identifier. Obviously we don't need this anymore now that every object has a name. If you have a good use case in mind, then we should certainly allow it, though. Actually, I can think of two solutions that I would be happy with, in both cases raising an *error* instead of a warning for setting an unknown attribute:
* have an explicit `add_attribute` method that you can call (and that is mentioned in the error message). It would create the attribute and set it to `None`, you could then use it to store whatever you want
* have a standard `metadata` attribute in every group, an object that you can access with both attribute and dict syntax and where you can store arbitrary additional information.

> A possible middle path: how about we only raise a warning if the new attribute is below a threshold of similarity to an existing one (using e.g. http://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance)?

For me this is a bit too "magic". More importantly, it wouldn't cover the situation where you change a model and by accident remove a parameter or differential equation from the equation string.

**Comment by thesamovar** [comment]
Yes, you're right about that idea being too magic.

In the past I've used new attributes in a group a lot but I don't feel that it's a must-have feature. It's probably bad programming style anyway. I would say probably the ``metadata`` attribute is not worth having (although I'm also not opposed to it if you want), and that the ``add_attribute`` would be good. I might also add that it would be good to have a pair of methods to switch attribute checking on and off. This will be useful in our own code so that we don't have to explicitly add every attribute, and also when doing something like deriving from a ``NeuronGroup`` (even though we don't do that so much any more).

**Comment by mstimberg** [comment]
> I might also add that it would be good to have a pair of methods to switch attribute checking on and off.

I'm not sure we necessarily need this, the check will only happen after `_enable_group_attributes` has been called, and this is normally at the end of `__init__`.

**Comment by mstimberg** [comment]
Actually, yet another solution: we don't do a check for attribute names starting with an underscore (no state variable defined by the user can have such a name), so all you have to do to store arbitrary attributes in an object is to start its name with an underscore. What do you think about that?

**Comment by mstimberg** [comment]
Ok, yet another proposition: do both :) I'll upload a branch soon where 1) names starting with `_` are not checked, i.e. will directly generate a new attribute if you assign to it and it doesn't exist 2) there's an `add_attribute` method that allows you to add new attributes.

Do you think we'll still need a mechanism to switch the checks off in this case? With some small changes (mostly moving the `_enable_group_attributes` all to the end of `__init__` in a few places), no error is raised anywhere in our code, i.e. we never have to call `add_attribute`.

**Comment by thesamovar** [comment]
Not checking ``_`` names is a very good idea. I think an attribute/method to enable/disable checking would be straightforward and potentially useful, but you're right that we might not need to use it.

**Comment by mstimberg** [comment]
I have to make a qualification to my above statement, we do actually need to call `add_attribute` once in `SpatialNeuron` for `diffusion_state_updater` (which should be public for consistency with `state_updater`, `thresholder`, etc.). But still in this case using `add_attribute` once is shorter than switching attribute checking on and off. Maybe let's stick with this for now and add another mechanism if we encounter a need for it? As you say, it's trivial to implement but I'm a bit hesitant to add something to a very basic class if it's not a strong necessity.

**Comment by mstimberg** [comment]
I implemented all that in the `unknown_attributes` branch and added a little spell checker suggestion. The latter is very simple for now, e.g. if you type `V` instead of `v`, it would also suggest all other one-letter variable names but it should already be quite useful for a typo like `delays` instead of `delay`. I'll open a pull request for the branch.
