### ISSUE TITLE
loop-invariant optimisation can turn integer expressions into floats

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#400]
When the loop-invariant optimisation pulls out constant expressions, it uses the standard dtype for those constants (i.e. a float). This will lead to bugs (in C) if the code uses an operation that is only defined for integers such as the modulo operator:
```Python
from brian2 import *
prefs.codegen.target = 'weave'
G = NeuronGroup(4, '''a : integer''',
                threshold='True',
                reset='a += i%(2*N)'  # 2*N will be pulled out
                )
run(defaultclock.dt)
```

Will lead to
```
[...]CompileError: error: Command "c++ -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -fPIC -I/usr/include -I/home/marcel/.local/lib/python2.7/site-packages/scipy/weave -I/home/marcel/.local/lib/python2.7/site-packages/scipy/weave/scxx -I/home/marcel/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c /home/marcel/.cache/scipy/python27_compiled/sc_8e5301c5898c4a29b6a1650eadee6f641.cpp -o /tmp/scipy-marcel-sHtBfu/python27_intermediate/compiler_ede35212078c0beff706e86697d62e7e/home/marcel/.cache/scipy/python27_compiled/sc_8e5301c5898c4a29b6a1650eadee6f641.o -w -O3" failed with exit status 1
/home/marcel/.cache/scipy/python27_compiled/sc_8e5301c5898c4a29b6a1650eadee6f641.cpp: In function ‘PyObject* compiled_func(PyObject*, PyObject*)’:
/home/marcel/.cache/scipy/python27_compiled/sc_8e5301c5898c4a29b6a1650eadee6f641.cpp:754:26: error: invalid operands of types ‘const int’ and ‘const double’ to binary ‘operator%’
                 a += i % _lio_const_1;
                          ^
/home/marcel/.cache/scipy/python27_compiled/sc_8e5301c5898c4a29b6a1650eadee6f641.cpp: In function ‘PyObject* compiled_func(PyObject*, PyObject*)’:
/home/marcel/.cache/scipy/python27_compiled/sc_8e5301c5898c4a29b6a1650eadee6f641.cpp:754:26: error: invalid operands of types ‘const int’ and ‘const double’ to binary ‘operator%’
                 a += i % _lio_const_1;
```

**Comment by thesamovar** [comment]
Quick fix: no LIO when there is an int in the subexpression? Maybe this is good enough?

**Comment by thesamovar** [comment]
A deeper solution would be type inference, but I'm not sure we want to go down that route?

**Comment by mstimberg** [comment]
Yeah, I don't think it is worth it... We ignore literals in the check, right? Otherwise whenever we have a `2 * `, we'd not pull it out. I can't think of any expression where literals make the difference. Oh, and I realized that we have the same issue with booleans.

**Comment by thesamovar** [comment]
I think we pull out literals too, so you do get things like ``2*x`` pulled out. I think we probably want that behaviour though, right? Perhaps this complicated this issue though.

**Comment by mstimberg** [comment]
No, that's fine. What I meant is that if the expression is `i * x` we'd not pull it out (because there is an integer in it and we won't bother with full type inference) but if the expression is `2 * x`, we still pull it out, you don't necessarily have to write `2.0 * x`.

**Comment by thesamovar** [comment]
Yes, I agree. Is there any danger in that? For example, if there was ``2*3*i`` might it pull out ``double c=2*3`` and then use ``c*i`` later?

**Comment by mstimberg** [comment]
That's what I wondered but I thought that since we pass things through sympy, expressions like this would be optimized away. But I now realized that this will be only the case for equations, not for statements. So there the situation you describe could in fact occur. So I guess we rather err on the side of caution and don't pull out `2 * x`? It shouldn't occur very often anyway.

**Comment by thesamovar** [comment]
"It shouldn't occur very often" is the sort of phrase that comes back to bite you. :)

I think you're right that making int literals (and presumably bool literals) unable to be pulled out would solve the problem, so it's probably a good stopgap measure. I wonder if we could write down what we'd like with an ideal solution though? To see if we can do better.

I'm wondering if we'll actually need to be clearer about type inference. What does ``i/N`` mean in abstract code for example? Is it integer or float? I don't remember what we decided and I'm not sure what is the best option. I'm not sure there is a "least surprising" option there.

**Comment by thesamovar** [comment]
How about e.g. ``exp(-(x-mu)**2/(2*sigma**2))``? Under the new rule this couldn't be pulled out, right?

**Comment by thesamovar** [comment]
We could do some minimal amount of type inference. For example, we know the type of some variables, and the type of literals, and we can always assume that ``float op int`` will be ``float`` for any operator op so we can pull out expressions as long as we know that they are float. Functions is still tricky though. For example ``int(x)`` returns an int and in general we don't know what the return type of a function is.

**Comment by thesamovar** [comment]
Actually the type inference for functions might not be too bad. We just specify for each function that the return type is one of int, float, bool, same or unknown (by default). "Same" means that it returns the same type as its argument (what do we do for functions with more than one argument?) and for "unknown" we never pull them out.

**Comment by mstimberg** [comment]
Maybe we should be explicit about the return type? An ideal solution would be to 1) do type inference and 2) give pulled out constants the appropriate type, i.e. not always float.

How about a very conservative short-term solution (because we are currently breaking some scripts) where indeed we are not pulling out expressions like the one you quoted and then we work on a better solution.

**Comment by thesamovar** [comment]
Yes, agree on conservative short-term solution. Do you want to open a new issue for the type inference?

**Comment by mstimberg** [comment]
The new issue is #402.

I did not reply to this yet:
> I'm wondering if we'll actually need to be clearer about type inference. What does `i/N` mean in abstract code for example? Is it integer or float? I don't remember what we decided and I'm not sure what is the best option. I'm not sure there is a "least surprising" option there.

`i/N` will currently do integer division, because both variables are integers. We discussed using the Python 3 convention instead (i.e. use `//` for integer division), this might be a good idea in the long term. But since the current solution is consistent with Python 2 and C usage, I think it is ok for now.
