### ISSUE TITLE
Add `before_` and `after_` slots to the schedule

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#426]
In Brian 1, there were slots like `after_thresholds` and I think they are more convenient than writing `when='thresholds', order=1` for example. A good solution would be to not include them in `Network.schedule` (i.e. this would still just be `['start', 'groups', ...]`) but instead automatically add the `before_` and `after_` slots when sorting the objects in a network. This way, one can also conveniently add new slots to the schedule (e.g. for custom operations) and then use `before_`, `after_` relative to them.

**Comment by thesamovar** [comment]
Excellent idea!
