### ISSUE TITLE
Use appveyor to build binary installers for Windows

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#427]
Using appveyor, it should be pretty straightforward to build binary installers for Windows:
https://packaging.python.org/en/latest/appveyor.html

Similarly, we can build conda packages (but then we should do the same for Linux on travis obviously):
https://github.com/rmcgibbo/python-appveyor-conda-example

**Comment by thesamovar** [comment]
Maybe we should make this a high priority for 2.0?
