### ISSUE TITLE
Make `PopulationRateMonitor` more useful

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#430]
Currently, `PopulationRateMonitor` records the population rate per time bin. This is rarely what users want, e.g. plotting it won't give a smooth PSTH. There are two things to do:

- [ ] allow for binning during the run (which will save memory, even though a single value for a population per time step should not be really of any relevance)
- [ ] have a convenient binning/smoothing option. For this, we could simply convert the `smooth_rate` function from Brian1: https://github.com/brian-team/brian/blob/master/brian/monitor.py#L634

The second part should be trivial, we should do this rather sooner than later, I guess.

**Comment by thesamovar** [comment]
Do we really need the first part? As you say, it doesn't take much memory and we can do this afterwards quite easily.

**Comment by mstimberg** [comment]
Yeah, I'd be happy to not bother and rather focus on a nice smoothing function.
