### ISSUE TITLE
Reduce Python overhead

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#447]
At the moment Brian 2 is slower than Brian 1 for some small networks because the amount of Python overhead is larger. We could probably reduce this by pushing some stuff that is in functions into ``Network.run``.

Are there any possible side effects of this?

Are there any other places we could reduce overhead?

**Comment by thesamovar** [comment]
What I mean is that ``Network.run`` calls ``BrianObject.run`` which loops through ``BrianObject._code_objects`` calling ``CodeObject.__call__()`` on each one, which calls ``CodeObject.update_namespace()``, updates the namespace dict, and then calls ``CodeObject.run()`` which is then specific to each target. So we could collapse all of this into ``Network.run``.

**Comment by thesamovar** [comment]
This specific optimisation in ``Network.run`` doesn't save much, but once you start doing several it really adds up. On a run that started at 33s I got it down to 19s with the following optimisations, not all of which fully generalise but it's suggestive:

* 5-6s saved by removing the call to ``update_namespace`` which wasn't necessary in this particular case. I suspect most of this is in the call to ``DynamicArrayVariable.get_value()`` which in turn calls ``Device.get_value()`` which does an ``isinstance`` check and a dictionary lookup and attribute get.
* 2s saved by inlining ``BrianObject.run`` and ``CodeObject.__call__`` in ``Network.run``
* 4-5s saved by adding two checks, an ``if len(_spiking_synapses)`` around the whole synapses propagation code, and an ``if spikespace[-1]`` around the whole reset code
* 1-2s saved by removing clock code from ``Network.run`` in the case of a single clock network, and inlining ``Clock.tick`` and ``Clock.running``.

OK so I don't know if we can learn much from this other than that Python overheads add up, but it's something we should, at some point, work on.

In any case, we should certainly add the if checks in synapses and reset because that's easy to do and gives quite a speed improvement.

**Comment by mstimberg** [comment]
What example did you use for testing this? There might be some variables included in the non-constant variables that are updated every time step using `update_namespace` which don't need to be updated, this might be easy to fix. I'm not sure about inlining too much, since this means we are losing some options to overwrite the complete `BrianObject.run` call. We should certainly have checks for no spikes in the propagation/reset code, I though we had those already, but in fact it might have been one of the optimisations I added to Brian 1 a long time ago...

Did your runtime go down from 33s to 19s for the numpy or the weave target?

**Comment by thesamovar** [comment]
I was using the example from this thread; https://groups.google.com/forum/#!topic/briansupport/UZ7nMQyOj4Y (with the monitors removed). I think there were indeed some variables in the nonconstant list that were being updated but didn't need to be.

That was with the numpy target (for a better comparison with Brian 1), although I think that didn't change anything because the actual time spent executing the code was fairly minimal.

I agree with what you say. One way we could potentially get some speed improvements here would be to dynamically generate the code for the ``Network.run()`` loop that automatically inlines some code if it can be done safely, etc. Not sure if it is worth it or not. But optimising ``update_namespace`` and adding the checks for spikes in prop/reset code seems like low hanging fruit.

**Comment by mstimberg** [comment]
Ok, I'll look into this, but I don't think it has to be a high priority for now, there are other things more urgent.

From my point of view I'd say:
* inlining code in Network.run() is probably not worth the additional complication
* optimisation/simplification for a single `Clock` might be worth doing
* improving `update_namespace` and adding a spike check for reset/propagation should be the first/easiest thing to do

**Comment by thesamovar** [comment]
Agreed.

**Comment by damiendr** [comment]
I'm not entirely familiar with what's inside run(), but it seems to me that there's massive overhead indeed.
I have here a small, fully-connected network of 128 neurons + 64 input neurons (dt=1 ms) with some non-trivial state updates running on a slower clock (dt=50 ms).

In[ ]: 
```python
net._sort_objects()
net.objects
```
Out[ ]:
```
[NeuronGroup(clock=Clock spike: t = 0. s, dt = 1. ms, when=start, order=0, name='e_cells'),
 Synapses(clock=Clock spike: t = 0. s, dt = 1. ms, when=start, order=0, name='ee_synapses'),
 NeuronGroup(clock=Clock learn: t = 0. s, dt = 50. ms, when=start, order=0, name='input_cells'),
 NeuronGroup(clock=Clock defaultclock: t = 0. s, (new) dt = 1. ms, when=start, order=0, name='input_dendrite'),
 Synapses(clock=Clock learn: t = 0. s, dt = 50. ms, when=start, order=0, name='input_synapses'),
 CodeRunner(clock=Clock learn: t = 0. s, dt = 50. ms, when=before_learn, order=0, name='spikecount_e_cells'),
 CodeRunner(clock=Clock learn: t = 0. s, dt = 50. ms, when=before_learn, order=0, name='spikecount_input_cells'),
 CodeRunner(clock=Clock learn: t = 0. s, dt = 50. ms, when=learn, order=-1, name='meta_input_dendrite'),
 CodeRunner(clock=Clock learn: t = 0. s, dt = 50. ms, when=learn, order=0, name='learn_ee_synapses'),
 CodeRunner(clock=Clock learn: t = 0. s, dt = 50. ms, when=learn, order=0, name='learn_input_synapses'),
 CodeRunner(clock=Clock learn: t = 0. s, dt = 50. ms, when=before_input, order=0, name='patterns_input_cells'),
 StateUpdater(clock=Clock learn: t = 0. s, dt = 50. ms, when=input, order=0, name='input_cells_stateupdater'),
 SummedVariableUpdater(clock=Clock learn: t = 0. s, dt = 50. ms, when=after_input, order=-1, name='input_synapses_summed_variable_g_syn_post'),
 CodeRunner(clock=Clock learn: t = 0. s, dt = 50. ms, when=dendrites, order=0, name='integrate_input_dendrite'),
 StateUpdater(clock=Clock spike: t = 0. s, dt = 1. ms, when=groups, order=0, name='e_cells_stateupdater'),
 StateUpdater(clock=Clock defaultclock: t = 0. s, (new) dt = 1. ms, when=groups, order=0, name='input_dendrite_stateupdater'),
 Thresholder(clock=Clock spike: t = 0. s, dt = 1. ms, when=thresholds, order=0, name='e_cells_thresholder'),
 SynapticPathway(clock=Clock spike: t = 0. s, dt = 1. ms, when=synapses, order=-1, name='ee_synapses_pre'),
 Resetter(clock=Clock spike: t = 0. s, dt = 1. ms, when=resets, order=0, name='e_cells_resetter'),
 <SpikeMonitor, recording spikemonitor>,
 <StateMonitor, recording ['ys'] from input_cells>,
 <StateMonitor, recording ('g_nmda', 'g_syn', 'k_syn', 'ys', 'h_ltp', 'h_ltd') from input_dendrite>,
 <StateMonitor, recording ('u', 'ys', 'yl', 'I', 'gi') from e_cells>]
```

Runtime for 500,000 timesteps, including compilation:
weave: 120 seconds
standalone_cpp: 12 seconds

I'm a bit shocked by the 1,000 % overhead here.

The very possibility of standalone_mode seems to indicate that most of the overhead could in theory be (re)moved into compiled code, even when *not* using standalone mode, couldn't it?
Then even if there's a python network_operation in the middle of the list of updates, that should ideally be only three objects to update per loop (before network_operation, nework_operation, after_network_operation) instead of 23.

**Comment by thesamovar** [comment]
We can't fix this problem, which is why we're thinking about alternatives. One of these is standalone mode, and we also have in mind a variant on standalone mode where instead of generating a project that is run entirely separately, you generate a Python package for your particular model that can be called, run and so forth from Python. https://github.com/brian-team/brian2/issues/251 Hopefully this will cover the cases not covered by the existing modes.

Also worth mentioning that the overheads are much smaller relatively speaking for large networks (since the Python overheads are fixed relative to the number of objects, not the number of neurons/synapses).

**Comment by thesamovar** [comment]
CNS meeting update: this is still important for 2.0, but will probably largely be subsumed in other changes we're making.

**Comment by thesamovar** [comment]
This is done now.
