### ISSUE TITLE
Problem calculating weight 

### ISSUE THREAD

**Issue by ManuNeuro** [brian-team/brian2#450]
Hello !

Firstly, I would thank you for your potential help !

I'm a french student, I'm pretty new on Github and Brian2, I got a problem and saw all the tuto that was available on the internet, and I'm still stuck on it...

So, the problem is : 

I have an image, and I want to use neurons group to do the segmentation...

# So, I created a grid of neurons like this : 
G = NeuronGroup(rows * cols, '''x : 1
                                y : 1''',eqs ,threshold= 'v > 5*mV', reset = 'v = 0*mV')

# Then, initialize the grid positions
G.x = 'int((i / rows) * grid_dist) '
G.y = 'int((i % rows) * grid_dist) '

# Here is my synaptic connections : 
distance = 2
S = Synapses(G, G,'w : volt',pre = 'v+=w')
S.connect('sqrt((x_pre - x_post)**2 + (y_pre - y_post)**2) < distance')
(I wanted all the neurons to be connected with his neighbors)

Now, I want to create the weight associated with my synapse connections, using the following formula : 
w_max*(1-(1/(1+math.exp(-alpha))*(abs( image(i)) - image(j) +delta)))

What I want, is to access to the pixel associated to the neuron at index 'i', and the same for 'j'

But when I do this : 
S.w = "w_max*(1-(1/(1+math.exp(-alpha))*(abs( image(i)) - image(j) +delta)))"
it doesn't work, because the compiler can't access to an array, he needs scalar value.

So, I know that i could use a double "for" loop to calculate the weight, but i'll have to set up all the conditions at the border of the picture... 

How tu use the easy computing of Brian ? I don't want to program like a 'c' program... 

What I tried is to use the "image" as a class, with the attribute "pixel", which can be access through 'index'
class onbjet_img:
    """Classe enveloppe d'un dictionnaire"""
    def __init__(self):
        """Notre classe n'accepte aucun parametre"""
        self.pixel = {}
    def __getitem__(self, index):
        """Cette methode speciale est appelee quand on fait objet[index]
        Elle redirige vers self._dictionnaire[index]"""
        
        return self.pixel[index]
    def __setitem__(self, index, valeur):
        """Cette methode est appelee quand on ecrit objet[index] = valeur
        On redirige vers self._dictionnaire[index] = valeur"""
        
        self.pixel[index] = valeur
    
#Creation de l'objet image

img = objet_img()

for i in xrange(len(image)):
    img[i] = image[i]

So iI wanted to use a function which can give me the possibility to have a direct access to the scalar values
def accede_pixel(index):
    return img.pixel[index]

I wanted to use this ineasted : 
S.w = "w_max*(1-(1/(1+math.exp(-alpha))*(abs( accede_pixel(i)) - accede_pixel(j) +delta)))"
But it doesn't work anyhow...

=> 'The identifier "accede_pixel" could not be resolved.'

So if someone could help me, it would be really appreciated :) I'm working on it since... I don't remember, i'm becoming crasy ! ahah

**Comment by thesamovar** [comment]
Hi,

Could you post this to our email list for brian2?

https://groups.google.com/forum/#!forum/brian-development
