### ISSUE TITLE
Allow subexpressions to have the flag "unless refractory"

### ISSUE THREAD

**Issue by dabliss** [brian-team/brian2#473]
This is a feature request.  I'd like to record the total current into my neurons as

    I_total = I_gaba + I_L + I_nmda + I_ampa + I_app + I_ext + I_other : amp (unless refractory)

Are there reasons this shouldn't be allowed?  If not, I'm happy to start working on it, though I'm guessing achieving this will be pretty complicated.

Alternatively, because I have `dv / dt` defined as follows

    dv / dt = (I_gaba + I_L + I_nmda + I_ampa + I_app + I_ext + I_other) / C_m : volt (unless refractory)
    
another way to achieve the value for `I_total` I want would be to be able to have

    I_total = dv / dt * C_m

(i.e., to allow derivatives to appear on the RHS of equations).

**Comment by thesamovar** [comment]
What does it mean? Is it 0 when refractory?

**Comment by dabliss** [comment]
Yeah, it would apply the normal effect of "(unless refractory)": making the variable 0 when refractory.

**Comment by thesamovar** [comment]
Just multiply by not_refractory. @mstimberg do you think it's worth extending the syntax to allow this?

**Comment by dabliss** [comment]
Whoops, overlooked that option.  I'll close this.
