### ISSUE TITLE
Changing dt's between runs does not currently work in standalone

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#478]
In runtime mode, this code
```Python
from brian2 import *
G = NeuronGroup(1, 'v:1')
mon = StateMonitor(G, 'v', record=True)
run(1*ms)
defaultclock.dt = 1*ms
run(3*ms)
print mon.t
```
correctly prints:
```
<statemonitor.t: array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        2. ,  3. ]) * msecond>
```

whereas in standalone mode it prints
```
<statemonitor.t: array([ 0.,  1.,  2.,  3.]) * msecond>
```
i.e. the last `dt` is used for the full simulation.

**Comment by mstimberg** [comment]
I had a look at this and I don't see a quick and easy fix. I wonder whether it wouldn't be a good time for a major refactoring of the `Clock` object, making it more similar to a standard group (i.e. `t` and `dt` would be stored as other scalar variables), getting rid of `AttributeVariable` and so on... This could take care of #389 as well then. It would mean some small change to the templates, though, something like
```C++
const double t = {t}[0];
```
in the beginning. This is a bit ugly but on the other hand it would get rid of the need to pass in `t` to the namespace at every time step in runtime mode, which involves going through quite a bit of Python machinery.

**Comment by thesamovar** [comment]
So when you set ``defaultclock.dt`` it creates a code object to do that and then it gets inserted into the sequence and is correctly handled, is that right? I'd certainly be happy to refactor Clock to make this sort of thing more flexible. Is there any way we could make scalar variables be handled automatically so we don't have to explicitly write things like ``t = {t}[0]``? i.e. we would just say at the top that it uses the variable t, Brian would know that it was a scalar variable and would generate the ``t={t}[0]`` line automatically? Not sure if it's worth the effort or not.

**Comment by mstimberg** [comment]
> So when you set defaultclock.dt it creates a code object to do that and then it gets inserted into the sequence and is correctly handled, is that right?

Not necessarily a code object, it would rather be directly included in the `main()` function -- the same way as for other variables (if they don't use string indexing/string expressions).

> Is there any way we could make scalar variables be handled automatically so we don't have to explicitly write things like t = {t}[0]?

I guess we could handle this a bit more automatically, let's look into this when we do the refactoring.

**Comment by thesamovar** [comment]
CNS meeting update: we will do this for 2.0, and it will be included as part of a general refactoring of standalone to allow for, e.g. changing parameters without recompiling.
