### ISSUE TITLE
Bug in Morphology.set_length

### ISSUE THREAD

**Issue by romainbrette** [brian-team/brian2#493]
It seems that it calculates the total length instead the length of each compartment. There is a difficulty however, which is that from n compartments and their coordinates one can only deduce n-1 lengths. To deal with it properly requires looking at parent and children - requires some thought.

**Comment by mstimberg** [comment]
After the refactoring of the `Morphology` class, there is no `set_length` method anymore, length calculation in general should be correct now. Fixed via #652 .
