### ISSUE TITLE
Bug in swc import

### ISSUE THREAD

**Issue by romainbrette** [brian-team/brian2#494]
It's maybe not exactly a bug but perhaps a missing feature: importing swc files is not possible when the soma is made of several compartments, because soma is modelled as a sphere in Morphology. Instead one would need to model the soma as a set of cylinders. In addition, in those cases the soma is not necessarily the root of the tree (reconstruction can start from a dendrite end). It requires a little bit of care.

**Comment by mstimberg** [comment]
This should have been dealt with in #652 .
