### ISSUE TITLE
PyNN integration status

### ISSUE THREAD

**Issue by rgerkin** [brian-team/brian2#496]
Is there a roadmap towards PyNN integration for Brian2?

**Comment by thesamovar** [comment]
None of us are actively working on it, but we'd be happy if someone 
wanted to contribute (although it would be a contribution to PyNN rather 
than Brian).

On the other hand, we do have a GSoC student working on NeuroML/NineML 
integration, and perhaps PyNN works with these? (Not sure.)

**Comment by thesamovar** [comment]
Closing because this is a PyNN issue.
