### ISSUE TITLE
Equation strings for built-in neuron types from Brian

### ISSUE THREAD

**Issue by rgerkin** [brian-team/brian2#497]
Since certain useful neuron types (e.g. Izhikevich neuron) that were built-in in Brian1 have been removed in Brian 2 in favor of the requirement for explicit equation strings, it would be useful (for those getting started) to have those strings documented in tutorials.  For example, the Brian2 implementation of an Izhikevich neuron.  These reference implementations would be useful for those porting code from Brian1 to Brian2, or for those looking to get started quickly.

**Comment by thesamovar** [comment]
Yep, this in the plan (issue #45).
