### ISSUE TITLE
Refactor/re-design Morphology object

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#503]
I had a closer look at the `Morphology` object and I think some major re-design is necessary here. It currently uses an approach where the internal state changes completely after it is used for constructing a `SpatialNeuron` which can be very confusing for the user (e.g. before , all the attributes have units, afterwards they don't). The various ways of constructing morphologies are also not very consistent, e.g. you'd expect the following two things to do the same thing:
```Python
morpho1 = Cylinder(length=10*um, diameter=1*um, n=1)
morpho1.L = Cylinder(length=10*um, diameter=1*um, n=1)
morpho1.LL = Cylinder(length=10*um, diameter=1*um, n=1)

sub_morpho = Cylinder(length=10*um, diameter=1*um, n=1)
sub_morpho.L = Cylinder(length=10*um, diameter=1*um, n=1)
morpho2 = Cylinder(length=10*um, diameter=1*um, n=1)
morpho2.L = sub_morpho
```
The latter does not correctly work, though (it will have an incorrect `distance` attribute in `morpho2.LL`).

This also needs a lot more testing, some features (e.g. the `set_length` method that is currently buggy: #493) are not tested at all.

In general I think the best design would be to not change the `Morphology` object at all but instead to create a new object when it is used in a `SpatialNeuron` object. This needs some thought, though.

**Comment by thesamovar** [comment]
Hey this can be closed now, right?

**Comment by mstimberg** [comment]
> Hey this can be closed now, right?

Yes, definitely. Actually it's not the only issue that was fixed by the morphology branch, I'll close the others as well.
