### ISSUE TITLE
mod doesn't work for integer values

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#509]
With weave code generation, ``i%N`` in a ``NeuronGroup`` confuses the compiler (because it is trying to use ``fmod`` and there is no directly matching signature).

**Comment by thesamovar** [comment]
May be Windows only of course...

**Comment by mstimberg** [comment]
I guess the title should be "does not work for integer values"? `fmod` does indeed work with integer values with my gcc on Linux -- it has something to do with the type-generic math library introduced with C++11, I guess...

**Comment by thesamovar** [comment]
Yes. It actually does work for floating point values. I think you're right about the problem.

**Comment by thesamovar** [comment]
Here is an example of the error in action:

```
c:\users\dgoodman\appdata\local\temp\dgoodman\python27_compiled\sc_34e121a9f1a3026134bf48f399b1b8211.cpp(744) : error C2668: 'fmod' : ambiguous call to overloaded function
        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\math.h(561): could be 'long double fmod(long double,long double)'
        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\math.h(513): or       'float fmod(float,float)'
        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\math.h(120): or       'double fmod(double,double)'
        while trying to match the argument list '(const long, int)'
```
