### ISSUE TITLE
record argument disappeared from SpikeMonitor

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#510]

**Comment by mstimberg** [comment]
Uh, indeed, this must have happened during the recent changes to `SpikeMonitor`. On the other hand, I'm pretty sure we have always ignored this argument in Brian 2...

**Comment by thesamovar** [comment]
Oh really? I think it's a useful one to have (I often use just the count), but if we decide against having it then we should remove it from the docs.
