### ISSUE TITLE
Some pre-synaptic updates give incorrect warnings

### ISSUE THREAD

**Issue by mariomulansky** [brian-team/brian2#524]
I'm using the following simple Synapse:
```
synapses = br2.Synapses(neurons, pre='v -= 0.2')
```
and I get a warning:
```
WARNING  brian2.codegen.generators.base: Came across an abstract code block that is not well-defined: the outcome may depend on the order of execution. 2 lines of abstract code, first line is: "v -= w (in-place)"
```

However, if I make the following trivial change:
```
synapses = br2.Synapses(neurons, pre='v += -0.2')
```
The warning disappears.

**Comment by thesamovar** [comment]
Yes, this is a known limitation at the moment and will be fixed in a future release. As you say though, an easy workaround.

**Comment by mstimberg** [comment]
Actually, since we don't have any other issue for this at the moment, I'll reopen it. It's not the only example of an incorrect warning, the following will generate one as well:
```Python
G = NeuronGroup(1, 'v : 1', threshold='v>1')
S = Synapses(G, G, pre='v_post += v_post')
```

**Comment by thesamovar** [comment]
We will never be able to fix all incorrect warnings though (it's a hard mathematical problem). The best we can do is to cover the most common situations and change the wording of the warning to say that it 'may not be well-defined'. ``v_post+=v_post`` is a particular one in that it is well defined but it won't be possible to efficiently compute the class of all well-defined operations with numpy, and unless we explicitly cover the case ``v_post += v_post`` then this will be one of the cases where it won't be covered. In addition, I don't think it's a common use case, right?

**Comment by thesamovar** [comment]
Also, we were supposed to have fixed this thing with ``-=`` and ``/=`` before but apparently we forgot. Not only that, we even had this same conversation before in #438. ;)

How about we just add ``-=`` and ``/=`` to the list of allowed operators and call that a day?

**Comment by mstimberg** [comment]
The `-=` and `/=` is something we should definitely fix right away, before we forget about it again :)
In general, I'm less and less sure that our warning is useful -- I start to get the impression that we will more often have false warnings than useful ones.
The `v_post += v_post` example was of course contrived, but @btel came across this warning when simulating coupled oscillators, where the phase advance of the post-synaptic neuron depends on its current phase: `v_post += sin(-v_post)`.

**Comment by thesamovar** [comment]
So actually any operation of the form ``postsynaptic_var op f(only postsynaptic vars)`` is well defined I think. Similarly for presynaptic variables. I guess I made a mistake in my logic somewhere not allowing for this.

**Comment by thesamovar** [comment]
I think the warning is good, but yeah it does sound like it needs to be improved. We should definitely change the warning text to 'may not be well defined' though, plus maybe a link to somewhere in the documentation where we explain the issue.

**Comment by mariomulansky** [comment]
From a pure user perspective, I would definitely like to see a more comprehensible warning. In the beginning, I really assumed I was doing something wrong which caused the warning. It took me quite some time to arrive at the workaround and realize this is a problem of Brian. A change in the warning text that represents the fact that it might not necessarily be a real problem in the code would be good.

**Comment by thesamovar** [comment]
OK, so add ``-=`` and ``*=`` and change the warning message for 2.0, but do something more for post-2.0?

For the warning, I tried to find an algebraic condition before, but an alternative is that we just run a few example synapses through it and check that it is order-independent numerically. This might even end up being less numerically expensive than trying to check it algebraically!

**Comment by mstimberg** [comment]
This should now be fixed via #531

**Comment by thesamovar** [comment]
The now merged #531 fixes many but not all of these problems. I think it's enough for 2.0 so I'm removing the milestone from the issue.

**Comment by thesamovar** [comment]
Simulpost!

I'd stay it should still be open because we haven't covered some cases that users might expect to work.

**Comment by mstimberg** [comment]
Simulpost indeed! What is an example that still gives an incorrect warning? If I'm not mistaken, all the examples mentioned in this issue are now part of the test suite and do not raise a warning anymore. If we leave this open, I think we should have at least one example where this is actually an issue.

**Comment by thesamovar** [comment]
I think we didn't handle all (any?) of the cases where you don't use an inplace operator. The following should all work (but I think they don't): ``v=v+w1+w2``, ``v=w1+v+w2``, ``v=w1+w2+v``.

**Comment by mstimberg** [comment]
Statements like those are automatically translated into in-place operations, all of them are `v+=w1+w2` after they are passed through `make_statements`. I tried adding all three of them to the "good examples" list and they all pass.

**Comment by thesamovar** [comment]
Ah OK I thought we hadn't covered all those. In that case, happy to close the issue.

**Comment by mstimberg** [comment]
yay, one issue less :)
