### ISSUE TITLE
Create TORC sounds for reverse correlation?

### ISSUE THREAD

**Issue by choldgraf** [brian-team/brian2#527]
Hey all - I'm not sure if Brian Hears is under active development under Brian 2.0. But in the event that it is, I noticed that there wasn't a function for creating amplitude modulated ripple noise a la:

> Klein, D. J., Depireux, D. a., Simon, J. Z., & Shamma, S. a. (2000). Robust spectrotemporal reverse correlation for the auditory system: Optimizing stimulus design. Journal of Computational Neuroscience, 9(1), 85–111. doi:10.1023/A:1008990412183

This is pretty common in the reverse correlation world, and might be a useful thing to have since I haven't found code that creates these type of stimuli elsewhere in python. An example of the NSL toolbox implementation is here:

https://github.com/tel/NSLtools/blob/master/multimvripfft.m

Would this be something people are interested in? I think at the least a port from the matlab function above would be a decent start...

**Comment by thesamovar** [comment]
Development of Brian Hears for brian2 hasn't been started yet, but will happen as part of this repository: https://github.com/brian-team/brian2hears. Could you put this issue there? That said, I think it's unlikely we'll do this ourselves (although if someone contributes a patch that would be great).

**Comment by choldgraf** [comment]
Can do - I can try to create a python port of the NSL function - need to
check the license on the NSL toolbox though. Would it make more sense to
contribute this to brian hears, rather than brain2hears?

**Comment by thesamovar** [comment]
We won't do any further releases of Brian 1, and Brian Hears for Brian 2 is still a long way off. So my recommendation would be to make your own github repository for it, and we can direct users to it from our webpage and potentially incorporate it into Brian Hears 2 when that comes along.

**Comment by choldgraf** [comment]
Sounds good, will do.
