### ISSUE TITLE
Multi-threading does not improve performance for a code example with plasticity

### ISSUE THREAD

**Issue by vilim** [brian-team/brian2#535]
Taking the Vogels et al. 2011 example and adding:

```python
set_device('cpp_standalone')
prefs.devices.cpp_standalone.openmp_threads = X
```
after importing brian and `device.build` after run, as described in the documentation to use the cpp version with multithreading, X>0 does not improve performance (it even deteriorates for a large number of threads):

X     | runtime/s
--------------- | -------------
0 | 17.66
1 | 18.8
2 | 17. 49
4 | 23.56
8 | 29.25
16 | 63.62

The compiler is gcc 4.9.2 on Debian 4.9.2-10 with the current versions of all required packages, on a 2-processor Xeon E5-2670 v3 configuration with 24 cores.

**Comment by thesamovar** [comment]
Hi, thanks for the report. As stated in the docs, not all networks can benefit from our current (rather simple) OpenMP implementation. It appears this is one of them.
