### ISSUE TITLE
Warn about unstable integration

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#554]
One of the things we see a lot on the support list is people who are seeing weird plots or getting warnings about undefined values and not understanding where they come from. Usually the problem is that the numerical integrator was unstable at that timestep and for those equations. We could actually detect this fairly easily by running a check on the variables once every second or so of simulated time: if we see values larger than 1e100 say, it's most likely due to an instability and we can fire off a warning with a slightly more detailed explanation and suggestions.

**Comment by mstimberg** [comment]
It seems you mentioned this already as part of #499

**Comment by thesamovar** [comment]
Hah, yes. Oops. :)

Actually I wonder if it's worth having a separate issue for it though: #499 will be quite a bit of work whereas this could quickly and easily be done. What do you think? Happy for it to be closed if you think it's not necessary.

**Comment by mstimberg** [comment]
Ok, let's keep them separate. The unstable integration issue is something that can be implemented with a network operation, i.e. it is something that is independent of code generation etc. (except if we want to have working for standalone as well), whereas the indexing checks and so on are quite specific and need to be included in the template.

**Comment by thesamovar** [comment]
The other option is that we do the check only at the end of a run or (for standalone) when variables are loaded from disk. Like this the same code works for both standalone and runtime.
