### ISSUE TITLE
Linear integretation can lead to NaNs when it shouldn't

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#573]
The linear state updater tends to create too complicated statements, and this can lead to divisions by zero. For example, the CUBA equations (ignoring refractoriness for now):
```Python
eqs = Equations('''
dv/dt  = (ge+gi-(v-El))/taum : volt                    
dge/dt = -ge/taue : volt
dgi/dt = -gi/taui : volt
''')
```
are solved like this:
```
print linear(eqs)
_ge = -ge*taue*taum*(-dt/taum + dt/taue)*exp(-dt/taue)/(dt*(taue - taum))
_gi = -gi*taui*taum*(-dt/taum + dt/taui)*exp(-dt/taui)/(dt*(taui - taum))
_v = El - El*exp(-dt/taum) + ge*(-taue*exp(-dt/taum)/(taue - taum) + taue*exp(-dt/taue)/(taue - taum)) + gi*(-taui*exp(-dt/taum)/(taui - taum) + taui*exp(-dt/taui)/(taui - taum)) + v*exp(-dt/taum)
ge = _ge
gi = _gi
v = _v
```

Sympy's `simplify` can rewrite it as:
```
_ge = ge*exp(-dt/taue)
_gi = gi*exp(-dt/taui)
_v = El - El*exp(-dt/taum) + ge*(-taue*exp(-dt/taum)/(taue - taum) + taue*exp(-dt/taue)/(taue - taum)) + gi*(-taui*exp(-dt/taum)/(taui - taum) + taui*exp(-dt/taui)/(taui - taum)) + v*exp(-dt/taum)
ge = _ge
gi = _gi
v = _v
```
But for complicated equations, simplify is too slow and I'm therefore hesitant to use it here (see #384). In the "unsimplified" equations, we see that there is an unnecessary division by `dt*(taue - taum)` which does not enter into the results because it is cancelled by the same factor in the numerator but which can lead to a NaN if `taue == taum`. This might be unlikely, but as noted in #572 the same problem occurs with expressions that include the `is_refractory` variable which of course switches to `0` during refractoriness.

A semi-solution:
* Do not use simplify when checking whether equations can be integrated exactly (because this is called for every equation where `method` is not specified)
* Use it when we decided that we integrate with the `linear` method  -- after all, this will most likely only be the case for relatively simple equations where `simplify` should only take a reasonable amount of time.

**Comment by thesamovar** [comment]
If ``taue==taum`` the differential equation actually has a different solution, right? I don't think we should ignore this case and decide that it's unlikely.

**Comment by mstimberg** [comment]
My explanation was a bit over-simplified. If `taue == taum`, then this is indeed a problem and even the simplified version will still lead to a division by zero in the membrane potential. This did not change. What *did* change is that it will not lead to a division by zero in the solution for `ge` and `gi`. From a mathematical point of view, `ge` and `gi` are completely independent of all other variables, so their solution should not depend on `taum`. With refractory you see the issue more clearly:
```Python
eqs = Equations('''
dv/dt  = (ge+gi-(v-El))/taum : volt (unless refractory)
dge/dt = -ge/taue : volt
dgi/dt = -gi/taui : volt
''')
group = NeuronGroup(1, eqs, refractory=1*ms)
```
Without simplification, this generates the following abstract code for updates:
```
_ge = -ge*taum*(-dt*int(not_refractory)/taum + dt/taue)*exp(-dt/taue)/(dt*(1 - taum/(taue*int(not_refractory)))*int(not_refractory))
_gi = -gi*taum*(-dt*int(not_refractory)/taum + dt/taui)*exp(-dt/taui)/(dt*(1 - taum/(taui*int(not_refractory)))*int(not_refractory))
_v = El - El*exp(-dt*int(not_refractory)/taum) + ge*(-exp(-dt*int(not_refractory)/taum)/(1 - taum/(taue*int(not_refractory))) + exp(-dt/taue)/(1 - taum/(taue*int(not_refractory)))) + gi*(-exp(-dt*int(not_refractory)/taum)/(1 - taum/(taui*int(not_refractory))) + exp(-dt/taui)/(1 - taum/(taui*int(not_refractory)))) + v*exp(-dt*int(not_refractory)/taum)
ge = _ge
gi = _gi
v = _v
```
This looks odd (and at first, I thought there was a bug in the refractory mechanism) because `ge` and `gi` are independent of all other variables and are not marked as `unless refractory`, but still refer to `int(not_refractory)` in their solutions. And during refractoriness, this will lead to a division by zero. With simplifications, this gives something much more reasonable:
```
_ge = ge*exp(-dt/taue)
_gi = gi*exp(-dt/taui)
_v = El - El*exp(-dt*int(not_refractory)/taum) + ge*taue*(-exp(dt/taue) + exp(dt*int(not_refractory)/taum))*int(not_refractory)*exp(-dt*(int(not_refractory)/taum + 1/taue))/(taue*int(not_refractory) - taum) + gi*taui*(-exp(dt/taui) + exp(dt*int(not_refractory)/taum))*int(not_refractory)*exp(-dt*(int(not_refractory)/taum + 1/taui))/(taui*int(not_refractory) - taum) + v*exp(-dt*int(not_refractory)/taum)
ge = _ge
gi = _gi
v = _v
```
The solution for `v` could certainly be simplified further, but the loop-invariant optimisations will pull out a significant part of it, so I don't think it is very inefficient.

**Comment by thesamovar** [comment]
Should this really be closed?

**Comment by mstimberg** [comment]
I think it should, it does not lead to NaNs anymore -- the question whether `simplify` is too slow is a different one (#384). It does not handle special cases, e.g. `taue == taum`, but I don't think we can do anything about it and if it is an essential part of a model, it should be written with a single constant. And of course something like #554 to warn the user about NaNs (instead of just having nothing a plot) would be useful.

**Comment by thesamovar** [comment]
OK, I'm happy to not handle ``taue==taum`` as long as we have a way of warning about NaNs. This should lead people to a page in the docs where we talk about possible reasons for them appearing.

**Comment by thesamovar** [comment]
But I'd also be happy if we could handle ``taue==taum`` cases, but obviously it's going to be hard to do that in the general case. Unless we can tell Sympy the values of symbols but still have it handle them symbolically?

**Comment by mstimberg** [comment]
I don't think we can, we can only provide assumptions (positive, etc.) -- but in any case, we'd have the same issue if `taum` and `taue` were parameters in the equation, nothing we can do about it in that case.

**Comment by thesamovar** [comment]
OK so we just need to handle NaNs and have a good page then.
