### ISSUE TITLE
Improve weave's efficiency

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#577]
I noticed that simulations with weave were extremely slow on my machine and realized that weave is very inefficient on machines where you run a lot of different weave code (which we do of course, especially when running the test suite). 

On my machine, the database index in `~/.cache/scipy/python27_compiled/linux227compiled_catalog.dir` is ~400MB. This file is accessed using the "patched" `dumbdbm` from weave by reading in all lines (11639 in my case). Each line is of the form:
```
"some C code", (number, number)
```
And this will be converted into a tuple of string and two integers using Python's `eval` function (sic). This whole process is done 10 times for the CUBA simulation, I guess once for every code object... 

Actually, any benchmarking I did recently (e.g. #576) is probably mostly a reflection of these database operations. If I run the CUBA example with the 400MB database, it takes more than 1 minute. After deleting the database it only takes 26s even though it has to compile all the code! A run after that only takes 13s...

I wonder whether it makes sense to for example have one database directory per project directory, instead of a global one for the user (at least as an option). Granted that our situation is a bit extreme because we run the test suite often and we run it on different version of Brian. I can imagine something similar happening for other "power users" as well, and it can give a very bad impression for runtime mode -- in fact, I already started suspecting a harddisk problem as a reason for the slowdown...

**Comment by thesamovar** [comment]
Oh wow! I'm surprised it's so bad. Can we access the database store for weave?

I think it shouldn't be so bad for Cython. If I remember correctly, we take a hash of the source code and use that as a filename, and then we just check if that filename is there or not. I thought that weave would be doing something similar.

**Comment by mstimberg** [comment]
Actually, after a bit of investigation I found the situation may be specific to my machine or maybe anaconda installations. If I try `import dbhash`, then this fails with an error about `bsddb`. This is way weave falls back to the "dumb db" which is using the huge textfile + eval approach. After a `conda install bsddb` it now uses a Berkeley DB database file (`linux227compiled_catalog`) and I think this should be much faster and memory efficient. We should probably add this as a dependency, at least for the conda package.
Actually, maybe with the Berkeley DB issue #463 disappears and we can run weave in parallel?

**Comment by mstimberg** [comment]
> Actually, maybe with the Berkeley DB issue #463 disappears and we can run weave in parallel?

Just tried it, this is still not working so the DB is not the issue. I think the problem is that several process might interfere while writing to the same file.

**Comment by thesamovar** [comment]
Yup, import dbhash works for me which I guess explains why I wasn't seeing this.
