### ISSUE TITLE
Are pre and post keyword arguments in Synapses confusing?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#582]
@romainbrette

**Comment by mstimberg** [comment]
I got some feedback on this question and we agreed that `on_pre` and `on_post` would have been a better choice. Given that this syntax has been around for quite some time now we should leave `pre` and `post` as an alternative for quite some time, though. The questions is whether we'll emit a warning or not. I'm tempted to not warn for now, given that this will raise a warning for almost every script out there -- maybe wait a bit until the new syntax trickled down from documentation and examples?

**Comment by thesamovar** [comment]
So the idea is we would change the documentation and all the examples to have ``on_pre`` and ``on_post`` but we allow ``pre`` and ``post`` to keep working without warning for a while? I'd be happy with that, although I think it's better to make it a warning now before everyone is using Brian 2. A warning is a fairly mild thing: it doesn't stop anything from working.

**Comment by mstimberg** [comment]
> So the idea is we would change the documentation and all the examples to have on_pre and on_post but we allow pre and post to keep working without warning for a while?

That was my idea -- but you are probably right that warning is not a big deal and we should better do it now than later.

**Comment by thesamovar** [comment]
OK, if we do the warning I'm definitely OK with this.

**Comment by mstimberg** [comment]
There's actually one more open question here: should the "pathway" also be renamed to `on_pre`, `on_post`? E.g. to change the delay:
```Python
syn.on_post.delay = 3*ms  # or syn.post.delay ?
```

**Comment by thesamovar** [comment]
I would vote for keeping ``syn.post.delay`` but I don't have a very strong feeling about that so happy to go the other way if you prefer.

**Comment by syntapy** [comment]
How about make warnings, but use a function to easily disable all the warnings with one call? And the function would be documented and allow users to decide which warnings to disable, and maybe even all warnings?

**Comment by mstimberg** [comment]
> How about make warnings, but use a function to easily disable all the warnings with one call? And the function would be documented and allow users to decide which types of warnings to disable, and maybe even all warnings?

That's an excellent idea @syntapy, you will be happy to hear that our logging system is already capable of doing this :-) This feature is unfortunately somewhat hidden in the developer documentation, but by raising the log level to "ERROR" you will suppress all warnings and you can suppress specific warnings with `BrianLogger.suppress_hierarchy` and `BrianLogger.suppress_name`: http://brian2.readthedocs.org/en/2.0b4/developer/guidelines/logging.html

**Comment by mstimberg** [comment]
> I would vote for keeping syn.post.delay but I don't have a very strong feeling about that so happy to go the other way if you prefer.

I don't have a strong opinion either, so I'd say for simplicity let's use the pathway names we used before (i.e. `pre` and `post` instead of `on_pre` and `on_post`).
