### ISSUE TITLE
Update installation docs for Windows

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#591]
Recently, a few things seem to have improved for C++ code generation under Windows:
* Python 3.5 does no longer need the SDK environment variables under 64 Bit
* Anaconda now comes with a msvc_runtime package that might make a manual download of the "C++ compiler for Python" obsolete

We should check this and update the installation docs accordingly before the release.

**Comment by thesamovar** [comment]
Interesting, that would be great if true.
