### ISSUE TITLE
Put Cython code into temp directory rather than user directory?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#599]
At the moment, Cython files go into ``~/.brian/cython_extensions``. Perhaps this directory should be a Brian option (with the default being to put it in a temp directory, like weave does)?

**Comment by mstimberg** [comment]
Just a quick remark: Under Linux, weave puts it files not in the temp directory but in `~/.cache` (or whatever  `$XDG_CACHE_HOME` specifies, I guess) which seems to be the correct place (this directory is the "base directory relative to which user-specific non-essential (cached) data should be written").

I agree that making it configurable is a good idea.
