### ISSUE TITLE
Treat stateful functions correctly when using sympy (e.g. in equations)

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#604]
Quoting myself from https://github.com/brian-team/brian2/pull/602#issuecomment-160972614 :

I realized that there is one annoying issue that we did not take yet care of. In the work you did for the code optimization, we avoided incorrectly simplifying expressions that involved stateful functions. Unfortunately, we can't control this whenever we use sympy. In the current code, including `rand() - rand()` somewhere in equations will be simplified away directly. The changed I propose in #603 (extracting common subexpressions) would mean that we are using sympy for all statements, so this problem would also occur for code in `run_regularly` operations, in resets, etc. I guess we have to deal with this at the very first stage where we convert strings into sympy objects, but unfortunately this also means that we will need the variables dictionary there whereas currently we don't.

**Comment by mstimberg** [comment]
Given that this is mostly a theoretical problem for now (no one will write `rand() - rand()`) and that this is non-trivial to fix -- how about clearly documenting it (and maybe add it to a "known bugs" section, together with a warning about the random number generation in standalone, etc.) and postponing the fix to post-2.0?

**Comment by thesamovar** [comment]
It makes me uncomfortable to leave this sort of bug in. If it's too much work to fix right now, how about we count the number of calls of each stateful function in a given statement/expression and raise an error/warning if it's more than 1?

**Comment by mstimberg** [comment]
Ok, this is probably a better short-term solution. I'll think about where the best place would be for this check. Given that it should never occur in practice, raising an error and not just a warning might be the best solution.

**Comment by thesamovar** [comment]
Agreed.
