### ISSUE TITLE
Matlab interface?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#618]
It might be interesting to many people to have an easy way to interoperate Brian with Matlab scripts. One way to do this would be to use a standalone device to generate a mex function (or even simpler, a Matlab function that calls out to an executable). It might also be possible to have it work transparently from within Matlab, e.g. have a couple of functions that can call out to Python to generate the executable and everything (for this you'd still need the simulation script in Python). We could also consider automatically generating a Matlab interface from the Python one, allowing people to use Matlab directly, but the danger of this is that it would put a heavy support burden on us since likely a lot of people would just use this instead of Python. On the other hand, if it increased the number of users substantially maybe even that could be worth it?

**Comment by thesamovar** [comment]
See also #251, #306.

**Comment by mstimberg** [comment]
Yuk :) I think the maintenance burden would be a nightmare (e.g. we can't do automatic testing on the servers) and I don't really see the interest: if your simulation is using Brian, what would you do in Matlab? If it is only the analysis, then writing the data to disk and loading it for your analysis seems to me a much simpler approach. If someone else would be interested in writing an interface, why not, but I think we have much more important tasks on our list.
A direct Matlab frontend (if I understood correctly, you mean that you could actually write a Brian script completely in Matlab?) would be a crazy amount of work I think. Either you'd have to re-write a lot of fundamental mechanisms that we use (overloaded operators for units, overloaded attribute setting, the magic system...) in Matlab or you'd have to use an ugly system where you call stuff like `exec_brian('neuron.Vm = \'i*mV\'')`.

**Comment by thesamovar** [comment]
You're probably right. :) OK, closing this issue. Maybe a cookbook project at some point.
