### ISSUE TITLE
Error after installing on Python 3.5

### ISSUE THREAD

**Issue by prcastro** [brian-team/brian2#622]
I installed version 2.0b4 of brian (downloaded the tar.gz source package from PyPi) in my ArchLinux machine (with python 3.5.1). I installed by `cd`ing into the downloaded folder and running `python setup.py install` (`python` defaults to Python 3 on ArchLinux). After running `import brian2`, I get the following error:

http://pastebin.com/7tfkNENX

I had a problem with the `izip` function also, but I can't reproduce it.

**Comment by thesamovar** [comment]
Thanks for the report. This is actually fixed in master and will be in the next release (it's specific to Python 3.5).
