### ISSUE TITLE
Sections and number of segments

### ISSUE THREAD

**Issue by rcaze** [brian-team/brian2#628]
I would like first to thank you for this great piece of software! I wanted to jump into Brian and as a NEURON user I like the concepts of sections and segments. When you create one geometrical element in Brian you can specify the number of segments (for instance: 'Cylinder(..., n=5)'). Is there a method to change this number of segments after the creation? Do you plan to implement this feature? If not how one (me) could do it best?

**Comment by mstimberg** [comment]
The internal representation of the morphology is currently a bit in a flux and might change significantly soon, have a look at #569 and [the wiki entry](../wiki/Open-questions:-Multicompartmental-modeling).

Could you explain your use case a bit -- why do you want to change the number of segments? Are you thinking about changing it in the `Morphology` (i.e. before the creation of a `SpatialNeuron`) or when you already have a `SpatialNeuron` object?

**Comment by rcaze** [comment]
I want to segment a model from a reconstruction. A bit like the 'CellBuilder' of NEURON. So to be clearer I would like to change the number of segments just after loading an 'swc' file and before 'SpatialNeuron'.

**Comment by mstimberg** [comment]
Ok, thanks -- this is exactly the scenario we are discussing in the pull request/wiki page, feel free to weigh in with any comments about what is proposed there.

**Comment by rcaze** [comment]
I read the wiki on the two problems. I have a solution for the number two, namely changing the number of compartments, and this solution keep the length constant. I wrote a python function for that. It takes as input the lists of coordinates defining a section and a number of segments and it outputs the new set of coordinates (I wrote that for NEURON;). How can I send you the code snippets?

**Comment by mstimberg** [comment]
Thanks, I'd be interested in that function, maybe just send it by mail or put it in a gist? Or if it is not too long, you could also just post it here as a comment.

**Comment by rcaze** [comment]
Hi Marcel,

Hope this code snippet is self-explanatory.

2016-01-13 21:36 GMT+00:00 Marcel Stimberg <notifications@github.com>:

> Thanks, I'd be interested in that function, maybe just send it by mail or
> put it in a gist? Or if it is not too long, you could also just post it
> here as a comment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brian-team/brian2/issues/628#issuecomment-171442120>.
>



-- 
Dr R D Caze
http://romaincaze.wordpress.com/
Marie Curie Initial Training post-doctoral Fellow
@ Department of Bioengineering
Imperial College London
Tel: +44 (0) 7840596166

**Comment by mstimberg** [comment]
I think you mistakenly replied to the github notification mail so your mail appeared in the github issue (and this does not take attachments) -- use my personal mail (see @mstimberg) instead.
