### ISSUE TITLE
Brian tutorial (for NEURON lover)

### ISSUE THREAD

**Issue by rcaze** [brian-team/brian2#631]
Hi All,

I am currently writing a tutorial that would be (for the first two parts at least) as close as possible to the famous NEURON tutorial (http://www.anc.ed.ac.uk/school/neuron/). But failed to reproduce the plot from the first part and obtained something different (I sent the script to Marcel). What am I doing wrong? Also In this script I am launching in fact three simulations. How could I launch one instead? (guess the answer is in eq), also it would be nice to have something like an insert method and default hh and pas mechanism -to be more user friendly (smaller and tidier script).

**Comment by mstimberg** [comment]
I am posting the code you sent me here (how about putting it in its own github repository or in a fork of the Brian 2 repository in case you intend to submit the finished tutorial for inclusion in Brian 2?):
```Python
# Brian tutorial (for NEURON lovers) PART #1
import matplotlib.pyplot as plt
import brian2 as br2
from brian2 import um, mV, cm, uF, siemens, ohm, amp, ms, namp

gNa0 = 0.120*siemens/cm**2
gK = 0.036*siemens/cm**2
gl = 0.0003*siemens/cm**2
ENa = 50*mV
EK = -77*mV
El = -54.3*mV
EL = -70*mV
gL = 0.001*siemens/cm**2

# Typical equations for hh and pas
eq = '''
Im = hh + pas : amp/meter**2
hh = gl * (El-v) + gNa * m**3 * h * (ENa-v) + gK * n**4 * (EK-v) : amp/meter**2
pas = gL * (EL-v) : amp/meter**2
I : amp (point current) # applied current
dm/dt = alpham * (1-m) - betam * m : 1
dn/dt = alphan * (1-n) - betan * n : 1
dh/dt = alphah * (1-h) - betah * h : 1
alpham = (0.1/mV) * (-v+25*mV) / (exp((-v+25*mV) / (10*mV)) - 1)/ms : Hz
betam = 4 * exp(-v/(18*mV))/ms : Hz
alphah = 0.07 * exp(-v/(20*mV))/ms : Hz
betah = 1/(exp((-v+30*mV) / (10*mV)) + 1)/ms : Hz
alphan = (0.01/mV) * (-v+10*mV) / (exp((-v+10*mV) / (10*mV)) - 1)/ms : Hz
betan = 0.125*exp(-v/(80*mV))/ms : Hz
gNa : siemens/meter**2
'''

# Create the geometrical objects corresponding to the two compartments
e_neuron = br2.Soma(diameter=18.8*um)
e_neuron.sections = {"soma": e_neuron}
e_neuron.name = "soma"
neuron = br2.SpatialNeuron(morphology=e_neuron, model=eq,
                           method="exponential_euler",
                           Cm=1*uF/cm**2, Ri=123*ohm*cm)

neuron.v = -65*mV
neuron.h = 0
neuron.m = 0
neuron.n = 0
neuron.I = 0*amp
neuron.gNa = gNa0
M = br2.StateMonitor(neuron, 'v', record=True)

br2.run(100*ms, report='text')
neuron.I = 1.1*namp
br2.run(100*ms, report='text')
neuron.I = 0*namp
br2.run(100*ms, report='text')
plt.plot(M.t/ms, M.v.T[:, 0*100]/mV)
plt.xlabel('Time (ms)')
plt.ylabel('v')
plt.ylim(-80, 40)
plt.show()
```

**Comment by mstimberg** [comment]
I only had a quick look at the NEURON code, but are you sure that you are using the same HH equations as in that example? From here, it seems to use a differently shifted membrane potential: http://www.neuron.yale.edu/hg/neuron/nrn/file/tip/src/nrnoc/hh.mod Also, I think their hh model already includes the leak so you don't need an extra "pas" current.

I think this is exactly the reason why we don't want to include a "standard" model of HH channels in Brian 2 (I am sure @romainbrette agrees), hiding this in a black box instead of writing down the equations explicitly as part of your model glosses over the details which can make quite a difference. If in a project (or for the tutorial), you are going to use the same set of channels repetitively, you can always store then in a variable/module/function, i.e. something like
```Python
hh = Equations('''
hh = ...
dm/dt = ...
...
''')
# or simply
hh = '''
hh = ...
dm/dt = ...
...
'''
```
you can then concatenate these `Equations` or strings into the full equations.

**Comment by rcaze** [comment]
Thank you Martin,
I am new to github but I will try to do a pull (why not say push?:) request for the tuto. I fully understand and agree also with the rational to go as far as possible from the black box approach of NEURON. Yet I think a middle way is possible. It would avoid to be over-verbose. The tutorial would be about Brian and not HH. 

Using a different HH from NEURON was my guess. My question would become:"how different?" It would bring even more people to Brian if a demonstration of their parallelism could be made.

**Comment by mstimberg** [comment]
> Using a different HH from NEURON was my guess. My question would become:"how different?" It would bring even more people to Brian if a demonstration of their parallelism could be made.

I am sorry, I do not quite understand the question...

**Comment by rcaze** [comment]
No worry my clarity is most of the time a problem. What differs in NEURON and Brian in the implementation of HH? In others words why the curve obtain from the script and the one in the NEURON tutorial are different? How can we make them similar? (three question but I hope I am clearer)

**Comment by mstimberg** [comment]
It is clearer indeed :) Well, while there is an "HH implementation in NEURON", there is no such thing in Brian -- it just executes the equations you give it. So to give the same result, you'd need to use the same equations as NEURON uses -- you should be able to more or less copy them from the mod file I linked before, I guess. I am not sure why in the NEURON tutorial they consider the squid giant axon HH model at 6.3°C as a good model of "subthalamtic projecting neurons", but well...

**Comment by thesamovar** [comment]
Closing this unless there is some reason to keep it open?
