### ISSUE TITLE
Error while creating an environment with Anaconda

### ISSUE THREAD

**Issue by rcaze** [brian-team/brian2#633]
I installed the last version of Brian 2 using conda for developping. 
```
conda install --channel https://conda.anaconda.org/brian-team brian2
```

But when I try to create a new environment from it. It fails

```
rcaze@romain-work:~$ conda create -n brian_tuto_dev brian2
Fetching package metadata: ....
Error: No packages found in current linux-64 channels matching: brian2

You can search for this package on anaconda.org with

    anaconda search -t conda brian2
```

What is happening?

**Comment by mstimberg** [comment]
You did not add the `brian-team` channel, but used it only once for the installation of brian 2 in your anaconda root environment. You'll have to add the `brian-team` channel (or specify it again when you use `create`), as explained in our installation instructions: http://brian2.readthedocs.org/en/latest/introduction/install.html#installing-brian-2
