### ISSUE TITLE
Make standalone mode more prominent in documentation

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#645]
Currently, the "Devices" page that explains the standalone mode is a bit hidden. How about including the information from this page in "Computational methods and efficiency"?

**Comment by thesamovar** [comment]
I'd be happy to put more about standalone mode in the computational methods section, but I wouldn't necessarily move it. I also don't particularly find that it's difficult to come across. It's mentioned within the first few paragraphs in the efficiency section with a note saying that it's the fastest method.

Maybe we should rename "Devices" to "Standalone mode" though until we actually have other devices!

**Comment by mstimberg** [comment]
Oops, did forget to comment on this one. 

> I'd be happy to put more about standalone mode in the computational methods section, but I wouldn't necessarily move it. I also don't particularly find that it's difficult to come across. It's mentioned within the first few paragraphs in the efficiency section with a note saying that it's the fastest method.

I opened this issue after watching Romain looking for the documentation on how to enable standalone mode. It went like this: going to "Running a simulation", clicking on the "Computational methods and efficiency" link and then scrolling through the page looking for the `set_device` code snippet. This did not exist, so he searched for a link that says "standalone mode", this does not exist either (but it is mentioned in the text with a link to "Devices", as you say).

I think the "Computational methods and efficiency" page is currently a bit unbalanced, its title suggests something general, and it has some general text about compiler settings (which applies both to runtime and standalone) but it also goes into the specifics of runtime mode.

IMHO, the page should be either general and have a link to "Runtime mode" and "Standalone mode" (and yes, renaming is a good idea) in the first paragraph, or be a longer page with one section for runtime mode and another one for standalone mode.

**Comment by thesamovar** [comment]
OK, I see what you mean. In that case, yes let's make this a longer page with information about standalone, and get rid of the 'devices' section. If we have a couple of GPU devices implemented by the time we do the release, we could add a new "Running on GPU" page (and also add a link to that from the computational efficiency page).
