### ISSUE TITLE
AttributeError: 'MagicNetwork' object has no attribute 'reinit'

### ISSUE THREAD

**Issue by flinz** [brian-team/brian2#649]
Me and @MarcoLehmann are currently converting [our lab's brian1 scripts](https://github.com/EPFL-LCN/neuronaldynamics-exercises) to brian2 and stumbled across the following curious error (on the brian2.0b4 release)

```python
import brian2
brian2.reinit()
```

which results in 

```python
.../brian2/core/magic.pyc in reinit()
    370         intended use. See `MagicNetwork` for more details.
    371     '''
--> 372     magic_network.reinit()
    373
    374 def store(name='default'):
AttributeError: 'MagicNetwork' object has no attribute 'reinit'
```

I guess this is not intended behavior?

**Comment by mstimberg** [comment]
Thanks for the report, this is indeed not intended. The `Network.reinit` method (and accordingly `MagicNetwork.reinit`) was removed a while ago, it is no longer necessary/possible to reinitialize a network. See https://brian2.readthedocs.org/en/2.0b4/user/running.html (in particular the last section about "Continuing/repeating simulations") for details.

So `reinit()` should simply disappear, which leads to a simple workaround for now: don't use it :-)

**Comment by flinz** [comment]
Thanks for the quick reply and the easy to apply fix :+1: we will refrain from using it
