### ISSUE TITLE
Integer division is different for different languages

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#661]
`-1/2==-1` in Python (and numpy), but `-1/2==0` in C++.

We handled this for `a%b` but not for integer division. We should either handle this or at least warn about it somewhere.

**Comment by mstimberg** [comment]
Ugh, how could we have not seen this when we dealt with the mod issue...? We decided to go for Python's semantics for mod, didn't we? I guess we should then use Python's semantics here as well. This means that in the C++ renderer, we'd replace integer division by `_brian_div(a, b)` and this function then takes care of the semantics. Or maybe for the compiler it is better to directly replace it by (`a >= 0 ? a/b : (int)(floor((double)a/b))`) (or something like that) -- this way it could be easy optimized away for positive constants.

**Comment by thesamovar** [comment]
Does that force us to change it for all languages? It's a shame but I guess there's no way round it. For Cython we could conceivably set ``cdivision: false`` and this will also fix the mod problem.

**Comment by thesamovar** [comment]
My vote is that for 2.0 we just put a note in the "known issues" page in the documentation, and we try to fix this in 2.0.1. What do you think?

**Comment by mstimberg** [comment]
Agreed, we can postpone this. It's important to do this right, we certainly don't want to fix a corner case at the cost of breaking more common use cases...
