### ISSUE TITLE
Check generated synapse indices are valid after construction

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#666]
This is necessary if using the generator syntax.

Should we do this for 2.0?

**Comment by mstimberg** [comment]
Yes, I think we should do it. For runtime we can copy the existing code (or rather refactor it in a function), for standalone we'll put the check directly in the template. The only thing that is a bit ugly is that that means that we need a `if isinstance(device, RuntimeDevice)` check in `Synapses`.

**Comment by thesamovar** [comment]
Why not just always do it from the template? Like we do with calling ``_update_synapse_numbers``?

**Comment by thesamovar** [comment]
By the way, this is issue 666 so we can expect it to be problematic.

**Comment by mstimberg** [comment]
> Why not just always do it from the template? Like we do with calling _update_synapse_numbers?

Right, makes a lot of sense.

> By the way, this is issue 666 so we can expect it to be problematic.

I noticed!

**Comment by mstimberg** [comment]
Closed via #600
