### ISSUE TITLE
Runtime check for nans

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#676]
In order to prevent/alleviate situations like #626 we should at least check for nans at runtime and log a warning pointing to a documentation page with some advice about what could be causing it. This is less than what was proposed in #499: we should still do that, but this would be good to have for 2.0.

**Comment by mstimberg** [comment]
Isn't this #554?

**Comment by thesamovar** [comment]
Yes! Closing this issue and promoting that one to 2.0 (if you agree?).

**Comment by mstimberg** [comment]
> Yes! Closing this issue and promoting that one to 2.0 (if you agree?).

Yes in general -- let's discuss the details there (e.g. whether we need to check during the run or whether checking at the end is fine)
