### ISSUE TITLE
Expose the network simulation schedule to the user

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#678]
While we have a nice system to control the execution schedule of all objects in a network, the final schedule is not necessarily very obvious to the user. A method like `Network.object_schedule` (`schedule` is already taken for the general schedule, but we can probably come up with a better name) with an equivalent for the magic network should print something like this:

```
dt     | slot       | order | name
------------------------------------------------------
0.1 ms  start         0       statemonitor
0.1 ms  groups        0       neurongroup_stateupdater
0.1 ms  thresholds    0       neurongroup_thresholder
0.1 ms  resets        0       neurongroup_resets
```

or ideally it would rather return an object that can be converted to a string like the above but also allows for convenience methods to access certain details (similar to `ProfilingSummary`). Yet another "ideally": it would be great if instead of collecting this information for the user on demand, the object would also be internally used as part of the scheduling so that we can sure that the reported schedule and the actually used schedule are the same.

Obviously, the above output is an example and I'm open to a different formatting... Oh and one detail that we should deal with: `NeuronGroup`, `Synapses`, etc. will appear in the object list even though they do not do anything in their `run` method, all computation is performed by the state updater, thresholder, etc. objects. This will certainly not be very obvious to the average user... (I myself stumble over it every time ;-) )

**Comment by thesamovar** [comment]
Sounds like a good idea to me!
