### ISSUE TITLE
Update main web page for release

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#685]
We should update the main webpage to point to Brian 2 stuff by default when we release 2.0 final. Also, it could really do with a cleanup: lots of outdated / broken links (I just removed some, but there are more).

**Comment by thesamovar** [comment]
For 2.0 let's not change the theme immediately but at least update the content?

**Comment by thesamovar** [comment]
One option to consider is to use GitHub pages as a host, and have a static site generator.

**Comment by thesamovar** [comment]
OK, I updated everything except for the front page, which we should discuss. Take a look and let me know what you think? Mostly it now redirects to the docs, and some older content has been cut.

For the front page, I think the current example code and image is great. We might also want to link directly to some of the things that are on the sidebar, like install instructions, examples, tutorials, documentation, support page, etc. I like having the "what to cite" information there. Anything else?

**Comment by mstimberg** [comment]
> OK, I updated everything except for the front page, which we should discuss. Take a look and let me know what you think? Mostly it now redirects to the docs, and some older content has been cut.

Looking great (not literally, but you know what I mean). The two paragraphs right after the example are now outdated, though. A line mentioning Brian 1 and referring to its docs might be good? 

Apart from that, yes a line that has the most important links (even if they are duplicated) would be nice: documentation + install + support, I guess

**Comment by thesamovar** [comment]
OK, I've updated the front page. What do you think?

**Comment by mstimberg** [comment]
> OK, I've updated the front page. What do you think?

Perfect, I think that's all we need. One small thing to fix: the code example has `&gt;` instead of `>` in the threshold.

**Comment by thesamovar** [comment]
Done!
