### ISSUE TITLE
Brian2.test multiple failures

### ISSUE THREAD

**Issue by adamhaber** [brian-team/brian2#709]
I'm interested in trying Brian2 for a project I'm working on, and I've installed it using conda.
Then, I ran brian2.test() and got many failed test. 

I've looked through the documentation and made sure I've installed everything as instructed.
I'm using Python 2.7, Anaconda 4.0.0, on Windows 7 Ent.

I'm attaching the test results in case it helps.
[brian2 test log.txt](https://github.com/brian-team/brian2/files/302493/brian2.test.log.txt)

**Comment by thesamovar** [comment]
Looks like you haven't got MSVC installed or maybe there is some interference between this version and another version? See, e.g. http://stackoverflow.com/questions/4676728/value-error-trying-to-install-python-for-windows-extensions

In any case, it's not a Brian-specific problem, so closing this issue.

**Comment by mstimberg** [comment]
We should maybe restructure the test suite so that it does not run the weave/cython tests if they don't work, this abundance of errors does not really help..

**Comment by thesamovar** [comment]
Indeed! Can we set it to print out a clear message to the user saying that weave/cython are not available because of the lack of a compiler?

**Comment by mstimberg** [comment]
Oh, and I forgot @adamhaber : especially if all you want to is to try out Brian, the test results do not mean you cannot use Brian! You *can* run Brian code in "numpy mode", the only disadvantage is that without the working C compiler it will not be as fast as it would be otherwise (typically by about a factor of ~2). If weave/cython does not work (as in your case), "numpy mode" will be automatically selected but you'll get a warning. Alternatively, you can also explicitly set `prefs.codegen.target = 'numpy'` and everything should work. See the documentation for more details: http://brian2.readthedocs.io/en/2.0rc1/user/computation.html

You can also run the test suite without the weave/cython tests by using `brian2.test('numpy')`.

**Comment by mstimberg** [comment]
> Indeed! Can we set it to print out a clear message to the user saying that weave/cython are not available because of the lack of a compiler?

Sure, shouldn't be too difficult.

**Comment by fuadfukhasyi** [comment]
I've installed brian2 using anaconda2 32-bit also Microsoft Visual C++ Compiler for Python 2.7. But when I'm testing brian using jupyter notebook use command:
import brian2
brian2.test()
I got many failed test.
please give me advice..
thank you..

**Comment by fuadfukhasyi** [comment]
Running tests in C:\Users\anaconda\Anaconda2\envs\myenv\lib\site-packages\brian2 for targets numpy, cython (excluding long tests)
Testing codegen-independent code 
Resetting to default preferences

Running tests that do not use code generation
.................S.................S........WARNING    Integrating equations with GSL is still considered experimental [brian2.stateupdaters.GSL]
.........WARNING    Cannot use Cython, a test compilation failed: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools (DistutilsPlatformError) [brian2.codegen.runtime.cython_rt.cython_rt.failed_compile_test]
...............................................................................................................................................................................SS.................................................WARNING    The 'independent' state updater is deprecated and might be removed in future versions of Brian. [brian2.stateupdaters.exact.deprecated_independent]
..................................................................
----------------------------------------------------------------------
Ran 343 tests in 139.661s
..
.
.
.
.
.
.

sorry, the result can not be attached. i've tried but it can't

**Comment by mstimberg** [comment]
Is it possible that you are using Python 3 and not Python 2? In that case you'd need a more recent version of the Microsoft Compiler. According to the Python documentation for 3.5 and 3.6 (most likely  you are using one of them), please download the *Build Tools for Visual Studio 2017* from  https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017

**Comment by fuadfukhasyi** [comment]
In program and feature on control panel written _Python 2.7.14 (Anaconda2 5.1.0 32-bit)_.
Should I install Build Tools for Visual Studio 2017?

**Comment by mstimberg** [comment]
I am not sure what control panel you are referring to, but make sure that you are checking the version in `myenv` where you are running the tests. In a jupyter notebook where Brian 2 tests fail, what does
```Python
import sys
sys.version
```
display? If it shows 2.7.14, then this is very odd, you should not have to install Visual Studio 2017 for that version.

**Comment by fuadfukhasyi** [comment]
It shows 3.6 then I installed Visual Studio 2017. but I still got many failed and error..
