### ISSUE TITLE
Cython SpikeQueue build failures on Windows

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#724]
Some builds started failing on appveyor lately, I don't quite see the pattern, it seem to be 64-bit builds, but not those that use Python 3.5...?
One example is here:
https://ci.appveyor.com/project/brianteam/brian2/build/1501/job/bs679qmyb2off0mq

The error seems to be that `link.exe` is called with an extra parameter:
```
C:\Program Files\Git\usr\bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Miniconda3-x64\envs\_build\libs /LIBPATH:C:\Miniconda3-x64\envs\_build\PCbuild\amd64 /EXPORT:PyInit_cythonspikequeue build\temp.win-amd64-3.4\Release\brian2\synapses\cythonspikequeue.obj build\temp.win-amd64-3.4\Release\brian2/synapses/cspikequeue.obj /OUT:build\lib.win-amd64-3.4\brian2\synapses\cythonspikequeue.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\brian2\synapses\cythonspikequeue.lib /MANIFESTFILE:build\temp.win-amd64-3.4\Release\brian2\synapses\cythonspikequeue.pyd.manifest
link: extra operand '/INCREMENTAL:NO'
Try 'link --help' for more information.
error: command 'C:\\Program Files\\Git\\usr\\bin\\link.exe' failed with exit status 1
```
Quick googling did not turn up anything obvious, @thesamovar any idea?

**Comment by thesamovar** [comment]
I think the problem might be to do with path order, it is trying to use the GNU linker.

**Comment by mstimberg** [comment]
> I think the problem might be to do with path order, it is trying to use the GNU linker.

Hmm, but isn't distutils taking care of this stuff (or rather the call to `vcvarsall.bat`)? Do you think there is anything we can do about this from Brian's side or is it something in the appveyor configuration and only needs to be fixed there?

**Comment by thesamovar** [comment]
I think it's probably in the appveyor configuration but if that was the case then I'd expect to see bug reports on their end and a quick fix.

**Comment by mstimberg** [comment]
This does not seem to be an issue anymore, let's close it for now and re-open it in case we encounter the problem again.
