### ISSUE TITLE
Implement MPI?

### ISSUE THREAD

**Issue by AStupidBear** [brian-team/brian2#733]

**Comment by thesamovar** [comment]
OpenMP is already supported in C++ standalone (although still a bit experimental at this stage).

**Comment by AStupidBear** [comment]
But for larger networks beyond the capacity of one node?

**Comment by mstimberg** [comment]
> But for larger networks beyond the capacity of one node?

Changing Brian to work in a distributed memory environment would be a fundamental change to the Brian architecture and will therefore not be done by us in the foreseeable future. Multi-node computation requires explicit messages to be sent around and you cannot do this efficiently for all the kinds of models that Brian permits (e.g. synapses can refer to and change both pre- and post-synaptic variables, variables can be linked within groups).

**Comment by AStupidBear** [comment]
Yes, this is a trade off between flexibility and powerfulness. Yao-------- Original Message --------Subject: Re: [brian-team/brian2] Implement MPI? (#733)From: Marcel Stimberg To: brian-team/brian2 CC: Yao Lu ,Author 
But for larger networks beyond the capacity of one node?


Changing Brian to work in a distributed memory environment would be a fundamental change to the Brian architecture and will therefore not be done by us in the foreseeable future. Multi-node computation requires explicit messages to be sent around and you cannot do this efficiently for all the kinds of models that Brian permits (e.g. synapses can refer to and change both pre- and post-synaptic variables, variables can be linked within groups).
