### ISSUE TITLE
synapses within python array not working ?

### ISSUE THREAD

**Issue by yzerlaut** [brian-team/brian2#734]
Dear Brian2 developers,

In the following example: [CUBA](http://brian2.readthedocs.io/en/2.0rc/examples/CUBA.html)
When I substitute
`Ce = Synapses(P, P, on_pre='ge += we')`
`Ci = Synapses(P, P, on_pre='gi += wi')`
`Ce.connect('i<3200', p=0.02)`
`Ci.connect('i>=3200', p=0.02)`
With:
`C_ARRAY = []`
`C_ARRAY.append(Synapses(P, P, on_pre='ge += we'))`
`C_ARRAY.append(Synapses(P, P, on_pre='gi += wi'))`
`C_ARRAY[0].connect('i<3200', p=0.02)`
`C_ARRAY[1].connect('i>=3200', p=0.02)`
It doesn't work anymore...
(It does not report any error but the synapses are not created anymore... see the much higher firing rate because the recurrent inhibition is absent...)

Is it a bug ? Or am I missing something and I shouldn't try to do that ? If yes, why ?

**Comment by mstimberg** [comment]
I assume you use the standard `run()` function, i.e. you do not create an explicit `Network` object? In this case this is expected, the `run` does not "see" your synapses when they are in a container like a list. Here's the relevant quote from the docs (http://brian2.readthedocs.io/en/2.0rc3/user/running.html#magic-networks):

> Note that it will not automatically include objects that are “hidden” in containers, e.g. if you store several monitors in a list. Use an explicit `Network` object in this case. It might be convenient to use the `collect()` function when creating the `Network` object in that case:

> ```Python
G = NeuronGroup(10, 'dv/dt = -v / tau : volt')
S = Synapses(G, G, model='w:1', on_pre='v+=w')
S.connect('i!=j')
monitors = [SpikeMonitor(G), StateMonitor(G, 'v', record=True)]
# a simple run would not include the monitors
net = Network(collect())  # automatically include G and S
net.add(monitors)  # manually add the monitors
```

**Comment by yzerlaut** [comment]
Indeed... Sorry about that, and thanks a lot for your quick response !!
