### ISSUE TITLE
clip function returns double value for integer arguments

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#782]
This only applies to C++/Cython -- probably we should use fused types/templates here to return the type of the first argument?

**Comment by thesamovar** [comment]
Yeah, should be similar to things like ``mod``, ``abs`` etc.

**Comment by dsprenkels** [comment]
Would you like PRs for random easy bugs like this one? If so, then I would like to work on this.

**Comment by mstimberg** [comment]
> Would you like PRs for random easy bugs like this one? If so, then I would like to work on this.

A PR would be most certainly welcome! In general, if it is a bug with a relatively clear fix, please don't hesitate to contribute. If it is something that needs discussion (most importantly everything that changes user-facing syntax), it is better to lay out the proposed solution first before spending much time on an implementation that might not be what we had in mind.

**Comment by dsprenkels** [comment]
I opened a pull request in #810.
