### ISSUE TITLE
Group_variable_set template uses global pointer variable instead of functions scope pointer variable

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#796]
See my comment on [here](https://github.com/brian-team/brian2/commit/eef72536cfbeeb6d2827f43172ceb9c1ae7cfeff#diff-249efa7f2d1861cb5520386b1d00664eR986).

Was that intended? In `cuda_standalone` we don't have access to the global host variables,  so I can't use the `{{_group_idx_var}}` keyword the way it is defined now, but have to reset it with
```
{% set _group_index_var = get_array_name(variables['_group_idx']) %}
```
to get the correct pointer variable used in the function scope (since this uses the generator `get_array_name` function instead of the devices).

**Comment by mstimberg** [comment]
Um, no that was not intended. In `cpp_standalone`, this distinction between local and global does not matter much (except for potential optimizations by the compiler), but after looking at the code again, my fix was much too complicated anyway. It should have just relied on our standard mechanism (which generates the function scope name you need). 
Could you check whether the version I just pushed to the `fix_#796` branch works for you?

**Comment by mstimberg** [comment]
Oops, just had to push a new version to that branch, I forgot a teardown function in a "standalone-compatible" test...

**Comment by denisalevi** [comment]
Yep, this works for me. Thanks!

**Comment by mstimberg** [comment]
The change has been merged to master now.
