### ISSUE TITLE
Clear up use of dimensions vs. units

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#797]
I was looking into the time that is spent during run preparation (which becomes relevant when using many short runs) and noticed that a significant time is spent in the `get_unit` function, e.g. to get the unit of external constants. Now, that function can certainly be optimized (e.g. with caching), but I realized that in most cases it is doing something unnecessary in the first place: we are interested in the *dimensions* (to check consistency) and do not need a `Unit` object.
It actually seems to me that most of the places where we store units should actually store dimensions instead, most importantly state variables. The only additional information a `Unit` stores in addition to the dimensions is a scale and a string name. However, state variables are always stored in the base scale and we cannot do much with the string name either, since our `Quantity` objects only store dimensions, not a unit.
So for example whether you define a variable as having units of `Hz` or `second**-1` *will* have an effect (it is stored differently), but as soon as you access the its values, you will get a `Quantity` that no longer has this information. When you print it, we will again search for a "nice" unit, but this does not depend on what unit was used for the definition in the first place.

So I wonder: should we get rid of most instances where units are currently stored (and going with that, most calls of `get_unit`) and instead store dimensions? For some use cases, this might have a noticeable effect on performance and I don't see us losing much -- whenever we display stuff to the user, i.e. when we transform things to strings, we use something like `in_best_unit` anyway.

Anything that I missed here?

PS: For the transition, we should probably keep a `unit` attribute around in places where we had it before to avoid breaking user code relying on it.

**Comment by thesamovar** [comment]
This seems very sensible to me. Actually storing dimensions is more logical than units, so if it also has a performance benefit: great!
