### ISSUE TITLE
linear `event-driven` variables sometimes cannot be integrated

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#801]
As reported [on the mailing list](https://groups.google.com/d/msg/briansupport/drwbP1s_cC8/b23Ds5BSEAAJ), exact integration for synaptic `event-driven` variables sometimes fails. We integrate such equations with the `independent` state updater which uses sympy's `dsolve` method which itself has a variety of methods available. In the reported case, sympy uses the solver called `separate` which rarely (subtle changes in the equations can make all the difference) returns an implicit solution which leads Brian to fail with an error message.

I also realized that our `linear` solver is much faster than `independent` (which uses sympy's general `dsolve` method). For the kind of equations that we use in synapses (e.g. the `dApre/dt = -Apre/taupre` of STDP) this actually makes a difference of ~25ms vs. ~140ms.

So my proposal is:
* for `event-driven` equations, use `linear` instead of `independent`
* if the former fails, re-try using `independent`

This should make things both more stable/predictive *and* faster in the majority of use cases. It slows things down ever so-slightly for `event-driven` variables that are non-linear but can still be solved analytically (say, `'dApre/dt = -Apre*sin(t) / tau`). This slow-down should be really minor, though (figuring out that the equation is not linear is fairly quick) and I don't know of any real-world use-case for that, anyway...

I'll open a PR for that change soon.

**Comment by thesamovar** [comment]
Is there a case for just using linear and not trying independent?

**Comment by mstimberg** [comment]
> Is there a case for just using linear and not trying independent?

I considered it, but there is the faint possibility that this would break someone's code, with no straightforward way to do something about it (i.e. it is not just a matter of adding a keyword or something like that). I don't see much that we'd gain from it in this specific case, but in the long run we might consider throwing out the `independent` updater completely, just to remove code that is most likely never used (the `independent` updater is never chosen for the user automatically, so I doubt many users know that it exists...).

**Comment by thesamovar** [comment]
Sounds reasonable to me.
