### ISSUE TITLE
Int devision typo in elapsed time measurement in cpp standalones Network::run?

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#804]
Parenthesis in [this line](https://github.com/brian-team/brian2/blob/master/brian2/devices/cpp_standalone/templates/network.cpp#L77) look wrong. Shouldn't it be
```c++
const double elapsed = (double)(current - start) / CLOCKS_PER_SEC;
```
instead of 
```c++
const double elapsed = (double)((current - start) / CLOCKS_PER_SEC);
```
Or is the latter performance wise faster and it doesn't really matter, since this is just the report functions time?

**Comment by mstimberg** [comment]
Thanks, well spotted! This was definitely not intended (I strongly doubt it will have any measurable impact on performance), but since it does not make any difference when the reporting time is an integer number of seconds I don't think that anyone was really affected by it. Fix is on its way.
