### ISSUE TITLE
How to get string represention of  units

### ISSUE THREAD

**Issue by Cody-G** [brian-team/brian2#807]
Hi, thanks for your work on Brian2!  I'm beginning to write a simple wrapper to call Brian2 from Julia.  One sticking point is translating the units of Brian2 Quantity instances.  I've been looking for an interface to get the string representation of a unit in Brian2 (i.e. a way to take a unit or a Quantity like 10 * ms and return "ms").  Is there some way to do this that I'm missing?  Thanks!

**Comment by mstimberg** [comment]
There are various ways to get units for a quantity, depending what you need. First to get terminology straight: a quantity has a numerical value and physical dimensions. What I mean by this is that both `10*ms` and `0.01*second` are represented by `0.01` with dimensions of time. What we call a "unit", is a name + dimensions + a scale, e.g. `ms` is a unit with the same dimensions as `second`, but with the scale 0.001 and not 1.
So it depends what you need, the most straightforward (and computationally cheap) way to separate value and dimensions is to use:
```Python
# q is a quantity
value = np.asarray(q)  # for a scalar value, you can also use: float(q)
dimensions = q.dim
```
You can convert the dimensions to a string with `str` or `repr` -- the difference is that `str` gives you something nicer for display (e.g. `s` for second), wheras `repr` gives you the fullname (i.e. `second`). Now this works fine for values with simple dimensions, but it might not be what you want for e.g. voltages:
```Python
>>> q = 10*mV
>>> str(q.dim)
'm^2 kg s^-3 A^-1'
>>> repr(q.dim)
'metre ** 2 * kilogram * second ** -3 * amp ** -1'
```
This is all correct and you could use it programmatically, but for display you might indeed be interested in a unit. So what you can do in this case is to ask Brian to find a nice unit for the value (remember that the quantity internally does not store any such unit):
```Python
>>> q = 10*mV
>>> u = q.get_best_unit()
>>> str(u)
'mV'
>>> v = q/u
>>> v
10.0
```
Note that `Quantity.get_best_unit` currently only exists in github master, in version 2.0.1 it is still called `Quantity._get_best_unit`.


PS: I'm closing the issue as this is not really a bug/new feature -- this kind of question is better suited for the [brian-development mailing list](https://groups.google.com/forum/#!forum/brian-development) (brian-development@googlegroups.com) in general. But please feel free to post follow-up comments here if something is still unclear.

**Comment by Cody-G** [comment]
Thanks for your very thorough reply!  That clears things up nicely.  I'll post in the mailing list if I have any more questions like this (and I probably will).
