### ISSUE TITLE
str_to_sympy converts integers into floats

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#812]
When converting a string to sympy (i.e., for use in equations), all integer literals are transformed to float literals and when variables are involved in certain operations, they are multiplied by 1.0. E.g.:
```Python
>>> from brian2 import *
>>> from brian2.parsing.sympytools import str_to_sympy
>>> from brian2.core.variables import ArrayVariable
>>> str_to_sympy('1 + i % 25', variables={'i': ArrayVariable('i', None, 100, get_device(),
...                                                          dtype=np.int32)})
Mod(1.0*i, 25.0) + 1.0
```

We do of course rarely deal with integers in differential equations and if we do, it normally doesn't make a difference whether they are represented as integers or as equivalent floating point variables. It *could* make a difference though e.g. when the user wants to use integer division in an equation:
```
dv/dt = (i/100) / second : 1
```

To do this properly, we also have to take care of functions that return integers. E.g. even the following workaround does not work at the moment:
```
dv/dt = (int(i)/int(100)) / second : 1
```
Since sympy does not know that these are integers and that there is anything special about integer division it will happily convert this to:
```
int(i)/(second*int(100.0))
```
which defeats the purpose.

You could of course use `int(i/100)` here, but this is still different from other places (e.g. synaptic `connect` calls) where it will use integer division without any explicit `int` call.

I think it is important that sympy does not screw with the type of literals/variables (we take some care to not do this in our code gen pipeline), but there's also the somewhat orthogonal question of how to deal with integer division. Currently, we use C/Python2 semantics and have example where we use this e.g. to arrange neurons in a grid (something like `x = i / gridsize`, `y = i % gridsize`).

Maybe it would be better to make this clear once and for all and use `/` for floating point and `//` for integer division as in Python 3? We have to be careful when introducing this, e.g. use multiple steps with a `FutureWarning` that the semantics will change and later a warning when the semantics did change. This certainly needs some careful thought and implementation (it is also related to #661 )

**Comment by thesamovar** [comment]
Another possibility would be to shield all integer subexpressions from sympy, i.e. any subexpression that matches as integer would be replaced by a named variable and so there wouldn't be any simplifications involving it, and then at the end that named variable would be replaced by the original expression. Bit convoluted, but probably matches intended behaviour. Also easy to explain: sympy will simplify any float expression but not any integer expression. I'm hesitant to introduce the Python 3 semantics while we still support Python 2, because many people won't have encountered it.

**Comment by mstimberg** [comment]
Ugh, I already wrote a reply but apparently I never sent it, so here we go again...

> Another possibility would be to shield all integer subexpressions from sympy, i.e. any subexpression that matches as integer would be replaced by a named variable and so there wouldn't be any simplifications involving it, and then at the end that named variable would be replaced by the original expression. Bit convoluted, but probably matches intended behaviour.

We might have to do something like this, even though it adds another layer of ugliness to our already quite convoluted parsing/rendering... In principle, sympy should be able to handle all this, since you can define integer symbols/functions/literals. However, everything except numbers does not seem to work:
```Python
>>> from sympy import Integer, Symbol
>>> Integer(1) // Integer(100)
0
>>> Symbol('i', integer=True) // Integer(100)
Traceback (most recent call last):
...
TypeError: Integer can only work with integer expressions.
```
Maybe I'll open a sympy issue about this...


> I'm hesitant to introduce the Python 3 semantics while we still support Python 2, because many people won't have encountered it.

I am not sure what to do here either. I tend to think that possibly we have more errors due to the unexpected `1/2 == 0` equivalence than users consciously making correct use of integer division. Also, according to the anaconda download stats for our latest Brian 2 release, 45% of our users are actually using Python 3!
This needs more thorough investigation, but I just realized that we already have a bug in Brian 2 where division gives different results, depending on the codegen target and Python 2 vs. 3.
I'll open a separate bug report about this!
