### ISSUE TITLE
Handle `_pre` and `_post` variables in `Synapses` model

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#818]
Just did a little test after @mstimberg mentioned concerns for using `*_pre` and `*_post` variables in `Synapses` models. And it is quite confusing, especially when using a variable `A` in a `NeuronGroup` and connecting it in a `Synapses` object with variable `A_pre` or `A_post`, since it is not clear which variable is going to get modified if we have `on_pre = 'A_post = ...'`
Take e.g. this script
```python
from brian2 import *

G = NeuronGroup(1, 'A : 1', threshold='True')
S = Synapses(G, G, model='A_post : 1', on_pre='A_post += 1')
S.connect()
run(defaultclock.dt)

print('G.A = {}'.format(G.A[:]))
print('S.A_post = {}'.format(S.A_post[:]))                   

```
which produces this output
```
G.A = [ 0.]
S.A_post = [ 1.]
```
But one could have wanted to change the `NeuronGroup` variable instead. I guess it would be good to at least produce a warning or even not allow `_pre` or `_post` variables in `Synapses` models as @mstimberg  suggested?

**Comment by thesamovar** [comment]
Yeah I would tend to say that banning ``_pre`` or ``_post`` on synaptic variables (or maybe all variables for consistency?) would be the most logical approach.

**Comment by mstimberg** [comment]
> Yeah I would tend to say that banning _pre or _post on synaptic variables (or maybe all variables for consistency?) would be the most logical approach.

I agree, I'd be happy to ban it for all variables (imagine having a variable `x_pre` in a `NeuronGroup` and then referring to `x_pre_pre` or `x_pre_post` in the `Synapses`...). I *really* thought we were already doing that :-/
