### ISSUE TITLE
Documentation for `standalone-only` unit tests wrong?

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#819]
The [latest docs for writing unit tests](http://brian2.readthedocs.io/en/latest/developer/guidelines/testing.html#unit-tests) give wrong instructions for the use of `device` when setting up `'standalone-only'` tests. Just before the Summary section, the example is
```python
from nose import with_setup
from nose.plugins.attrib import attr
from brian2 import *
from brian2.devices.device import reinit_devices

@attr('cpp_standalone', 'standalone-only')
@with_setup(teardown=reinit_devices)
def test_cpp_standalone():
    set_device('cpp_standalone')
    # set up simulation
    # run simulation
    device.build(...)
    # check simulation results
```
and in the Summary section it says under "explicit use of `device`":
```python
set_device('cpp_standalone')
...
device.build(directory=None)
```
But  I think either one is wrong, it either needs
```python
set_device('cpp_standalone', directory=None)
```
or
```python
set_device('cpp_standalone', build_on_run=False)
... 
device.build(directory=None)
```
I am using [this commit](fadc6a0aeb90d1b4d343470628457d8561536f67). I think this should already incorporate the changes to the testing system for devices?

**Comment by mstimberg** [comment]
Yepp, this is indeed incorrect. I think I'll include both options you mention.
