### ISSUE TITLE
multi-layer spiking neural network

### ISSUE THREAD

**Issue by ImQianYang** [brian-team/brian2#831]
Hi. I intend to construct a multi-layer spiking neural network for hand-written numeral recognition. I am a little confused about distinguishing different weight variables between different layers. Could you please show me an example on how to set up this kind of network?

**Comment by thesamovar** [comment]
Questions like this should be posted to the email support list. In this case, I'm not sure you'll get much of a response because the question is too open ended.

**Comment by mstimberg** [comment]
Agree with everything what Dan said. Apparently SNNs for the MNIST data set are a hot topic nowadays, so I'll put this here for further reference nevertheless. There is a paper that used Brian to do the MNIST task with a spiking network:
http://journal.frontiersin.org/article/10.3389/fncom.2015.00099/abstract#
An attempt to make it work for Brian 2 is here (can't tell you whether it is properly working or not): https://github.com/zxzhijia/Brian2STDPMNIST
