### ISSUE TITLE
Conda install: UnsatisfiableError (Python 3.6)

### ISSUE THREAD

**Issue by mgiugliano** [brian-team/brian2#846]
I get

`UnsatisfiableError: The following specifications were found to be in conflict:
  - brian2 -> numpy 1.10* -> python 2.7* -> openssl 1.0.1*
  - python 3.6*`

upon typing `conda install -c brian-team brian2`. The install via conda is therefore not successful.

conda 4.3.21
Python 3.6  (Anaconda 4.3.1 for macOS)

**Comment by mstimberg** [comment]
Hi. We currently don't have a conda package for Python 3.6, that's why the installation fails. Our last Brian2 release was made before Python 3.6 was released. You can create a Python 2.7/3.5 conda environment and install Brian2 there, or use your 3.6 environment and install Brian via `pip install brian2`. We will do a new Brian2 release within the next three weeks, this will include packages for Python 3.6 (but drop support for Python 3.4).

**Comment by mstimberg** [comment]
This should now be fixed, the latest 2.0.2 release comes with conda packages for Python 3.6.

**Comment by mgiugliano** [comment]
Thanks. I am in debt with your team for your help and support.

Michele
________________________________

**Comment by mgiugliano** [comment]
The Brian2tools can't still be installed via Conda
M

Sent from a microscopic (touch) keyboard.
________________________________

**Comment by mstimberg** [comment]
> The Brian2tools can't still be installed via Conda

Indeed, we didn't have a brian2tools release in a while... It would probably make sense to have a release just for the conda packaging, I'll look into this.

**Comment by mstimberg** [comment]
FYI: I just released a new brian2tools version (0.2.1.1), installation should now work for Python 3.6 as well.

**Comment by mgiugliano** [comment]
Do you come to Antwerp for the CNS2017?
If so, a Belgian beer awaits you (and Romain, Pierre, et al. of course).
M

**Comment by mstimberg** [comment]
Ah, sounds great, but I won't come to CNS this year (I'll be in Okinawa at that time). Romain and Pierre both come, though, I'm sure they'll happily drink a beer for me ;)

**Comment by fuadfukhasyi** [comment]
I am installing brian2 using anaconda python 3.6. the anaconda has been successfully installed but when I install brian2 (conda install -c brian-team brian2), I found this conflict:
Solving environment: failed

UnsatisfiableError: the following spesifications were found to be in conflict:
  - anaconda -> mkl-service==1.1.2=py36h10c1010_4
  - anaconda -> numexpr==2.6.4=py36h51df984_0
  - anaconda -> scikit-learn==0.19.1=py36hb0057d7_0
  - brian2
Use "conda info <package>" to see the dependencies for each package

Thank you,

**Comment by mstimberg** [comment]
Please let's discuss this issue further in #930 (it's not about Python 3.6, Brian has had packages for this Python version for quite a while now). I cannot reproduce your problem on my machine, I can install the listed packages together with brian2, it only needs to downgrade numpy. Maybe another package is preventing a numpy downgrade? As commented in #930, could you try to explicitly downgrade to numpy 1.13 (`conda install numpy==1.13`)?

**Comment by fuadfukhasyi** [comment]
![image](https://user-images.githubusercontent.com/37688299/37832403-bd434712-2e65-11e8-8d86-e25e4b231f80.png)

**Comment by mstimberg** [comment]
(Please, take this over to #930, I'll lock this issue here)
Ok, the culprits seem to be blaze and numba. You can either remove those packages, or create a new environment for Brian without these packages (see #930).
