### ISSUE TITLE
time does not update in variable assignment

### ISSUE THREAD

**Issue by ffa** [brian-team/brian2#847]
Hi,

The time, ```t```, does not update in the following code. Also, note that plain assignment ```G.tat = ta2d```, raises an error. Plain assignment used to work in Brian, but it does not seem to work with Brian2.

```
from brian2 import *
ta2d = TimedArray([[1, 2], [3, 4], [5, 6]]*mV, dt=0.1*ms)
print ta2d(0.1*ms,0)
G = NeuronGroup(4, '''v = tat : volt
tat : volt''')
G.tat = 'ta2d(t, i%2)'
mon = StateMonitor(G, 'v', record=True)
net = Network(G, mon)
net.run(0.2*ms)  

print mon.v[:]
```

The output is
```
[[ 1.  1.]
 [ 2.  2.]
 [ 1.  1.]
 [ 2.  2.]] mV
```

however, the correct output is
```
[[ 1.  3.]
 [ 2.  4.]
 [ 1.  3.]
 [ 2.  4.]] mV
```

**Comment by mstimberg** [comment]
Hi. You are only setting the initial value with the `TimedArray`, it will not be used during the simulation. Your code should read (no need to introduce a new `tat` variable):
```Python
G = NeuronGroup(4, '''v = ta2d(t, i%2) : volt''')
```
See: http://brian2.readthedocs.io/en/latest/introduction/brian1_to_2/inputs.html#arbitrary-time-dependent-input-timedarray

**Comment by ffa** [comment]
Hi mstimberg, my use case needs to be able to introduce a new variable. Otherwise, depending on the type of input, spikingsource or timedarray, I would have to modify the eqs for the NeuronGroup.

Also, is it not considered a bug that time, ```t```, is not updating? It is broken functionality if the time, ```t```, variable is available, but does not work.

**Comment by mstimberg** [comment]
> Hi @mstimberg , my use case needs to be able to introduce a new variable. Otherwise, depending on the type of input, spikingsource or timedarray, I would have to modify the eqs for the NeuronGroup.

Why is modifying the equations of the NeuronGroup not an option? You have to modify *something* to make the change. Either way, there is an alternative if you want to keep the same equations: you can use a `run_regularly` operation (http://brian2.readthedocs.io/en/stable/user/input.html#regular-operations) :
```Python
G = NeuronGroup(4, '''v = tat : volt
                      tat : volt''')
G.run_regularly('tat = ta2d(t, i%2)', dt=0.1*ms)
```

> Also, is it not considered a bug that time, t, is not updating? It is broken functionality if the time, t, variable is available, but does not work. The variable t should be working in G.tat = 'ta2d(t, i%2)'.

It would be considered a bug, if `t` did not update, but `t` *does* update, and the correct value of `t` is taken into account in assignments. You are doing a single assignment that sets the initial value of `tat`, based on the current value of `t` (which is `0s` at that point). It is only evaluated once, in the same way as other initializations. E.g. the [CUBA example](http://brian2.readthedocs.io/en/stable/examples/CUBA.html) initializes `v` via:
```Python
P.v = 'Vr + rand() * (Vt - Vr)'
```
This means that the value of `v` is set to a random value at this point -- not that it is set to a random value at every time step. For doing assignments repeatedly, you can use the `run_regularly` function as shown above.

**Comment by ffa** [comment]
I understand. I appreciate the detailed help you provided. Thank you.

Also, I look forward to the first release of Brian2GeNN. You and the Brian team have been doing well thought out work, the documentation has been clear and concise, and all of that has made my work considerably easier.

**Comment by mstimberg** [comment]
I see. Thanks for the warm words - much appreciated!
