### ISSUE TITLE
File write warning

### ISSUE THREAD

**Issue by zifeo** [brian-team/brian2#851]
Environment: osx, Brian 2.0.1, python 3.6.1 (brewed)

```shell
WARNING    /usr/local/lib/python3.6/site-packages/brian2/codegen/runtime/cython_rt/extension_manager.py:190: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/*****/Library/Caches/cython/brian_extensions/_cython_magic_ee4485027de5d7cd3fc6280fc6e18bb2.pyx' mode='w' encoding='UTF-8'>
  open(pyx_file, 'w').write(code)
```

Would `with` be an issue [here](https://github.com/brian-team/brian2/blob/master/brian2/codegen/runtime/cython_rt/extension_manager.py#L190) ?

**Comment by mstimberg** [comment]
Yes that would indeed be clearer, we currently rely on CPython's garbage collection to close the file but this is an implementation detail and not a language feature, we should not rely on it. Would you be interested in fixing this with a pull request?

**Comment by mstimberg** [comment]
Actually this is not the only place where we are doing this. It would be nice to fix all of them in one go, I guess...

**Comment by nik849** [comment]
I would be happy to give this a go

**Comment by mstimberg** [comment]
Hi @zifeo and @nik849 : is one of you still interested in fixing this?
