### ISSUE TITLE
Exact integration fails with sympy 1.1

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#856]
The latest sympy version seems to break the exact integration. The symbolic solution involves a call of `as_explicit` on the sympy matrix. This fails with an error message that seems to be a bug in sympy:
```
...
File ".../sympy/matrices/expressions/matmul.py", line 67, in _entry
    if not X.cols.is_number:
AttributeError: 'int' object has no attribute 'is_number'
```

I don't see any straightforward way to fix this right now, I consider just doing a quick release that requires sympy < 1.1.

**Comment by thesamovar** [comment]
That seems like a reasonable short term solution!
