### ISSUE TITLE
neuron cannot be reset.

### ISSUE THREAD

**Issue by Snow-Crash** [brian-team/brian2#860]
I was writing a linear neuron model. The membrane potential increases over time
v = 0.1 * t, where t is time, and neuron's threshold is 0.3. 
Following is my code
I plot the result. v does increase as a linear function of t, but neuron cannot be reset. v continues incresing even if v is greater than threshold. I check spike monitor and find that neuron keeps firing after t = 30, it seems that neuron cannot be reset after fire.
Did I make something wrong?  Thank you!
```
from brian2 import *
prefs.codegen.target = "numpy"
start_scope()
tau = 10*ms
eqs = '''v =  t * 0.1/tau : 1'''
G = NeuronGroup(1, eqs, threshold='v > 0.3', reset = 'v = 0', method='linear')
M = StateMonitor(G, 'v', record=0)
spikemon = SpikeMonitor(G)
run(50*ms)
plot(M.t/ms, M.v[0])
xlabel('Time (ms)')
ylabel('v');
```

**Comment by thesamovar** [comment]
Hi,

First of all, for questions like this can you please use the email support list.

You can't write ``v=t*0.1/tau`` and ``v=0``: they're inconsistent. You might try ``dv/dt=0.1/tau`` which might have the effect you're looking for?
