### ISSUE TITLE
brain2 

### ISSUE THREAD

**Issue by YangBain** [brian-team/brian2#861]
I want to update the brian1 code to brian2, but when I run the code the problem occurred, "AttributerError: module "brian2" has no attribute "set_global_preferences"". So for this problem, where can I find the answer. Also about the brain_no_units for brian2. Thank you very much.

Bin Yang

**Comment by thesamovar** [comment]
Hi,

Please could you use the email support group for questions like this in the future.

Here's a general guide to converting Brian 1 to Brian 2 scripts: http://brian2.readthedocs.io/en/stable/introduction/changes.html

And the new preferences system: http://brian2.readthedocs.io/en/stable/advanced/preferences.html
