### ISSUE TITLE
Guide on converting integrated form equations to ODE form

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#863]
We are sometimes asked about how to convert kernel defined synapse equations into the ODE form used in Brian, and I don't think we have a nice short guide on how to do this anywhere. For the moment, we can point people to section 2.2 of our paper "Vectorised algorithms for spiking neural network simulation":

http://www.briansimulator.org/WordPress/wp-content/uploads/2010/10/algorithms-preprint.pdf

However, this should probably be included in the Brian docs somewhere.

**Comment by mstimberg** [comment]
This reminds me: we actually have some indirect (and quite hidden...) documentation of typical synapse models (exponential, bi-exponential, alpha) as part of the Brian 1->2 conversion guide: http://brian2.readthedocs.io/en/stable/introduction/brian1_to_2/library.html#synapses

**Comment by thesamovar** [comment]
Ah nice. Maybe we should have a copy of this (without the Brian 1 details) somewhere in the user docs? We did discuss what to do about standard models in #45, but it doesn't look like we're making much progress on the approach we discussed there! :)
