### ISSUE TITLE
Ship support for GSL integrators directly in Brian 2?

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#866]
@CharleeSF is making good progress wrapping up her GSoC project on adding support for numerical integration with the GSL (most importantly adding support for variable time step integration -- of course still within the context of grid-based spike propagation, etc.). The way she wrote it makes it possible to either ship it as a separate module (i.e. something that needs to be installed separately like, say, `brian2genn`) or as part of Brian itself. I see some merits for both solutions: shipping it separately avoids a dependency on the GSL and simplifies testing, etc.; shipping it with Brian itself makes it more discoverable and more likely to be actually used.
I tend towards including it in Brian itself, to make sure that users are actually aware of it and using it, as well as avoiding problems of it getting out of sync with Brian's main code. In the long run, a dependency on GSL might be something useful anyway, e.g. for random number generation.

@thesamovar: What do you think?

Oh, one more point that might speak against its inclusion: currently, only C-based codegen targets are supported (i.e. weave, cython + C++ standalone), numpy does not work.

**Comment by thesamovar** [comment]
That's great news! Congratulations @CharleeSF!

I think it depends on how straightforward it is to add a dependency on GSL (remembering that it has to work on windows and mac as well as linux). I'd say if that can be made as painless as the current install process then yes, aiming at including it would be a great idea. For pure Python, could we not use the variable timestep numerical integrators included in scipy? https://docs.scipy.org/doc/scipy/reference/integrate.html I'd prefer to have it working on all targets even if it is somewhat slow in pure Python mode.

Another possibility is we release as a separate package immediately, but work towards full integration later.

**Comment by mstimberg** [comment]
I think using scipy's interface to the odepack integrators would be too different (slightly different interface, different solvers). A better solution would be to use an existing Python interface to the GSL or write a Cython wrapper -- it's just too late to do this as part of the GSoC (it's basically the final week)...

**Comment by thesamovar** [comment]
In that case (not much time remaining), I'd be in favour of releasing as a separate package and we can think about integration into Brian2 core later.

**Comment by mstimberg** [comment]
> In that case (not much time remaining), I'd be in favour of releasing as a separate package and we can think about integration into Brian2 core later.

Just to make this clear: in its current state, it is part of Brian2, i.e. releasing it as a separate package is the option that is more work :smile:

**Comment by thesamovar** [comment]
But maybe not releasing it 'properly'?

What about marking it as 'experimental' for the moment?

Dan

**Comment by mstimberg** [comment]
So I think my preferred approach would be: merge it into Brian2 master at the end of the GSoC (it should be in a state were it is useable and gives correct results, "fails properly" in situations it cannot handle, etc.) and decide about the final approach (internal vs. external package) and/or add numpy support before the next release.

**Comment by thesamovar** [comment]
That sounds fine to me, but let's do slap on a warning that it is experimental for people who use master and in case we don't get round to it before the next release.

**Comment by mstimberg** [comment]
GSL integration has landed in Brian 2 master (via #870).
