### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#876]
I wonder what we should do about the next release. We have not yet merged the caching PR (#832), and then of course there's @CharleeSF's work on the GSL integrator (#870).
While the GSL integration is working and basically ready to use (apart from numpy), it has a few uglinesses in the code due to the way Brian expected the state updater to be organized: originally, a state updater was code that turned equations+variables into abstract code, but the GSL integrator also needs to use a separate `CodeGenerator`, etc. This is currently done by directly manipulating the stored `codeobj_class` in the `StateUpdater`, adding stuff to its `variables` dictionary, etc. While this all works (and is documented), I fear that workarounds like this will lead to problems in the future, in particular in combination with the caching... I therefore wonder whether it would not be better to put the merge of the GSL integration on hold for now, and just merge the caching stuff and do a release.

The next step would then to rework a bit our code generation pipeline with the GSL integration in mind and finally refactor the GSL integration to work with it. Then, (maybe throwing in some numpy support on the way) we can integrate it cleanly and do a new release (maybe that would be the 2.1 release then).

Thoughts?

**Comment by thesamovar** [comment]
Yes, but it would be a shame if this meant that adding this work in to Brian ends up taking a very long time to be released. We could include it with hacks and all, but also bump up the priority of refactoring the codegen pipeline for the next major release.

**Comment by thesamovar** [comment]
I'd not be unhappy with that actually, because there are a number of other changes we might make to the pipeline as part of that refactoring, e.g. for the 'encapsulation' idea, etc.

**Comment by mstimberg** [comment]
> Yes, but it would be a shame if this meant that adding this work in to Brian ends up taking a very long time to be released. We could include it with hacks and all, but also bump up the priority of refactoring the codegen pipeline for the next major release.

I agree that it would be a shame for it to take a very long time. The reason I'm worried is that I fear that it will not work well with the caching system we want to merge as well, due to the changes it does to objects directly. But I just had a quick try merging everything together which was easier than expected and no tests fail, so maybe it's actually fine.
How about merging the caching PR now, and then merging master into the GSL branch to do more thorough testing? If we don't find any major problems, I'm fine merging it in the less-than-ideal current state and make codegen refactoring a priority for the next release. It does display a warning about being experimental, anyway.

**Comment by thesamovar** [comment]
Sounds perfect to me.

**Comment by mstimberg** [comment]
Obsolete with 2.1 release.
