### ISSUE TITLE
Remove "independent" state updater?

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#878]
The "independent" state updater can be used for systems of differential equations where all equations are independent of each other, and individual equations are analytically solvable but *not necessarily linear* (e.g. it could be something like `dx/dt = sin(2*pi*t*freq)/ms : 1`).

This state updater has sometimes led to problems in the past due to changes in sympy. But most importantly, I think I have never seen it in actual use except for the carefully crafted examples we use in the test suite. In addition, it has the same naming issue described in #877.

My vote would be to simply remove it (with an error that explains that it has removed instead of just failing with "unknown state updater"), or maybe just mark it as deprecated for now. But then, I honestly don't think anyone uses it.

**Comment by thesamovar** [comment]
Sure, mark it as deprecated and see if anyone complains. If so, we can reconsider.
