### ISSUE TITLE
Bad equations generation 2.1.0 regression

### ISSUE THREAD

**Issue by zifeo** [brian-team/brian2#896]
The following worked before the 2.1.0 release. No workaround found yet except reverting to 2.0.2.

```python
from brian2 import *
eqs = Equations(
    '''
    I = v * s : amp
    ds / dt = - s : 1
    ''',
    I='I1',
    s='s1',
)
eqs += Equations(
    '''
    I = v * s : amp
    ds / dt = - s : 1
    ''',
    I='I2',
    s='s2',
)
print(eqs)
```

In `Brian2==2.0.2.1`, it correctly outputs:

```
I2 = v * s2  : amp
I1 = v * s1  : amp
ds1/dt = - s1  : 1
ds2/dt = - s2  : 1
```

In `Brian2==2.1.1`, it sadly outputs (notice the `s1` replacing `s2`):

```
I2 = v * s1  : amp
I1 = v * s1  : amp
ds1/dt = - s1  : 1
ds2/dt = - s1  : 1
```

**Comment by mstimberg** [comment]
Many thanks for the report. I'll look into this as soon as possible.

**Comment by mstimberg** [comment]
@zifeo, I just pushed an `equations_bug_#896` branch that should fix the issue, could you try it out with your "real life" use case?

**Comment by zifeo** [comment]
@mstimberg Just verified, the fix works fine. Thanks for the reactiveness!
