### ISSUE TITLE
Monitor created inside dictionary doesn't detect events

### ISSUE THREAD

**Issue by MariaCervera** [brian-team/brian2#904]
I am trying to create dictionaries where to store the states/spikes of the neurons. When creating the monitors directly in the dictionaries, they don't seem to keep track of what is going on in the network. However, if I create a variable and assign it to a key in the dictionary, it works fine.

This works:
`statemonitor = StateMonitor(neuron, 'v', record = 0)`
`statemonitors = {'neuron': statemonitor}`

This doesn't work:
`statemonitors =  {'neuron': StateMonitor(neuron, 'v', record = 0)}`

Why is this the case and how can I circumvent this issue?
Thank you

**Comment by mstimberg** [comment]
When you use the `run` command, you use Brian's so-called "magic" system, where it tries to figure out which elements take part in your network. It does this by looking at all objects that are directly "visible" at the point where you call `run`. In your first example, it finds `statemonitor` and includes it, in the second it only sees `statemonitors` which is not a "Brian object". The solution is to explicitly create a `Network` object and add everything to it. The documentation mentions the issues of containers and how you can use `collect()` to make the creation of the `Network` easier: http://brian2.readthedocs.io/en/stable/user/running.html#networks
In your case:

```Python
net = Network(collect())
net.add(statemonitors)
net.run(...)
```
should be all you need.

**Comment by MariaCervera** [comment]
Yes, that works perfectly fine now.
Thanks a lot for the explanation and the reference.
