### ISSUE TITLE
Broken links in the "Edit on Github" tab

### ISSUE THREAD

**Issue by Dyex719** [brian-team/brian2#908]
There are several broken links in the "Edit on Github" tab at the top of the webpage in following sections:
http://brian2.readthedocs.io/en/stable/introduction/install.html
http://brian2.readthedocs.io/en/stable/index.html
http://brian2.readthedocs.io/en/stable/resources/tutorials/index.html
http://brian2.readthedocs.io/en/stable/examples/index.html
http://brian2.readthedocs.io/en/stable/introduction/support.html

**Comment by Dyex719** [comment]
I would open a PR, but the html files aren't available here..

**Comment by mstimberg** [comment]
Hi, thanks for the report. These HTML files are generated by the readthedocs, the broken links are a known issue: rtfd/readthedocs.org#1820
It seems to have been fixed recently (rtfd/readthedocs.org#3302), so it will probably work for the stable version as soon as we do a new release. The version from master (i.e. "latest" on readthedocs) already seems to be fine, see e.g. http://brian2.readthedocs.io/en/latest/introduction/install.html

**Comment by mstimberg** [comment]
This has been fixed in readthedocs now.
