### ISSUE TITLE
How to set parameter so that Brian can update it pulselike?  

### ISSUE THREAD

**Issue by porridgeshoes** [brian-team/brian2#912]
hello,everyone.
If there is a presynaptic neuron A and a postsynaptic neuron B . neuron B has a parameter ''g'', the initial value of ''g'' is 'g0'.
my question is how to use BRIAN to make that:
when neuron A  firing, parameter ''g'' change to 'g1' and  lasts T*ms. And after T*ms, parameter ''g'' returns to 'g0'. Namely that parameter ''g'' is 'g1' only in the period that after neuron A firing, the rest of the time parameter ''g'' is 'g0'.
thanks a lot.

**Comment by mstimberg** [comment]
Hi,
for questions like this, please use the mailing list in the future.

The easiest way to model this in Brian is with [two synaptic pathways](http://brian2.readthedocs.io/en/stable/user/synapses.html#multiple-pathways), one with a delay `d` (or just 0), and one with a delay `d + T`. The first pathway is responsible for making the target variable go up, the second for making it go down. Something along these lines should work:
```Python
d = 0*ms
T = 5*ms
syn = Synapses(A, B, on_pre={'up': 'g_post = g_1', 'down': 'g_post = g_0'},
               delay={'up': d, 'down': d+T})
syn.connect(...)
```

Now this model means that a second spikes in A that arrives less than `T`ms after a first one will be ignored. You can tweak the model to get a different behaviour if that's not what you want.
