### ISSUE TITLE
Reduce the size of the Cython cache

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#914]
After running a lot of code with various versions of Brian, in particular the test suite, the Cython cache directory fills up with a lot of files. While disk space is not a major issue in general, a couple of GBs of cache can be annoying, especially on relatively small SSDs.

There's one relatively easy thing that we could to improve things: Currently, we write a `.pyx` file to disk, transform it into a `.cpp` and then compile it to a `.o` and `.so` file (named differently on Windows, I guess). All we need later is the `.so` file -- this is the module we import. For debugging purposes it can sometimes be useful to have the actual source files around, but it could be made optional via a preference. Deleting everything we don't need would make quite a difference. For example, when I run the `CUBA.py` example with Cython, it creates 10 code objects. With all the huge files that Cython tends to create, this already takes ~18MB of space. When I delete everything except for the `.so` files that are needed to avoid later recompilation, then we are down to ~4M, i.e. quite a significant decrease.

A more complex problem is to keep this cache from continuously growing. We can't run any kind of regular "cleanup code", but we could delete old code whenever we create new code, depending on some criterion about the size of the cache. Checking the actual disk size would be too costly, but just limiting the number of cached code objects might be enough. Unfortunately it would mean to also keep track of the use of the code (we don't want to delete a code just because it was created a long time ago, it should have been *used* a long time ago). A single text file or similar would be good enough for this, but it needs some serious thought to avoid the errors that weave made (e.g. stuff got slower with the number of code objects that were cached, updating the database was not threadsafe). An easier solution to doing this "online" might be to have a warning after a certain number of cache entries (e.g. checked at import time) and to provide an explicit "offline" command to clear old elements from the cache.

**Comment by thesamovar** [comment]
I like that last idea - I think that would be the best solution.

**Comment by mstimberg** [comment]
> I like that last idea - I think that would be the best solution.

I agree, a manual offline cleanup would be more in the spirit of Brian and is less difficult to implement (no need to worry about multithreading, etc.). We could still keep track of the use of cache elements to allow the user to do a fancy "delete everything but the last 1000 entries", but this would still be tricky do do get right (again, multhreading, etc.) I tend towards a simple solution, something where we don't track usage at all, and just check the number of elements in the cache directory at import time (configurable via a preference) + a warning if the number exceeds some threshold. For convenience, we can provide a `clear_cache()` command, but it would just delete everything from the respective directory.
