### ISSUE TITLE
Linked variables that link to scalar variables are not handled correctly

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#916]
It can sometimes be useful to link to a variable in another group that only has one "neuron" in it, e.g. to model shared noise or stimulation. We support this in general:
```Python
single = NeuronGroup(1, 'dx/dt = 0*Hz : 1')
neurons = NeuronGroup(10, 'x : 1 (linked)')
neurons.x = linked_var(single, 'x')
```
The `x` variable in `neurons` is automatically handled as a shared/scalar variable, i.e. with a single value for all neurons:
```pycon
>>> neurons.x
<neurongroup.x: 5.0>
```
However, it seems we do not correctly set the scalar flag of the variable:
```pycon
>>> neurons.variables['x'].scalar
False
```
This makes things fail if you create a subgroup of `neurons`:
```pycon
>>> neurons[:5].x
...
IndexError: index 1 is out of bounds for axis 0 with size 1
```
It also makes referring to the variable `x` from a `Synapses` object from/to `neurons` impossible.

I did a quick test, and setting the scalar attribute seems indeed to be enough to fix these issues.

**Comment by thesamovar** [comment]
I like these little issues that contain a solution to the problem. :)
