### ISSUE TITLE
Easy way to walk a large morphology to set different state parameters?

### ISSUE THREAD

**Issue by ckemere** [brian-team/brian2#919]
I'm trying to set up a model of an axon in which myelinated internodes have different channel properties. I understand that I can do:
```
neuron2.AIS.Internode0.Node0.Internode1.main.set_states({'gNax':500e-12*siemens/um**2})
```
But this seems super clunky to do for each segment. So I figured I'd walk my morphology like this:
```
node = neuron2.morphology
while node.total_sections > 1:
    print(node, node.total_sections)
    if node.type is 'Internode' :
         # do something
    node = node.children['1']
```
But I can't figure out how to get from the morphology to the SpatialSubgroup it represents. Advice?

**Comment by mstimberg** [comment]
Hi. In general, our mailing list briansupport@googlegroups.com (or its [web interface](https://groups.google.com/forum/#!forum/briansupport) ) is a better place to ask questions. However, I agree that navigating large morphologies is somewhat cumbersome in Brian at the moment (our own work mostly involves very simple morphologies). If you have any syntax suggestions, I'd be happy to hear them!

I think what you did is currently the most straightforward way to access individual sections. The only step missing is that you can use a morphology object to index into the neuron. In your above example, this should work:
```Python
...
if node.type is 'Internode' :
    neuron2.gNax[node] = some_value
...
```
In general, something like:
```Python
neuron2.AIS.Internode0.Node0.Internode1.main.gNax = some_value
```
should be equivalent to:
```Python
morpho = neuron2.morphology
neuron2.gNax[morpho.AIS.Internode0.Node0.Internode] = some_value
```
What happens under the hood is that the morphology is asked for the absolute indices of the compartments in the respective section, and then these indices are used to index into the full vector that stores the state variable's values for all compartments. You can also ask for these indices explicitly and then reuse them later:
```Python
indices = morpho.AIS.Internode0.Node0.Internode.indices[:]
neuron2.gNax[indices] = some_value
```

**Comment by ckemere** [comment]
Accessing by index is the solution I was looking for, as a way to link back from a morphology object to its model parameters. I had ended up with this:
```
# Build NeuronStructure list while adding segments to morphology.
gNax_vector = [parameters[SegType]['gNax'] for SegType in NeuronStructure]
neuron2.set_states({'gNax':gNax_vector})
```
but it required me to make a separate list that is probably unnecessary.

Thanks for quick response and I'll now keep an eye on the mailing list!
