### ISSUE TITLE
When using subgroups in combination with 'summed' in c++ standalone, target neuron variables are not correctly set to zero due to indexing issue

### ISSUE THREAD

**Issue by AI-pha** [brian-team/brian2#925]
It might be a slightly exotic case, but when using subgroups with 'summed' in c++ standalone, target neuron variables integrate their input over time, in addition to summing them over synapses (as expected).

The following code reproduces the issue (with numpy everything works fine, with cpp, subgroup neuron 0 works fine, but 1 and 2 rise linearly instead of staying at 1*nA):
```python
from brian2 import NeuronGroup, Synapses, prefs,\
    StateMonitor, run, ms, us, nA, Hz, figure, plot, show, legend, set_device
#prefs.codegen.target = "numpy"
set_device('cpp_standalone')

dummy_neuron = NeuronGroup(1, "")
neurons = NeuronGroup(5, "Iin : amp", name='Neurons')
neuron = neurons[2:]

syn = Synapses(dummy_neuron, neuron, "Iin_post = 1*nA : amp  (summed)")
syn.connect(True)

statemon_neuron = StateMonitor(neuron, variables=['Iin'], record=True)

run(100 * ms, report='text')

figure()
plot(statemon_neuron.t / ms, statemon_neuron.Iin.T / nA)
legend(range(3))
show()
```
(I am aware that this example code is not a sensible use case for the 'summed' mechanism)

If you set e.g. `neuron = neurons[3:]`, both subgroup neurons fail to work, however if you set `neuron = neurons[:]`, all neurons work as expected.

The reason for that peculiar behaviour is that the zero resetting of `_ptr_array_Neurons_Iin` does not use the correct subgroup indexing and just loops from 0 to `_target_size`.
In the following cpp code (from synapses_summed_variable_Iin_post_codeobject.cpp), `_target_idx` only goes from 0 to 2 instead of from 2 to 4 (which is why subgroup neuron 0, which has index 2 here, works fine in the above example): 
```cpp
    // Set all the target variable values to zero
    for (int _target_idx=0; _target_idx<_target_size; _target_idx++)
    {
        _ptr_array_Neurons_Iin[_target_idx] = 0;
    }
```

(It is not an urgent issue for me at all, as there are plenty of ways to avoid getting into that specific situation, I just wanted to make you aware of it as I rather wouldn't want to touch the c++ code generation myself)

**Comment by mstimberg** [comment]
Many thanks for the bug report (again)! I think your analysis of the problem is correct (it not only affects C++ standalone, but also weave and Cython), but I'll try to look into it in more detail tomorrow.
