### ISSUE TITLE
Build conda packages on conda-forge

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#956]
As suggested by @rinaldoB in issue #940, we should probably add `brian2` to the [conda-forge](https://conda-forge.org/) infrastructure. It is just a matter of adapting the `meta.yaml` file that we have already so that it builds from the `pypi` release instead of from source.

For a while, we should probably still copy over the package to our `brian-team` channel, but we'd no longer mention it in the docs. An advantage of separating the packaging from our release system is that we can fix problems in the package build independent of our github code. Previously, it could happen that we had a problem in our travis or appveyor script that led to a failure to upload the package to the servers. The only way to fix it was to do a new release. If the conda packages are built and uploaded via conda-forge, we can fix such issues there without needing to do a full new release. As a last point, being present on `conda-forge` might give us a bit more visibility.

**Comment by thesamovar** [comment]
This all sounds good, although will it add work to have things in separate places?

**Comment by thesamovar** [comment]
OK let's do it then.

**Comment by mstimberg** [comment]
Packages are now on conda-forge: https://anaconda.org/conda-forge/brian2
