### ISSUE TITLE
Names in brian2.__init__ overwrite builtins

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#969]
The package file `brian2/__init__.py` does not only import modules from subpackages, but also does some work like checking the presence of all packages and the size of the code generation caches. This code defines a few names that get imported with a `from brian2 import *`, e.g. `name`, `target`, and most importantly `dir`. The latter is a Python builtin and this will therefore break code that uses it.

I think the easiest quick fix is to prefix all names that we use in `__init__.py` with an underscore. In the long run, we should probably also use `__all__` more consistently in general, to avoid adding names and modules that we use in internal code to the names that are imported with `from brian2 import *`. Currently, importing from `brian2` will for example add the modules `datetime`, `types`, and `sympy` to the namespace.

**Comment by thesamovar** [comment]
I'm not against listing everything explicitly in ``brian2.__all__``. The only bother would be units, but we can do it once and never touch it again.

**Comment by mstimberg** [comment]
Not sure, maybe listing everything in `brian2.__all__` is a bit too much -- but then, I guess we don't add new names that often? What I had in mind was more the recursive approach that we use e.g. here: https://github.com/brian-team/brian2/blob/master/brian2/units/__init__.py#L102
But maybe that gets a bit ugly in `brian2.__init__`?

**Comment by thesamovar** [comment]
Yeah I think it would be annoying to do it the first time, but then relatively little effort to add new things to ``brian2.__all__`` as we add new features. Also not against the recursive approach.
