### ISSUE TITLE
Correct installation instructions for Windows (32bit vs. 64bit)

### ISSUE THREAD

**Issue by nh17937** [brian-team/brian2#974]
Hi!
I am trying to install Brian for the first time (Windows 7 64-bit). I followed the installation guide from the website, installed Anaconda (32 bit), but when I try to install brian2 (or brian2tools) using conda-forge channel I got an error that the package cannot be found (please see the text below). When I try to install using brian-team channel it installs the brian 2.1.2 version, not the latest one. 

Error:
conda install -c conda-forge brian2
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current cha
nnels:

  - brian2

Current channels:

  - https://conda.anaconda.org/conda-forge/win-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-32
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by mstimberg** [comment]
Hi, we should indeed make this clearer in our documentation. conda-forge does not build packages for 32 bit systems, so there's no package for the `win-32` architecture. You can either install a 64 bit environment (any particular reason why you chose a 32bit environment instead?), or install the package with `pip install brian2` -- on pypi, we still provide binary packages ("wheels") for 32bit Windows.

**Comment by nh17937** [comment]
Hi,

Thank you very much for your reply!

Probably I have misunderstood something, but I installed 32-bit version because the installation guide (http://brian2.readthedocs.io/en/stable/introduction/install.html) in "Installation with Anaconda / Installing Anaconda" section says: "Download the Anaconda distribution for your Operating System. For Windows users that want to use Python 3.x, we strongly recommend installing the 32 Bit version even on 64 Bit systems".

**Comment by mstimberg** [comment]
Oh, :astonished: sorry about that! This advice is actually outdated, I didn't realize it is still there. It applied to Python 3.4, where (as stated in the instructions below) running it with 64bit Windows was a bit complicated. With Python 3.5 and 3.6 (the version you get if you download Anaconda now), this problem does not exist anymore and 64bit is indeed recommended.  I'll fix the documentation on this point.
