### ISSUE TITLE
Supporting reward-modulated STDP?

### ISSUE THREAD

**Issue by KyungsuKim42** [brian-team/brian2#980]
Hello,

I was looking for the SNN simulator that supports  reward-modulated STDP, in other words, three-factor learning rule for synaptic plasticity. 

Let me briefly introduce about reward-modulated STDP. In reward-modulated STDP, each synapse has an eligibility trace which traces its recent activity. The value of eligibility increases if pre-then-post spike occurs and decreases if post-then-pre spike occurs and exponentially decays over time. It works like STDP. Difference is that pre or post spike doesn't change the weight but eligibility only. The weight is changed when the reward signal (positive or negative) is broadcasted to each synapses. When reward signal is received, the weight of each synapse is updated by amount of eligibility multiplied by reward.

The feature that I needed but couldn't find from brian2 is the feature that enables updating weight when external or global event (receiving reward) is occured. I think brian2 now only supports weight updating when pre or post spike is occured. Tell me if I'm wrong.

This feature is important to my research, so I have willingness to add this feature by myself and contribute to this project. In that case, I would be happy if you guys guide me a little bit about where to start.

Thank you for reading

**Comment by mstimberg** [comment]
Hi, there have been a few mails about reward-based STDP on the [mailing list](https://groups.google.com/forum/#!forum/briansupport) (and/or on the [development list](https://groups.google.com/forum/#!forum/brian-development)), maybe some of the discussions can give you helpful pointers.

> The feature that I needed but couldn't find from brian2 is the feature that enables updating weight when external or global event (receiving reward) is occured. I think brian2 now only supports weight updating when pre or post spike is occured. Tell me if I'm wrong.

In principle this should already be possible with Brian, I can see several ways:
* A `run_regularly` operation running on the `Synapses` object
* A `Synapses` object targetting the `Synapses`, modulating their weights in the `on_pre` statements (`Synapses` that target `Synapses` are a bit of an odd thing, but our [astrocyte example](http://brian2.readthedocs.io/en/stable/examples/index.html#frompapers-stimberg-et-al-2018) already uses this feature).
* In the simplest case: have a short `run`, apply the reward, continue the `run`, etc.

It would be great to have an example in the documentation implementing such a mechanism, this seems to be something that many people are interested in.
