### ISSUE TITLE
Custom function dependencies are placed in cpp code multiple times

### ISSUE THREAD

**Issue by AI-pha** [brian-team/brian2#988]
I ran into the following minor problem with custom functions in cpp code generation:
When 2 custom functions with the same `dependencies` (passed as parameter to `@implementation()` ) are used in the same group, those dependencies are included twice into cpp standalone code resulting in a compilation error "redefinition of ..."

Maybe, `_add_user_function() `in cpp_generator.py could check if the exact same function is already there and not add it in that case?

Here is an example that reproduces the issue (`BinomialFunction` has the dependency `_randn`):
```python
from brian2 import BinomialFunction, NeuronGroup, set_device, run, ms

set_device('cpp_standalone')

test_neuron = NeuronGroup(1, 'x : 1')
test_neuron.namespace.update({'bino_1': BinomialFunction(10, 0.5),
                              'bino_2': BinomialFunction(10, 0.6)})

test_neuron.x = 'bino_1()+bino_2()'

run(1 * ms)
```

**Comment by mstimberg** [comment]
Thanks, I'll try to look into this soonish!
