### ISSUE TITLE
Problems with brian2 and py-cpuinfo v4.0 on Windows

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#990]
There is a bug in py-cpuinfo 4.0 on Windows (reported at https://github.com/workhorsy/py-cpuinfo/issues/108) that causes issues with Brian on Windows. We should set our version requirement to ``<=3.3.0`` (the previous release) until the bug is fixed in py-cpuinfo.

**Comment by thesamovar** [comment]
I'll leave this issue open until we know what py-cpuinfo will do. It might be that they don't fix it in a future version, in which case we'll need a better workaround.

**Comment by mstimberg** [comment]
Yes, I was maybe a bit too optimistic, I hadn't seen the latest response before making the change. Maybe directly change the dependency to `<4` to be safe?

**Comment by sdeiss** [comment]
Given the error message below, and being new to Brian2 and not a software sleuth, I do not understand the solution that you have suggested for installing.  Can you walk a newbie through how to fix this?

(C:\Users\Steve\Anaconda3) C:\Users\Steve>conda install -c conda-forge brian2
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\Steve\Anaconda3:

The following NEW packages will be INSTALLED:

    blas:          1.0-mkl
    brian2:        2.2.2.1-py36he980bc4_0 conda-forge
    certifi:       2019.3.9-py36_0        conda-forge
    gsl:           2.4-hfa6e2cd_1004      conda-forge
    py-cpuinfo:    5.0.0-py_0             conda-forge
    pysocks:       1.6.8-py36_1002        conda-forge
    urllib3:       1.24.2-py36_0          conda-forge
    vc:            14-0                   conda-forge
    win_inet_pton: 1.1.0-py36_0           conda-forge
    wincertstore:  0.2-py36_1002          conda-forge

The following packages will be UPDATED:

    conda:         4.3.21-py36_0                      --> 4.6.14-py36_0           conda-forge
    conda-env:     2.6.0-0                            --> 2.6.0-1                 conda-forge
    cython:        0.25.2-py36_0                      --> 0.29.7-py36h6538335_0   conda-forge
    menuinst:      1.4.7-py36_0                       --> 1.4.16-py36_0           conda-forge
    pycosat:       0.6.2-py36_0                       --> 0.6.3-py36hfa6e2cd_1001 conda-forge
    requests:      2.14.2-py36_0                      --> 2.21.0-py36_1000        conda-forge
    setuptools:    27.2.0-py36_1                      --> 41.0.1-py36_0           conda-forge

Proceed ([y]/n)? y

menuinst-1.4.1 100% |###############################| Time: 0:00:00   1.53 MB/s
blas-1.0-mkl.t 100% |###############################| Time: 0:00:00 516.62 kB/s
conda-env-2.6. 100% |###############################| Time: 0:00:00 211.33 kB/s
vc-14-0.tar.bz 100% |###############################| Time: 0:00:00 165.63 kB/s
gsl-2.4-hfa6e2 100% |###############################| Time: 0:00:00   5.84 MB/s
certifi-2019.3 100% |###############################| Time: 0:00:00   4.93 MB/s
cython-0.29.7- 100% |###############################| Time: 0:00:07 275.53 kB/s
py-cpuinfo-5.0 100% |###############################| Time: 0:00:00 995.79 kB/s
pycosat-0.6.3- 100% |###############################| Time: 0:00:00   3.57 MB/s
win_inet_pton- 100% |###############################| Time: 0:00:00 581.90 kB/s
wincertstore-0 100% |###############################| Time: 0:00:00   1.45 MB/s
pysocks-1.6.8- 100% |###############################| Time: 0:00:00   1.49 MB/s
setuptools-41. 100% |###############################| Time: 0:00:00   8.13 MB/s
brian2-2.2.2.1 100% |###############################| Time: 0:00:00  10.13 MB/s
urllib3-1.24.2 100% |###############################| Time: 0:00:00   6.09 MB/s
requests-2.21. 100% |###############################| Time: 0:00:00   8.59 MB/s
conda-4.6.14-p 100% |###############################| Time: 0:00:00   9.82 MB/s
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::py-cpuinfo-5.0.0-py_0'.
CondaError: Cannot link a source that does not exist. C:\Users\Steve\Anaconda3\Scripts\conda.exe
Attempting to roll back.

CondaError: Cannot link a source that does not exist. C:\Users\Steve\Anaconda3\Scripts\conda.exe

(C:\Users\Steve\Anaconda3) C:\Users\Steve>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit
