### ISSUE TITLE
Refractoriness with `timestep` is slow

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2#991]
We've put some effort into making the newly introduced `timestep` function fairly fast, but I realized that it does still lead to a big slowdown for simple models that use refractoriness, e.g. CUBA. I'm still updating our benchmark suite with new tests that should show this, I'll post a link here when they are ready.

It seems that instead of having a `timestep` function that deals well with infinity it is faster to not have it deal with infinity at all, but instead formulate the refractoriness update as:
```Python
not_refractory = (t == -inf) or (timestep(t - lastspike, dt) >= timestep(refractory_time, dt))
```

**Pros:**
* seems to be faster (no comparison necessary for t values that are -infinity anyway)
* no arbitrary timestep value that we return for infinity

**Cons:**
* Not perfectly backwards compatible for users that started using `timestep` directly in their code since the 2.1.3 release (I doubt there are many)
* In principle this would break if someone gives `inf*second` as the refractory time (as an---albeit inefficient---way to switch it off). We could add another `or refractory_time == inf`, though (not sure how much that slows things down)

**Comment by mstimberg** [comment]
It's not the comparison, I think `isinf` is as efficient as it can be. My hunch is that the difference is that by short-circuiting, we don't do an unnecessary subtraction/comparison/`timestep` call for neurons with `lastspike == -inf`. In the CUBA example, these are quite a few, e.g. after 1s ~30% of the cells never spiked, and after 10s it is still ~5%.

But it seems that the change only has a strong effect when I do another more general optimization at the same time. Our code currently generates stuff like:
```C++
const double dt = _ptr_array_defaultclock_dt[0];
```
which is a bit of a pity, since `dt` does not change during the run. I replaced this instead by the value, this probably helps the compiler optimizing stuff. Maybe also it inlines the simpler function whereas it doesn't when it contains the `if (std::isinf(...))`? I'll do some more detailed benchmarks later.

PS: Yes, it should have been `lastspike == -inf`

**Comment by thesamovar** [comment]
I'm not sure inserting the value of dt is worth it, and it means adding recompilations if the user is changing dt.

**Comment by thesamovar** [comment]
Will wait for detailed benchmarks before further comment.

**Comment by mstimberg** [comment]
Ok, I did a bit of detailed benchmarking, the results are a bit depressing, though. Instead of running CUBA, I ran a model where all the state updater does is evaluating the refractoriness condition. I ran this for 100000 neurons and 10000 time steps, for different numbers of neurons that have never spiked, i.e. where `lastspike == -inf`. For any network, we start with 100% for this, and gradually go towards the lower end. My benchmarking script was this:
```Python
from brian2 import *

set_device('cpp_standalone')

results = []
for never_spiked in [0., 0.1, 0.5, 0.9, 1.]:
    print(never_spiked)
    for repeat in range(5):
        device.reinit()
        device.activate(clean=True)
        start_scope()
        G = NeuronGroup(100000, '',
                        threshold='False', refractory=5*ms, method='euler')
        # Set lastspike to a random value for the neurons that have spiked
        G.lastspike['rand() > never_spiked'] = '-rand()*5*ms'
        run(10000*defaultclock.dt, profile=True)
        profiling_info = dict(magic_network.profiling_info)
        results.append((never_spiked,
                        profiling_info[G.state_updater.codeobj.name]/ms))
```

I only benchmarked C++ standalone, because I think this is where we care the most about performance.
The results are here (legacy evaluation without time step function on the left, current code with the time step function on the right):

![figure_1](https://user-images.githubusercontent.com/1381982/44537912-3670c980-a700-11e8-993d-7ca34cfde866.png)

The dotted lines are when dt's value is directly inserted into the code, green is our current solution (i.e. where the `timestep` function checks for `inf`), and red is my proposed solution where the refractoriness code is `lastspike == -inf or timestep....`, and the `timestep` function itself does not deal with `inf`. As a side note, I realized that `refractoriness == inf` is not something that we really need to take care of...

**Comment by thesamovar** [comment]
OK so what can we make of this?

Firstly, that ``timestep`` is slow, but slow compared to a null model so maybe that's not a problem? Might be worth putting in a simple LIF model into the test to see what these differences do as a fraction of that?

Second, performance is worst when the percent that never spiked is close to 50%. The only way I can think to explain this is branch prediction. If that percent is low or high, then the processor will quickly start to speculatively execute the correct branch most of the time. Typically, I guess for most of the time we'll be towards the 0% end. Did you have ``-funsafe-math-optimizations`` enabled? I can't see why there would be such a difference between frozen and variable dt. In any case, for the frozen dt when the percent is close to 0% the performance is not too bad.

How well does it work if we set ``lastspike`` to a large negative number rather than ``-inf`` and throw away all inf-related code (but keep timestep)?

**Comment by mstimberg** [comment]
> Did you have `-funsafe-math-optimizations` enabled?

No, I used our standard preferences.

> How well does it work if we set lastspike to a large negative number rather than -inf and throw away all inf-related code (but keep timestep)?

Hmm, that solution + frozen dt works... pretty well:
![figure_2](https://user-images.githubusercontent.com/1381982/44595026-215f6d80-a7c8-11e8-99c5-11997cec3451.png)

> Might be worth putting in a simple LIF model into the test to see what these differences do as a fraction of that?

In the current master version (i.e. with the `timestep` function and its `std::isinf` check, no freezing for `dt`), if I add `dv/dt = (v-El)/taum : 1 (unless refractory)` as equations and solve them exactly, the runtime of the state updater goes up by about 400ms, so the refractoriness check *is* a significant part of the runtime for such simple models...

**Comment by mstimberg** [comment]
> I guess with frozen dt it might be that the compiler is optimising it all way entirely, because we'll be setting t=i*dt then essentially doing j=int(floor(t/dt)). If you know the value of dt you can perhaps detect whether or not int(floor((i*dt)/dt)) will always be i?

I don't think it is quite that, since we are not calling `timestep(t, dt)` but `timestep(t - lastspike, dt)`.

> The only other idea I can come up with is that the difference is a float divide, and in the case where you know dt you can decide if you can safely replace a /dt with a *some_constant.

I did a few tests in a simplified example, manually inserted a multiplication instead of a division, etc. but nothing did change so I am still a bit clueless as to what the reason behind this speed gain is. However, I saw that another optimisation works that has the advantage of not triggering re-compilations. Currently, we are generating code that looks like this:
```C++
    	// scalar code
    	const int _vectorisation_idx = -1;
        const double dt = _ptr_array_defaultclock_dt[0];
        const int64_t _lio_1 = _timestep(0.005, dt);
    	const int _N = N;
    	for(int _idx=0; _idx<_N; _idx++)
    	{
    	    // vector code
    	    const int _vectorisation_idx = _idx;
            const double dt = _ptr_array_defaultclock_dt[0];
            const double lastspike = _ptr_array_neurongroup_lastspike[_idx];
            const double t = _ptr_array_defaultclock_t[0];
            char not_refractory;
            not_refractory = _timestep(t - lastspike, dt) >= _lio_1;
            _ptr_array_neurongroup_not_refractory[_idx] = not_refractory;
    	}
```
We get `t` and `dt` again and again for each neuron, even though of course they do not change. In principle the compiler should be able to figure this out, but it seems it does not, even when the pointers are marked as restricted (as a side note: they are not currently marked as restricted, because this has been disabled for scalars "for safety reasons", even though I'm not sure why...).

I'll see whether I can fix this, preliminary tests with hacked code seem to show that this makes things as fast as the "freezing".

**Comment by mstimberg** [comment]
To follow up: it makes things indeed fast, but I also realized that our `timestep` function should return `int64` and not just `int`, otherwise we'd have to be very careful what "big value" to chose to represent `inf`, and it would depend on the timestep, etc. Be it as it may, PR is on the way!
