### ISSUE TITLE
How to set up for a simulation with multi-build and multi-run in standalone mode?

### ISSUE THREAD

**Issue by XiaoquinNUDT** [brian-team/brian2#999]
I have tried to compile and run a simulation with multi-build and multi-run, but failed. I have added the "reinit() and activate()" and tried other setting parameters such as "set_device(...), device.build(...)". And the most important thing is that after the first "device.build()" has been done and the first simulation is performed,  it still report "NotImplementedError: Cannot retrieve the values of state variables in standalone code before the simulation has been run." when the second simulation of the same network is to be built. The code is as followed:

from brian2 import *
import brian2 as b2

set_device('cpp_standalone', directory='CUBA', build_on_run = False)
prefs.devices.cpp_standalone.openmp_threads = 4
defaultclock.dt = 0.2*b2.ms

taum = 20*ms
taue = 5*ms
taui = 10*ms
Vt = -50*mV
Vr = -60*mV
El = -49*mV

eqs = '''
dv/dt  = (ge+gi-(v-El))/taum : volt (unless refractory)
dge/dt = -ge/taue : volt (unless refractory)
dgi/dt = -gi/taui : volt (unless refractory)
'''

P = NeuronGroup(4000, eqs, threshold='v>Vt', reset='v = Vr', refractory=5*ms,
                method='exact')
P.v = 'Vr + rand() * (Vt - Vr)'
P.ge = 0*mV
P.gi = 0*mV

we = (60*0.27/10)*mV # excitatory synaptic weight (voltage)
wi = (-20*4.5/10)*mV # inhibitory synaptic weight
Ce = Synapses(P, P, on_pre='ge += we')
Ci = Synapses(P, P, on_pre='gi += wi')
Ce.connect('i<3200', p=0.02)
Ci.connect('i>=3200', p=0.02)

s_mon = SpikeMonitor(P)

run(1 * second, report = 'text')
run(2 * second, report = 'text')
device.build(directory = 'CUBA', compile = True, run = True, debug = False)
device.reinit()
device.activate(directory = 'CUBA', compile = True, run = False, debug = False)
run(1 * second, report = 'text')
run(2 * second, report = 'text')
device.build(directory = 'CUBA', compile = True, run = True, debug = False)

log files:

[brian_debug_Am4CRt.log](https://github.com/brian-team/brian2/files/2330443/brian_debug_Am4CRt.log)

Also, I have tried the condition with multi-build and single-run. it just didn't work.
 Codes is as followed:

from brian2 import *
import brian2 as b2

set_device('cpp_standalone', directory='CUBA', build_on_run = True)
prefs.devices.cpp_standalone.openmp_threads = 4
defaultclock.dt = 0.2*b2.ms

taum = 20*ms
taue = 5*ms
taui = 10*ms
Vt = -50*mV
Vr = -60*mV
El = -49*mV

eqs = '''
dv/dt  = (ge+gi-(v-El))/taum : volt (unless refractory)
dge/dt = -ge/taue : volt (unless refractory)
dgi/dt = -gi/taui : volt (unless refractory)
'''

P = NeuronGroup(4000, eqs, threshold='v>Vt', reset='v = Vr', refractory=5*ms,
                method='exact')
P.v = 'Vr + rand() * (Vt - Vr)'
P.ge = 0*mV
P.gi = 0*mV

we = (60*0.27/10)*mV # excitatory synaptic weight (voltage)
wi = (-20*4.5/10)*mV # inhibitory synaptic weight
Ce = Synapses(P, P, on_pre='ge += we')
Ci = Synapses(P, P, on_pre='gi += wi')
Ce.connect('i<3200', p=0.02)
Ci.connect('i>=3200', p=0.02)

s_mon = SpikeMonitor(P)

run(1 * second, report = 'text')
device.reinit()
device.activate(directory = 'CUBA', compile = True, run = False, debug = False)
run(1 * second, report = 'text')

plot(s_mon.t/ms, s_mon.i, ',k')
xlabel('Time (ms)')
ylabel('Neuron index')
show()

log file:
[brian_debug_Fre7vp.log](https://github.com/brian-team/brian2/files/2330450/brian_debug_Fre7vp.log)

**Comment by mstimberg** [comment]
[Hi. Please use the [briansupport list](https://groups.google.com/forum/#!forum/briansupport) (briansupport@googlegroups.com) for general questions in the future, we try to keep the github issues for bugs and feature requests.]

I'm not 100% sure what exactly your simulation workflow is supposed to be. After the first run(s) + `device.build`, do you want to run again from the start? In this case, you'll have to create the full network again (e.g. you could put everything in a loop), after a `device.reinit`, the standalone device "forgets" about everything, so you have to create all objects/synapses, etc. again. I have to admit that the error message is misleading, though.

**Comment by XiaoquinNUDT** [comment]
Thanks! Got it.
